Fix docker inspect network go template for network which doesn't have MTU
kubernetes/minikube pull request #10053
Opened 2020-12-27 08:46 UTC by azhao155

First create network  without MTU

```
docker@p1:~$ docker network create m1
c3d778d8147416d2dd0d466e77c845191b26915614c3de3e4b7aacad08fd63f9
docker@p1:~$ docker network inspect m1 --format '{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{e
nd}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Conta
iners }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}'
{"Name": "m1","Driver": "bridge","Subnet": "172.18.0.0/16","Gateway": "172.18.0.1","MTU": 0, "ContainerIPs": []}
```
Create network with MTU

```
docker@p1:~$ docker network create m2 --opt com.docker.network.driver.mtu=9216
1b07fe461e1682b8010951bd17617f1c620144a8d34e22cd4e844860db2c3ee4
docker@p1:~$ docker network inspect m2 --format '{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{e
nd}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Conta
iners }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}'
{"Name": "m2","Driver": "bridge","Subnet": "172.19.0.0/16","Gateway": "172.19.0.1","MTU": 9216, "ContainerIPs": []}
```

So this go template will work in both scenarios.

2020-12-27 08:46 UTC, azhao155 commented
@medyagh

2020-12-27 08:47 UTC, azhao155 commented
fix https://github.com/kubernetes/minikube/issues/10033

2020-12-28 05:28 UTC, medyagh commented
/ok-to-test

2020-12-28 20:32 UTC, medyagh commented
/retest-this-please

2020-12-29 21:15 UTC, medyagh reviewed
how about adding a unit test for this func ? 

maybe we can have a a "mockDocker" driver

with an optinal mock parameter passed, if it is mock

then we can have a unit test for a series of examples of response...

2020-12-29 21:17 UTC, medyagh commented
we can also have a Specific Error Type to return if the user's docker has issue and user needs to upgrade docker

https://github.com/kubernetes/minikube/issues/9811#issuecomment-748465051

2020-12-29 21:19 UTC, medyagh reviewed
example of mocking unit test https://github.com/medyagh/minikube/blob/199ea3425b8343e533d8d1982ad750a8dab7d59e/pkg/drivers/kic/oci/info_test.go#L23

2020-12-30 21:52 UTC, medyagh commented on pkg/drivers/kic/oci/network_create_test.go
> +func TestDockerInspectWithMTU(t *testing.T) {
how about putting this in a for loop that goes over the test cases ? feel free to say no if u think this is better, but here is an example
https://github.com/medyagh/minikube/blob/199ea3425b8343e533d8d1982ad750a8dab7d59e/cmd/minikube/cmd/status_test.go#L68

so maybe we could put both of these tests in one test and have a for loop of test cases?

2020-12-30 23:32 UTC, medyagh requested changes

2020-12-30 23:32 UTC, medyagh commented on pkg/drivers/kic/oci/network_create_test.go
> +func TestDockerInspectWithMTU(t *testing.T) {
rename the func

2020-12-31 06:14 UTC, medyagh approved these changes

2020-12-31 06:15 UTC, medyagh approved these changes

2020-12-31 06:16 UTC, medyagh commented
thank you for fixing this and adding unit tests for it too

2020-12-31 06:16 UTC, merged