Fix flakiness of parallel docker-env test
kubernetes/minikube pull request #10118
Opened 2021-01-09 18:50 UTC by azhao155

This pr is create per cluster certs for docker-env. So in parallel testing, would fix race condition issue of getting certs.

2021-01-09 18:50 UTC, azhao155 commented
send out pr to verify if it can fix the flakiness.

2021-01-09 19:26 UTC, medyagh requested changes

2021-01-09 19:26 UTC, medyagh commented on pkg/provision/provision.go
> +	//if err := copyHostCerts(authOptions); err != nil {
any reason we have this commented code?

2021-01-09 19:27 UTC, medyagh commented
/ok-to-test

2021-01-10 03:06 UTC, medyagh commented
On first test seems to be fixing the docker-env flake

2021-01-10 03:06 UTC, medyagh commented
/retest-this-please

2021-01-11 17:43 UTC, medyagh commented
/retest-this-please

2021-01-13 17:23 UTC, medyagh requested changes

2021-01-13 17:23 UTC, medyagh commented on pkg/minikube/machine/client.go
> +		flock:        fslock.New(localpath.MakeMiniPath("fileLock.txt")),
let give a better name to the lock,how about "machine_client.lock"  ?

2021-01-13 17:23 UTC, medyagh commented on pkg/minikube/machine/client.go
> +					return fmt.Errorf("falied to acquire lock > " + lockErr.Error())
use %v formatting for the error and maybe more descriptive
```
fmt.Errorf("failed to acquire bootstrap client lock: %v " + lockErr)
```

2021-01-13 17:23 UTC, medyagh commented on pkg/minikube/machine/client.go
> +						klog.Errorf("falied to release lock > %s", lockErr.Error())
same here, use %v
```
klog.Errorf("falied to release bootstrap cert client lock  %v", lockErr)

```

2021-01-13 18:34 UTC, medyagh requested changes

2021-01-13 18:34 UTC, medyagh commented on pkg/minikube/machine/client.go
> +						klog.Errorf("falied to release bootstrap cert client lock  %v", lockErr.Error())
colon here too

klog.Errorf("falied to release bootstrap cert client lock:  %v")

2021-01-13 18:34 UTC, medyagh commented on pkg/minikube/machine/client.go
> +				lockErr := api.flock.LockWithTimeout(time.Second * 5)
add issue link here why we do this...say this causes docker-env in parallel work

2021-01-13 18:41 UTC, medyagh requested changes

2021-01-13 18:41 UTC, medyagh commented on pkg/minikube/machine/client.go
> +				// it will break Docker-Env test in parallel tesing.
add the issue number on github 
and change wording to
"this lock is needed to run docker-env tests in parallel issuue #... "

2021-01-13 19:46 UTC, medyagh approved these changes

2021-01-13 19:46 UTC, merged