Move DeletePossibleKicLeftOver function to delete pkg
kubernetes/minikube pull request #10321
Opened 2021-01-30 12:51 UTC by BLasan

fixes #8040 

Moved DeletePossibleKicLeftOver function from cmd/minikube/delete.go to a new package "delete" in order to make the function accessible from other packages.

2021-01-30 13:28 UTC, BLasan commented
@medyagh @tstromberg  Please review

2021-02-01 18:09 UTC, medyagh requested changes
I dont agree with the naming, the package naming should not stutter.

delete.DeletePossibe... doesn't sounds right

2021-02-01 18:26 UTC, BLasan commented
> I dont agree with the naming, the package naming should not stutter.
> 
> delete.DeletePossibe... doesn't sounds right

Yuh, is it ok to change the function name as well? I'll change the function name in to a meaningful one :)

2021-02-01 18:45 UTC, BLasan commented
> I dont agree with the naming, the package naming should not stutter.
> 
> delete.DeletePossibe... doesn't sounds right

Renamed. Please review

2021-02-03 19:22 UTC, BLasan commented
@medyagh Please review

2021-02-06 02:59 UTC, BLasan commented
@medyagh Sir, could you please verify this? If there are changes need to be done I would like to add them as well :)

2021-02-06 17:03 UTC, BLasan commented
@afbjorklund Sir, could you please verify these changes?

2021-02-10 00:59 UTC, medyagh requested changes
@BLasan what do u think about making a new package that is a noun

for example "profile"

so the could would read as

profile.DeletePossibleLeftovers()

2021-02-10 02:41 UTC, BLasan commented
> @BLasan what do u think about making a new package that is a noun
> 
> for example "profile"
> 
> so the could would read as
> 
> profile.DeletePossibleLeftovers()

That sounds ideal sir! Before that I think we need to merge new changes done in the issue #10332. According to your suggestion above, isn't it good if we could define all the profile related functions(which are defined in "cmd/delete.go" file) under "profile" package?

2021-02-11 03:20 UTC, BLasan commented
@medyagh @priyawadhwa Resolved the merge conflicts. Kindly take a look

2021-02-11 18:27 UTC, priyawadhwa reviewed
Left a couple comments, this is pretty close to finished!

2021-02-11 18:27 UTC, priyawadhwa commented on pkg/minikube/profile/profile.go
> +//DeletePossibleLeftOvers ...
can you fill in this comment?

2021-02-11 18:27 UTC, priyawadhwa commented on pkg/minikube/profile/profile.go
> +/*
Let's name this file `delete.go` instead of `profile.go`

2021-02-11 18:30 UTC, BLasan commented on pkg/minikube/profile/profile.go
> +//DeletePossibleLeftOvers ...
Sure

2021-02-11 19:22 UTC, BLasan commented
@priyawadhwa Changes added. Please review ma'am

2021-02-16 19:07 UTC, BLasan commented
@priyawadhwa Any remaining things to be added ma'am?

2021-02-17 18:04 UTC, priyawadhwa reviewed
One last comment

2021-02-17 18:04 UTC, priyawadhwa commented on go.mod
> +	k8s.io/klog v1.0.0
We want to use k8s.io/klog/v2 through the codebase, so to fix this I would:

1. Replace any imports of `k8s.io/klog` with `k8s.io/klog/v2`
2. Run `go mod tidy` to remove this dependency from go.mod

2021-02-17 18:04 UTC, priyawadhwa commented on pkg/minikube/delete/delete.go
> +	"k8s.io/klog"
this should be k8s.io/klog/v2

2021-02-17 18:22 UTC, BLasan commented
@priyawadhwa Thanks for the review ma'am. Made the required changes

2021-02-17 18:33 UTC, priyawadhwa approved these changes
LGTM, thank you!

2021-02-20 03:42 UTC, BLasan commented
@medyagh @priyawadhwa Any remaining works?

2021-02-24 01:15 UTC, merged