(docs) update docs/start/_index.md`
kubernetes/minikube pull request #10341
Opened 2021-02-02 10:12 UTC by vladdoster

- cask is now denoted as a flag `--cask`

![image](https://user-images.githubusercontent.com/10052309/106585051-89275000-650c-11eb-8505-345c305d8076.png)

# Before

![image](https://user-images.githubusercontent.com/10052309/106585236-bb38b200-650c-11eb-9884-f3c468897d04.png)

# After

![image](https://user-images.githubusercontent.com/10052309/106585336-d4416300-650c-11eb-8e75-e5f9da08a302.png)

2021-02-03 19:10 UTC, priyawadhwa requested changes
Thanks for improving this! Just left one comment.

2021-02-03 19:10 UTC, priyawadhwa commented on site/content/en/docs/start/_index.md
> +If which minikube fails after installation via brew, you may have to remove the old minikube links and link the newly installed binary:
Can you keep the backticks around `which minikube` to indicate that it is a command to run

2021-02-06 14:58 UTC, vladdoster commented
> Thanks for improving this! Just left one comment.

Thank you for catching that. I have added back `` around `which minikube`.

2021-02-10 19:07 UTC, priyawadhwa approved these changes
LGTM, thanks for fixing this!

2021-02-10 19:08 UTC, merged