Improve UI advice in cluster deletion
kubernetes/minikube pull request #10473
Opened 2021-02-13 20:37 UTC by BLasan

fixes #10460 

Before PR
See #10460 

After PR
Cluster Deletion error message will be prompted under three conditions. When `memInMB != cc.Memory` or `viper.GetInt(cpus) != cc.CPUs`or `memInMB != existing.DiskSize` . According to the newly added condition, the confusing error message will not be printed if one of the conditions get satisfied.

2021-02-13 20:38 UTC, BLasan commented
@priyawadhwa @medyagh Please review

2021-02-15 19:15 UTC, BLasan commented
@medyagh @priyawadhwa Please review

2021-02-17 18:55 UTC, BLasan commented
@priyawadhwa @medyagh Please review

2021-02-17 21:21 UTC, medyagh requested changes
I am not sure if this PR is fixing the issue, and also it is ignoring the errors _ which should not be done.

2021-02-17 22:06 UTC, BLasan commented
> I am not sure if this PR is fixing the issue, and also it is ignoring the errors _ which should not be done.

We need to avoid printing that particular error log if it satisfies one of the above conditions right? There's a mistake in logic I guess. If you have an idea I would like to hear from you sir

2021-03-30 04:16 UTC, closed without merging