Use golang:1.16.0 docker image to build kicbase
kubernetes/minikube pull request #10502
Opened 2021-02-17 22:21 UTC by ilya-zuyev

Bump golang:1.16-rc1 -> golang:1.16.0

2021-02-17 22:28 UTC, tstromberg approved these changes

2021-02-17 22:28 UTC, tstromberg requested changes
The CL description seems suspect: is BUILD_IMAGE really only used to build kicbase?

2021-02-17 23:26 UTC, ilya-zuyev commented
> The CL description seems suspect: is BUILD_IMAGE really only used to build kicbase?

Thanks! Fixed.

2021-02-18 00:22 UTC, tstromberg approved these changes

2021-02-18 00:45 UTC, merged