Rename None driver to Native and replace all references
kubernetes/minikube pull request #10579
Opened 2021-02-23 12:19 UTC by sadlil

Fixes: #7772

2021-02-23 18:01 UTC, medyagh requested changes
can u plz verify, starting a cluster with minikube 1.17.1 
```
minkube start --driver=none
```

and then stop it
and then start the same cluster with your PR
and ensure it still backward campatible ?

2021-02-23 18:02 UTC, medyagh requested changes
all instances of Baremetal should stay same since they include Mock

2021-02-23 18:02 UTC, medyagh commented on pkg/minikube/machine/client.go
> +	if driver.IsNative(h.Driver.DriverName()) {
all instances of Baremetal should stay same since they include Mock

2021-02-23 18:02 UTC, medyagh commented on pkg/minikube/machine/client.go
> +				if driver.IsNative(h.Driver.DriverName()) {
all instances of Baremetal should stay same since they include Mock

2021-02-23 18:02 UTC, medyagh commented on pkg/minikube/machine/client.go
> +				if driver.IsNative(h.Driver.DriverName()) {
same here

2021-02-23 18:02 UTC, medyagh commented on pkg/minikube/machine/fix.go
> +	if !driver.IsNative(h.Driver.DriverName()) {
same here

2021-07-13 20:57 UTC, andriyDev commented
Hi @sadlil, I'm gonna close this PR since it's been stuck for a while. If you'd like to bring it back, feel free to reopen!

2021-07-13 20:57 UTC, closed without merging