Fix Tests: Added a new step and changed Step to ErrT for err logs
kubernetes/minikube pull request #10603
Opened 2021-02-24 22:15 UTC by spowelljr

Closes: #10591

Registered a new step for a missing instance and changed `Step` to `ErrT` when outputing error logs.

2021-02-24 22:16 UTC, spowelljr commented
/ok-to-test

2021-02-25 00:35 UTC, spowelljr commented
/ok-to-test

2021-02-25 19:29 UTC, sharifelgamal approved these changes

2021-02-25 22:41 UTC, priyawadhwa commented on pkg/minikube/out/out.go
> +		return
I'd send this to Info or add a new "Styled" JSON type

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/config/disable.go
> +		out.Styled(style.AddonDisable, `"The '{{.minikube_addon}}' addon is disabled`, out.V{"minikube_addon": addon})
out.Step

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/delete.go
> +	out.Styled(style.Deleted, "Successfully purged minikube directory located at - [{{.minikubeDirectory}}]", out.V{"minikubeDirectory": localpath.MiniPath()})
out.step

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/delete.go
> +			out.Styled(style.DeletingHost, `Deleting "{{.profile_name}}" in {{.driver_name}} ...`, out.V{"profile_name": profile.Name, "driver_name": profile.Config.Driver})
out.step

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/delete.go
> +	out.Styled(style.Resetting, "Uninstalling Kubernetes {{.kubernetes_version}} using {{.bootstrapper_name}} ...", out.V{"kubernetes_version": cc.KubernetesConfig.KubernetesVersion, "bootstrapper_name"
out.step

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/delete.go
> +		out.Styled(style.DeletingHost, `Removing {{.directory}} ...`, out.V{"directory": machineDir})
out.step

2021-02-25 22:41 UTC, priyawadhwa commented on cmd/minikube/cmd/generate-docs.go
> +		out.Styled(style.Documentation, "Docs have been saved at - {{.path}}", out.V{"path": path})
out.step

2021-03-01 21:58 UTC, medyagh requested changes

2021-03-01 21:58 UTC, medyagh commented on pkg/minikube/bootstrapper/kubeadm/kubeadm.go
> +func (k *Bootstrapper) applyCNI(cfg config.ClusterConfig, isInit bool) error {
how about rename it to `registerStep bool`

2021-03-01 21:58 UTC, medyagh commented on pkg/minikube/bootstrapper/kubeadm/kubeadm.go
> +	// when not on init, can run in parallel and break step output order
thanks for the comment

2021-03-01 21:58 UTC, medyagh commented on pkg/minikube/bootstrapper/kubeadm/kubeadm.go
> +func (k *Bootstrapper) applyCNI(cfg config.ClusterConfig, isInit bool) error {
make this argument optional
so other callers can just called it

applyCNI
and if not True then it wont register step

2021-03-03 19:15 UTC, medyagh approved these changes

2021-03-03 19:16 UTC, merged