try autopushing to PRs for kicbase
kubernetes/minikube pull request #10611
Opened 2021-02-25 01:51 UTC by sharifelgamal

2021-02-25 01:53 UTC, sharifelgamal commented
ok-to-build-image

2021-02-25 18:52 UTC, sharifelgamal commented
ok-to-build-image

2021-02-25 20:48 UTC, sharifelgamal commented
ok-to-build-image

2021-02-25 20:59 UTC, medyagh requested changes

2021-02-25 20:59 UTC, medyagh commented on hack/jenkins/kicbase_auto_build.sh
> +	message="Hi ${ghprbPullAuthorLoginMention}, we have updated your PR with the reference to newly built kicbase image. Pull the changes locally if you want to test with them or updateyour PR further."
updateyour -->  update your

2021-02-25 21:00 UTC, sharifelgamal commented on hack/jenkins/kicbase_auto_build.sh
> +	message="Hi ${ghprbPullAuthorLoginMention}, we have updated your PR with the reference to newly built kicbase image. Pull the changes locally if you want to test with them or updateyour PR further."
fixed

2021-02-26 22:40 UTC, sharifelgamal commented
ok-to-build-image

2021-02-26 22:50 UTC, medyagh approved these changes

2021-03-01 17:19 UTC, merged