Silent output when talking to a shell
kubernetes/minikube pull request #10763
Opened 2021-03-09 16:49 UTC by afbjorklund

If the output is not a terminal, then assume that we are running
docker-env or podman-env under "eval" or similar shell construct.

So don't output all the interactive information, but only return
the actual exit code for some further troubleshooting (perhaps).

Closes #10761

----

BEFORE

```console
$ eval $(minikube docker-env)
🤷: command not found
$ minikube docker-env
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"
```
or, even worse:
```console
$ export MINIKUBE_IN_STYLE=false
$ eval $(minikube docker-env)
CHANGELOG.md: command not found
$ minikube docker-env
* The control plane node must be running for this command
  - To start a cluster, run: "minikube start"
```

AFTER

```
$ eval $(minikube docker-env)
$
$ minikube docker-env
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"
```

2021-03-09 18:58 UTC, afbjorklund commented
> @afbjorklund could u plz post the before and after this PR in description ?

Already done, see https://github.com/kubernetes/minikube/issues/10761#issuecomment-794154350

2021-03-09 23:39 UTC, medyagh requested changes
I think adding an integraiton test will ensure we will never break this

how about adding one here in validateDockerEnv
https://github.com/medyagh/minikube/blob/8da592988da45acfc93cef2637e79a8bfa4ad570/test/integration/functional_test.go#L216

2021-03-10 07:13 UTC, afbjorklund commented on pkg/minikube/out/out.go
> +func IsTerminal(w fdWriter) bool {
They take slightly different parameters, writer vs fd, but we could make a new helper I suppose -but  it's just one line

2021-03-10 07:46 UTC, medyagh commented
/ok-to-test

2021-03-10 21:26 UTC, merged