Upgrade csi-hostpath addon to v1.6.0
kubernetes/minikube pull request #10798
Opened 2021-03-12 16:47 UTC by govargo

### What type of PR is this?
/area addons

### What this PR does / why we need it:

This PR upgrades the csi-hostpath-driver addon to v1.6.0(latest).
And this PR make `volumesnapshots` addon contain the volumesnapshotclass `csi-hostpath-snapclass`.
Before this PR, the users have to register the volumesnapshotclass manually.
After this PR, however, user don't have to register the volumesnapshotclass by only enabling addon `volumesnapshots`.
I also update the turtorial for [CSI Driver and Volume Snapshots](https://minikube.sigs.k8s.io/docs/tutorials/volume_snapshots_and_csi/).

### Which issue(s) this PR fixes:
Fix #10797 

### Does this PR introduce a user-facing change?

Yes, this PR change VolumeSnaphost API version(v1).

**Before this PR**

```
% ./out/minikube addons enable csi-hostpath-driver
...
    ▪ Using image quay.io/k8scsi/csi-attacher:v3.0.0-rc1
    ▪ Using image quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
    ▪ Using image quay.io/k8scsi/hostpathplugin:v1.4.0-rc2
    ▪ Using image quay.io/k8scsi/livenessprobe:v1.1.0
    ▪ Using image quay.io/k8scsi/csi-resizer:v0.6.0-rc1
    ▪ Using image quay.io/k8scsi/csi-snapshotter:v2.1.0
    ▪ Using image gcr.io/k8s-staging-sig-storage/csi-provisioner:v2.0.0-rc2
```

```
% ./out/minikube addons enable volumesnapshots
// Users have to register the volumesnapshotclass manually
% kubectl get volumesnapshotclasses
No resources found
```

**After this PR**

Entire docker images of the addon are upgraded.

```
% ./out/minikube addons enable csi-hostpath-driver
...
    ▪ Using image k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
    ▪ Using image k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-external-health-monitor-agent:v0.2.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.2.0
    ▪ Using image k8s.gcr.io/sig-storage/hostpathplugin:v1.6.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
    ▪ Using image k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
```

```
% ./out/minikube addons enable volumesnapshots
// Volumesnapshotclass is registered automatically
% kubectl get volumesnapshotclasses
NAME                     DRIVER                DELETIONPOLICY   AGE
csi-hostpath-snapclass   hostpath.csi.k8s.io   Delete           10s
```

### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
NONE
```

2021-03-12 16:48 UTC, govargo commented
/assign @tstromberg

2021-03-12 19:18 UTC, medyagh approved these changes

2021-03-12 19:19 UTC, medyagh commented
/ok-to-test

2021-03-12 20:44 UTC, medyagh commented
@govargo the CSI test fails on Docker
https://storage.googleapis.com/minikube-builds/logs/10798/3aa47d5/Docker_Linux.html#fail_TestAddons%2fparallel%2fCSI

2021-03-12 20:44 UTC, medyagh requested changes
please ensure to fix the test 
https://storage.googleapis.com/minikube-builds/logs/10798/3aa47d5/Docker_Linux.html#fail_TestAddons%2fparallel%2fCSI

2021-03-15 16:28 UTC, govargo commented
@medyagh
Thank you for your point out, medya.
I fixed this error of disabling volumesnapshots addons.

I'll check the result of `CSI test on Docker` again.

2021-03-16 07:11 UTC, govargo commented
The test was passed!

https://storage.googleapis.com/minikube-builds/logs/10798/6654cf4/Docker_Linux.html#pass_TestAddons%2fparallel%2fCSI

2021-03-23 04:10 UTC, medyagh commented
/retest-this-please

2021-03-23 07:01 UTC, merged