Add solution message if Docker is rootless
kubernetes/minikube pull request #10878
Opened 2021-03-19 16:43 UTC by daehyeok

fixes #10652 
Message should be removed after #10836

```shell
ubuntu@rootless:~/out$ docker system info -f '{{json .}}'
{"ID":"E7PJ:D4AV:CFYR:2YLX:YWSM:3XFJ:PJGT:UALK:WKLF:HWHE:W2A2:JFB7","Containers":0,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":0,"Images":0,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":false,"KernelMemory":true,"KernelMemoryTCP":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":23,"OomKillDisable":true,"NGoroutines":39,"SystemTime":"2021-03-19T09:36:42.092055025-07:00","LoggingDriver":"json-file","CgroupDriver":"none","CgroupVersion":"1","NEventsListener":0,"KernelVersion":"5.4.0-67-generic","OperatingSystem":"Ubuntu 20.04.2 LTS","OSVersion":"20.04","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":4,"MemTotal":8348553216,"GenericResources":null,"DockerRootDir":"/home/ubuntu/.local/share/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"rootless","Labels":[],"ExperimentalBuild":false,"ServerVersion":"20.10.5","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"io.containerd.runtime.v1.linux":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"05f951a3781f4f2c1911b05e61c160e9c30eaa8e","Expected":"05f951a3781f4f2c1911b05e61c160e9c30eaa8e"},"RuncCommit":{"ID":"12644e614e25b05da6fd08a38ffa0cfe1903fdec","Expected":"12644e614e25b05da6fd08a38ffa0cfe1903fdec"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=default","name=rootless"],"Warnings":["WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode."],"ClientInfo":{"Debug":false,"Context":"default","Plugins":[{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.9.1-beta3","ShortDescription":"Docker App","Experimental":true,"Name":"app","Path":"/usr/libexec/docker/cli-plugins/docker-app"},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.5.1-docker","ShortDescription":"Build with BuildKit","Name":"buildx","Path":"/usr/libexec/docker/cli-plugins/docker-buildx"}],"Warnings":null}}

ubuntu@rootless:~/out$ docker system info -f "{{json .SecurityOptions}}"
["name=seccomp,profile=default","name=rootless"]

ubuntu@rootless:~/out$ ./minikube-linux-amd64 start
😄  minikube v1.18.1 on Ubuntu 20.04 (amd64)
✨  Automatically selected the docker driver. Other choices: ssh, none
E0319 09:37:39.656142    9157 start.go:749] Found Error : "rootless Docker not supported yet"

💣  Exiting due to PROVIDER_DOCKER_NOT_RUNNING: rootless Docker not supported yet
📘  Documentation: https://github.com/kubernetes/minikube/issues/10836
```

2021-03-20 07:23 UTC, medyagh requested changes

2021-03-20 07:23 UTC, medyagh commented on pkg/minikube/registry/drvs/docker/docker.go
> +			Healthy:   true,
healthy: false

2021-03-20 20:21 UTC, daehyeok commented on pkg/minikube/registry/drvs/docker/docker.go
> +			Healthy:   true,
done!

2021-03-23 01:57 UTC, medyagh approved these changes

2021-03-23 01:57 UTC, merged