[WIP] Fix to minikube cp functional test work on windows os
kubernetes/minikube pull request #10920
Opened 2021-03-25 01:27 UTC by anencore94

Bug from PR #10198 

resolve : #10914

2021-03-25 01:31 UTC, medyagh commented
@anencore94 
Checkout the setup certes in the functional. Test to see an example

2021-03-25 01:33 UTC, medyagh commented
Checkout other tests copying files 
```
func setupFileSync(ctx context.Context, t *testing.T, profile string) {
	p := localSyncTestPath
...
```

2021-03-26 06:30 UTC, anencore94 commented
Changed List
- make test code more understandable like `func setupFileSync(ctx context.Context, t *testing.T, profile string) {...}`
- change `filepath.IsAbs()` to `strings.HasPrefix()`.
  - since on windows host os, `filepath.IsAbs('/a/b/c')` equals false
  - I'm a bit confused why this happens..

Please Let me know if there are other issues.
Thanks a lot always, @medyagh

2021-03-29 16:28 UTC, medyagh requested changes

2021-03-29 16:28 UTC, medyagh commented on test/integration/functional_test.go
> +	dstPath := cpTestMinikubePath()
lets not make a func for that, and just simply put it here, easier to read

2021-03-29 16:33 UTC, merged