Create tr.md
kubernetes/minikube pull request #10982
Opened 2021-04-03 23:01 UTC by selek55

2021-04-03 23:14 UTC, selek55 commented
signed a CLA

2021-04-06 17:32 UTC, medyagh commented
/check-cla

2021-04-19 21:53 UTC, medyagh commented
@selek55 unfortunately the CLA is not signed yet or the system hasn't recognized it. would you please verify you signed the CLA with same email as `git config`?

2021-05-03 20:10 UTC, medyagh commented
/check-cla

2021-07-10 01:38 UTC, selek55 commented
signed a CLA

2021-07-13 16:57 UTC, spowelljr commented
@selek55 Thank you for signing the CLA! We have unfortunately updated the template for our GitHub Issues since your contribution. Would you mind updating it to match the new version? https://raw.githubusercontent.com/kubernetes/minikube/master/.github/ISSUE_TEMPLATE/__en-US.md

2021-07-13 17:06 UTC, spowelljr requested changes

2021-07-13 17:06 UTC, spowelljr commented on .github/ISSUE_TEMPLATE/tr.md
> +---
Could you please add a third tag here.
`labels: l/tr`

2021-07-21 18:32 UTC, spowelljr commented
@selek55 I'm going to close this issue due to it being open for a long duration. If at a later date you find the time to address the comments, feel free to reopen, thanks!

2021-07-21 18:32 UTC, closed without merging