Detect if go.sum changed after running go mod tidy
kubernetes/minikube pull request #11027
Opened 2021-04-08 19:04 UTC by spowelljr

Currently, we run `go mod tidy` in `make test` and check if the go.mod changed and fail it did. However, we don't check if the go.sum changed.

This becomes a problem when we go to release, `go mod tidy` is ran which will correct the go.sum, but makes the commit dirty and we have to make a PR to update the go.sum and run the deploy again.

This will detect if the go.sum should be updated during the unit test check in GitHub and will notify us, preventing the above issue.

2021-04-08 19:14 UTC, spowelljr commented
/ok-to-test

2021-04-08 22:28 UTC, medyagh requested changes

2021-04-08 22:28 UTC, medyagh commented on .github/workflows/pr.yml
> +      - "go.mod"
add same thing to the master.yml

2021-04-08 22:46 UTC, spowelljr commented on .github/workflows/pr.yml
> +      - "go.mod"
Done

2021-04-09 18:23 UTC, medyagh approved these changes

2021-04-09 18:24 UTC, merged