Update "Get started" page to use minikube syntax
kubernetes/minikube pull request #11023
Opened 2021-04-08 17:47 UTC by kam96

Users of this documentation are likely setting up minikube without the kubectl command available on their local environment. Other issues have been opened regarding this in the past. I haven't added further instructions myself to line 146 but it may be helpful to express the difference between a standalone kubectl command and the double-dashes used by minikube to stop parsing flags. 

The changes made continue to make use of minikube through the remainder of the page instead of using kubectl directly.

2021-04-08 20:39 UTC, afbjorklund commented on site/content/en/docs/start/_index.md
> +minikube kubectl create deployment hello-minikube -- --image=k8s.gcr.io/echoserver:1.4
Also https://github.com/kubernetes/minikube/issues/7289

2021-04-08 20:42 UTC, afbjorklund commented on site/content/en/docs/start/_index.md
> +minikube kubectl create deployment hello-minikube -- --image=k8s.gcr.io/echoserver:1.4
As seen on https://minikube.sigs.k8s.io/docs/handbook/kubectl/

2021-07-14 18:57 UTC, spowelljr commented
@kam96 CLA needs to be signed, along with addressing @afbjorklund's comments

2021-07-28 23:21 UTC, medyagh requested changes

2021-07-28 23:21 UTC, medyagh commented on site/content/en/docs/start/_index.md
> +minikube kubectl create deployment hello-minikube -- --image=k8s.gcr.io/echoserver:1.4
@kam96 I agree, with @afbjorklund would u please update it so everywhere it uses `minikube kubectl --`

2021-08-13 20:26 UTC, medyagh commented
@kam96 are you still working on this ?
The cla still needs to be signed

2021-09-15 18:48 UTC, sharifelgamal commented
I'm going to go ahead and close this for now. If you want to resume working on it, reopen it and sign the CLA.

2021-09-15 18:48 UTC, closed without merging