Add opt-in notifications for beta releases
kubernetes/minikube pull request #11169
Opened 2021-04-22 21:30 UTC by spowelljr

Closes #10328

Added a new config option that the user can enable to get notified of beta releases.

The user can opt-in with the following command:
```
minikube config set WantBetaUpdateNotification true
```

Release script need to be updated to update the `releases-beta.json` file with the release version.

2021-04-22 21:36 UTC, spowelljr commented
Just realized that with the current logic, a older beta will take priority over a newer full release. Will resolve this conflict and add a test for it.

2021-04-27 22:43 UTC, medyagh requested changes
lets change the get Names to proper go idiomatic and then looks good to me

2021-04-29 16:26 UTC, spowelljr commented
/ok-to-test

2021-04-29 21:03 UTC, medyagh approved these changes

2021-04-29 21:04 UTC, merged