completion: add specific shell completion
kubernetes/minikube pull request #11191
Opened 2021-04-25 07:01 UTC by zhijianli88

minikube$ minikube completion <tab>
bash  fish  zsh

Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>

2021-04-25 16:29 UTC, medyagh requested changes
@zhijianli88 thank you very much for this PR, does this break the old users who did NOT specify the type of the bash ?

Could we make it backward compatible ?

2021-04-26 01:10 UTC, zhijianli88 commented
> @zhijianli88 thank you very much for this PR, does this break the old users who did NOT specify the type of the bash ?
> 
> Could we make it backward compatible ?

Yes, i have just restored it

```bash
$ minikube completion

❌  Exiting due to MK_USAGE: Usage: minikube completion SHELL
```

2021-04-28 17:58 UTC, ilya-zuyev commented
Hey @zhijianli88. Thanks for your PR! Could you extend the PR description, adding more info why this PR important and how it improves the current behavior of `minikube completion`? Thanks!

2021-04-29 10:34 UTC, zhijianli88 commented
> Hey @zhijianli88. Thanks for your PR! Could you extend the PR description, adding more info why this PR important and how it improves the current behavior of `minikube completion`? Thanks!

PR description updated, PTAL.

2021-05-07 23:16 UTC, medyagh approved these changes

2021-05-07 23:16 UTC, medyagh approved these changes

2021-05-07 23:16 UTC, merged