Add a functional test for podman
kubernetes/minikube pull request #11265
Opened 2021-05-03 17:37 UTC by ilya-zuyev

Fixes https://github.com/kubernetes/minikube/issues/10673

2021-05-03 20:06 UTC, medyagh commented on test/integration/functional_test.go
> +	c := exec.CommandContext(mctx, "/bin/bash", "-c", "eval $("+Target()+" -p "+profile+" docker-env) && "+Target()+" status -p "+profile)
I think u meant podman-env here

2021-05-03 20:31 UTC, medyagh commented
seems to be also trying to fix https://github.com/kubernetes/minikube/issues/10231

2021-05-05 17:31 UTC, ilya-zuyev commented on test/integration/functional_test.go
> +	c := exec.CommandContext(mctx, "/bin/bash", "-c", "eval $("+Target()+" -p "+profile+" docker-env) && "+Target()+" status -p "+profile)
Fixed. Thanks!

2021-05-05 19:26 UTC, medyagh requested changes

2021-05-05 19:26 UTC, medyagh commented on test/integration/functional_test.go
> +// check functionality of minikube after evaling docker-env
fix comment

2021-05-05 19:26 UTC, medyagh commented on .github/workflows/pr.yml
> +  functional_podman_ubuntu:
add same thing to master.yml

2021-05-05 19:26 UTC, medyagh commented on Makefile
> +
remove unrelated

also please squash the commits, for a cleaner commmit history

2021-05-05 20:32 UTC, ilya-zuyev commented
recreated as https://github.com/kubernetes/minikube/pull/11295

2021-05-05 20:32 UTC, closed without merging