Implement -n/--node option for cp command
kubernetes/minikube pull request #11304
Opened 2021-05-06 05:14 UTC by daehyeok

fixes #11146

2021-05-06 22:22 UTC, ilya-zuyev requested changes
':' can be a part of filepath
```
➜  minikube git:(master) ✗ out/minikube ssh -- sudo mkdir "/tmp/bar:"
➜  minikube git:(master) ✗ out/minikube cp foo /tmp/bar:/foo         
➜  minikube git:(master) ✗ out/minikube ssh -- ls '/tmp/bar:/'      
foo
```

```
➜  minikube git:(copy_node) ✗ out/minikube ssh -- sudo mkdir "/tmp/bar:"
➜  minikube git:(copy_node) ✗ out/minikube cp foo /tmp/bar:/foo    

X Exiting due to GUEST_NODE_RETRIEVE: Node /tmp/bar does not exist.
```
May be it's better to add a new cli key, `--target-node` or something like this

2021-05-06 23:50 UTC, daehyeok commented
@ilya-zuyev  oops. changed to extract node name only destPath is not a absolute path(not start with '/'). 
We only allowed absolute path for remote destination, so file with ':' character will be not a problem.
and if we use another flag for node name, we will need another flag for #11296 in future.

2021-05-07 18:40 UTC, ilya-zuyev approved these changes

2021-05-07 19:15 UTC, ilya-zuyev commented
/ok-to-test

2021-05-14 22:59 UTC, merged