docker driver: relax version constraint
kubernetes/minikube pull request #11309
Opened 2021-05-06 14:04 UTC by AkihiroSuda

When Docker (Moby) was installed from the source code, the version string is typically set to "dev", or "library-import".

Previously, minikube could not start with these versions.

2021-05-06 18:08 UTC, medyagh commented
@AkihiroSuda do u mind sharing the instructions to build docker from source ? 
and how about instead of relaxing the requirement, we detect the docker from source and add an info line to users that you are using Docker from Source and this is not Tested and use it as your own risk ?

2021-05-06 18:26 UTC, afbjorklund commented
Thank you for this fix, we had a similar bug for podman (should have looked twice)

2021-05-06 21:55 UTC, ilya-zuyev reviewed
Thanks for the PR! Could you update the description with examples of output before and after  the change?

2021-05-06 22:28 UTC, ilya-zuyev requested changes
Please add a unit test for `checkDockerVersion`

2021-05-07 09:59 UTC, AkihiroSuda commented
> I admitably I had never seen anyone build docker from source.

I'm a maintainer of Moby (aka dockerd), so I'm always using github.com/moby/moby@master

> do u mind sharing the instructions to build docker from source ?

```bash
git clone https://github.com/docker/docker.git
cd docker
make binary
make install
```

The version string is set to `dev`.

Alternatively, you can also install dockerd with `go build github.com/docker/docker/cmd/dockerd`. In this case, the version is set to `library-import`. Direct execution of `go build` is unrecommended but still valid.


> and how about instead of relaxing the requirement, we detect the docker from source and add an info line to users that you are using Docker from Source and this is not Tested and use it as your own risk ?

Returned to the caller as `{NeedsImprovement: true, Fix: "Install the official release of Docker (Minimum recommended version is 18.09.0, current version is dev)"}`


>  Could you update the description with examples of output before and after the change?

Done

> Please add a unit test for checkDockerVersion

Done

2021-05-07 21:39 UTC, medyagh approved these changes
Thank you @AkihiroSuda for improving the docker version check on minikube

2021-05-07 21:39 UTC, medyagh commented
look forward to see more PRs from you @AkihiroSuda

2021-05-07 21:39 UTC, merged

2021-05-07 21:53 UTC, AkihiroSuda commented
Thanks!