Revert "base-image: Allow using podman as well as docker daemon"
kubernetes/minikube pull request #11356
Opened 2021-05-09 17:44 UTC by medyagh

Reverts kubernetes/minikube#11063

LoadImage test is consistently failing all on GH action tests
  "TestFunctional/parallel/LoadImage" 
Could it be from this PR ?

https://github.com/kubernetes/minikube/pull/11063

2021-05-09 18:17 UTC, afbjorklund requested changes
I don't think it is the kicbase changes that is causing the failures, but something from the other PRs. For instance it could be an issue with the canonical names, or a test framework issue ?

2021-05-10 02:39 UTC, medyagh commented
> I don't think it is the kicbase changes that is causing the failures, but something from the other PRs. For instance it could be an issue with the canonical names, or a test framework issue ?

Revering the pr seems to make all functional green (except containerd)

2021-05-10 04:55 UTC, afbjorklund approved these changes

2021-05-10 04:55 UTC, afbjorklund commented
There was a problem with the daemonBinary not being set in all code paths

2021-05-10 05:07 UTC, merged