Added Mock of Minikube Delete Profiles Test portion.
kubernetes/minikube pull request #11423
Opened 2021-05-16 19:05 UTC by vishjain

fixes #9795

2021-05-21 21:01 UTC, medyagh commented
@vishjain  are u still working on this ?

2021-05-22 01:51 UTC, vishjain commented
> @vishjain are u still working on this ?

Yes, please give me a few days to fix this. Out of town right now.

2021-06-02 18:59 UTC, vishjain commented
@medyagh Please take a look when you get a chance. Thanks.

2021-06-02 19:35 UTC, medyagh requested changes

2021-06-02 19:35 UTC, medyagh commented on cmd/minikube/cmd/delete.go
> +var DeleteHostAndDirectoriesGetter = func(api libmachine.API, cc *config.ClusterConfig, profileName string) error {
this func is not used anywhere in the code, lets make it private, also name Getter doesnt sound right here.

how about
var hostAndDirsDeleter = func ( ...

2021-06-02 19:37 UTC, medyagh requested changes
please see comment

2021-06-03 03:06 UTC, vishjain commented
@medyagh Made changes. Thanks.

2021-06-03 21:45 UTC, medyagh requested changes

2021-06-03 21:45 UTC, medyagh commented on cmd/minikube/cmd/delete_test.go
> +var DeleteHostAndDirectoriesMock = func(api libmachine.API, cc *config.ClusterConfig, profileName string) error {
this needs to be private as well and rename to the same name as the other with "hostAndDirsDeleterMock"

2021-06-05 18:19 UTC, vishjain commented
@medyagh All names should be fixed. Thanks!

2021-06-13 14:00 UTC, vishjain commented
@medyagh Can you please approve this/review this?

2021-06-17 17:02 UTC, medyagh approved these changes
thank you @vishjain

2021-06-17 17:02 UTC, merged