Add "resume" as an alias for "unpause"
kubernetes/minikube pull request #11431
Opened 2021-05-17 15:27 UTC by briandealwis

This PR adds an alias for the "unpause" command for "resume".  I always make a mistaken running `minikube resume` and then realize that it's `unpause`.

An alternative would be to use a `SuggestFor: ["resume"]`.

And yes, I should be using auto-pause.

2021-05-17 15:37 UTC, afbjorklund commented
We sorta left suspend/resume for the VM, but then again it was never implemented either.

And I think it is called "pause" and "resume" in VBoxManage, so there's confusion anyway.

https://www.virtualbox.org/manual/ch08.html#vboxmanage-controlvm

> **VBoxManage controlvm <vm> pause**: Temporarily puts a virtual machine on hold, without permanently changing its state. The VM window is gray, to indicate that the VM is currently paused. This is equivalent to selecting the Pause item in the Machine menu of the GUI.
>
> **VBoxManage controlvm <vm> resume**: Undoes a previous pause command. This is equivalent to selecting the Resume item in the Machine menu of the GUI.

Not sure if the Docker VM has a similar feature ? How to best separate processes/machines.

2021-05-17 16:57 UTC, briandealwis commented
Then maybe the `SuggestFor` is better so as to keep `resume` available.

2021-05-17 18:18 UTC, afbjorklund commented
> Then maybe the `SuggestFor` is better so as to keep `resume` available.

Nah, pause/resume is fine. We can do something else, if we do VM sleep

2021-05-17 18:19 UTC, afbjorklund reviewed
You need to run `make generate-docs`, then it should be good to go ?

2021-05-17 18:48 UTC, medyagh approved these changes

2021-05-17 18:49 UTC, medyagh requested changes
thank you for this PR @briandealwis would u please `make generate-docs`

2021-05-18 01:48 UTC, briandealwis commented
I was just running `generate-docs` and saw that you'd beaten me to the punch @medyagh :-)

2021-05-18 18:42 UTC, medyagh commented
/ok-to-test

2021-05-19 10:36 UTC, briandealwis commented
/retest

2021-05-19 22:04 UTC, medyagh approved these changes
thank you @briandealwis

2021-05-19 22:04 UTC, merged