Add option for vmware network type
kubernetes/minikube pull request #11517
Opened 2021-05-26 19:39 UTC by zarenner

Following https://github.com/machine-drivers/docker-machine-driver-vmware/pull/34, adds support for specifying the VMWare network connection type (e.g. `nat` vs `bridged`)

usage text:
```
      --vm-driver='': DEPRECATED, use `driver` instead.
      --vmware-network-type='nat': Network connection type to use. One of 'nat', 'bridged', 'hostonly', 'custom' (vmware
driver only)
      --wait=[apiserver,system_pods]: comma separated list of Kubernetes components to verify and wait for after
```

Running e.g. `minikube start --driver=vmware --vmware-network-type=hostonly` results in a `.vmx` with `ethernet0.connectionType = "hostonly"`

2021-05-26 19:43 UTC, zarenner commented
Hmm I have signed the CLA... investigating.

2021-05-26 20:04 UTC, medyagh commented
@zarenner do u mind posting an example of this new flag output in the PR description ?
consider adding a section in the webste for this flag and why and how to use it
https://minikube.sigs.k8s.io/docs/drivers/vmware/

2021-05-26 20:47 UTC, zarenner commented
@medyagh Added a screenshot to the description for the example there, and added a docs change. Thanks for the quick feedback!

2021-05-27 19:30 UTC, medyagh approved these changes

2021-05-27 20:12 UTC, medyagh commented
@zarenner please take a look at the unit test

```
make test
```

2021-06-02 00:59 UTC, medyagh commented
/ok-to-test

2021-06-02 19:42 UTC, medyagh requested changes

2021-06-02 19:42 UTC, medyagh commented on cmd/minikube/cmd/start_flags.go
> +	vmwareNetworkType       = "vmware-network-type"
@zarenner sorry for the changing in my opinion, but how about we called this flag "network-type"
and then then specify this is only currently used for for vmwware and then if user specificed a value for this flag for non-vmware drivers, we should Exit with Exit With Usage

```
				exit.Message(reason.Usage, "network-type flag is currently only supported only by the vm-ware driver "
```

2021-11-20 07:36 UTC, closed without merging