Exit out when failed to download kic image and fallback images.
kubernetes/minikube pull request #11589
Opened 2021-06-07 02:20 UTC by vishjain

fixes #8997

2021-06-07 18:54 UTC, ilya-zuyev commented on pkg/minikube/node/cache.go
> +			image.ErrFailedDownloadKICImages = errors.New(infoStr)
Usually, global `Err*` variables are supposed to be read-only, excluding maybe init functions. The idea is to be able to have checks like `if err == image.ErrFailedDownloadKICImages { ... `.  Changing value of `Err*` makes such checks undetermined and hard to debug.

2021-06-07 18:56 UTC, ilya-zuyev reviewed
Could you add PR description attaching minikube logs before and after the changes?

2021-06-07 21:31 UTC, sharifelgamal commented on pkg/minikube/image/types.go
> +// ErrFailedDownloadKICImages is thrown when user
can you finish this comment?

2021-06-09 02:02 UTC, vishjain commented
> Could you add PR description attaching minikube logs before and after the changes?

It's a bit hard to do that

2021-06-11 18:55 UTC, medyagh requested changes

2021-06-11 18:55 UTC, medyagh commented on pkg/minikube/node/cache.go
> +				exit.Message(reason.Usage, "Failed to download KIC base image or any fallback image.")
this is not a "Usage" problem !

2021-06-18 16:49 UTC, medyagh commented
@vishjain still working on this ?

2021-06-18 18:15 UTC, vishjain commented
@medyagh Making changes, Thanks!

2021-06-18 21:11 UTC, closed without merging