Add Tests Around Load Image.
kubernetes/minikube pull request #11588
Opened 2021-06-07 00:16 UTC by vishjain

fixes #10451

2021-06-09 18:32 UTC, medyagh commented on test/integration/functional_test.go
> +	busyboxImage := "busybox:1.33"
lets use a GCR hosted image to avoid the rate limit

2021-06-24 13:22 UTC, tharun208 commented on test/integration/functional_test.go
> +	if !strings.Contains(rr.Output(), fmt.Sprintf("busybox:load-%s", profile)) {
can we do the comparison against the `newImage` argument?

2021-06-24 13:23 UTC, tharun208 commented on test/integration/functional_test.go
> +	// pull busybox
please modify the comments

2021-07-26 20:38 UTC, medyagh requested changes
would u plz update the test comment with with more information ?

both for the new test and also the preivous test
"validateLoadImage"


by reading the doc we should like to learn what these two tests two differently and we why we have two diff tests and not combined into one?

2021-11-07 06:29 UTC, vishjain commented
Closing this and putting a new PR with comments. @medyagh

2021-11-07 06:29 UTC, closed without merging