Add  sub-command and description for configurable field
kubernetes/minikube pull request #11724
Opened 2021-06-21 23:37 UTC by daehyeok

add `minikube config list` subcommand
fixs #11560

```
❯ make && minikube config list
go build  -tags "" -ldflags="-X k8s.io/minikube/pkg/version.version=v1.21.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.21.0 -X k8s.io/minikube/pkg/version.gitCommitID="2c879a1fec38d2b6b587da28b13c994147b85c6f-dirty" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -o out/minikube k8s.io/minikube/cmd/minikube
driver - Used to specify the driver to run Kubernetes in. The list of available drivers depends on operating system.
vm-driver - DEPRECATED, use driver instead.
container-runtime - The container runtime to be used (docker, cri-o, containerd). (default "docker")
feature-gates - A set of key=value pairs that describe feature gates for alpha/experimental features.
v - number for the log level verbosity
cpus - Number of CPUs allocated to Kubernetes.
disk-size - Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g). (default "20000mb")
host-only-cidr - The CIDR to be used for the minikube VM (virtualbox driver only) (default "192.168.99.1/24")
memory - Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g).
log_dir - If non-empty, write log files in this directory
kubernetes-version - The Kubernetes version that the minikube VM will use (ex: v1.2.3, 'stable' for v1.20.7, 'latest' for v1.22.0-alpha.2). Defaults to 'stable'.
iso-url - Locations to fetch the minikube ISO from. (default [https://storage.googleapis.com/minikube/iso/minikube-v1.21.0.iso,https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-v1.21.0.iso,https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.21.0.iso])
WantUpdateNotification - 
WantBetaUpdateNotification - 
ReminderWaitPeriodInHours - 
WantNoneDriverWarning - 
profile - The name of the minikube VM being used. (default "minikube")
bootstrapper - The name of the cluster bootstrapper that will set up the Kubernetes cluster. (default "kubeadm")
insecure-registry - Insecure Docker registries to pass to the Docker daemon.  The default service CIDR range will automatically be added.
hyperv-virtual-switch - The hyperv virtual switch name. Defaults to first found. (hyperv driver only)
disable-driver-mounts - Disables the filesystem mounts provided by the hypervisors
cache - 
EmbedCerts - If true, will embed the certs in kubeconfig.
native-ssh - Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh' command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for SSH'.

❯ minikube config list --output json
[{"Name":"driver","Description":"Used to specify the driver to run Kubernetes in. The list of available drivers depends on operating system."},{"Name":"vm-driver","Description":"DEPRECATED, use driver instead."},{"Name":"container-runtime","Description":"The container runtime to be used (docker, cri-o, containerd). (default \"docker\")"},{"Name":"feature-gates","Description":"A set of key=value pairs that describe feature gates for alpha/experimental features."},{"Name":"v","Description":"number for the log level verbosity"},{"Name":"cpus","Description":"Number of CPUs allocated to Kubernetes."},{"Name":"disk-size","Description":"Disk size allocated to the minikube VM (format: \u003cnumber\u003e[\u003cunit\u003e], where unit = b, k, m or g). (default \"20000mb\")"},{"Name":"host-only-cidr","Description":"The CIDR to be used for the minikube VM (virtualbox driver only) (default \"192.168.99.1/24\")"},{"Name":"memory","Description":"Amount of RAM to allocate to Kubernetes (format: \u003cnumber\u003e[\u003cunit\u003e], where unit = b, k, m or g)."},{"Name":"log_dir","Description":"If non-empty, write log files in this directory"},{"Name":"kubernetes-version","Description":"The Kubernetes version that the minikube VM will use (ex: v1.2.3, 'stable' for v1.20.7, 'latest' for v1.22.0-alpha.2). Defaults to 'stable'."},{"Name":"iso-url","Description":"Locations to fetch the minikube ISO from. (default [https://storage.googleapis.com/minikube/iso/minikube-v1.21.0.iso,https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-v1.21.0.iso,https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.21.0.iso])"},{"Name":"WantUpdateNotification","Description":""},{"Name":"WantBetaUpdateNotification","Description":""},{"Name":"ReminderWaitPeriodInHours","Description":""},{"Name":"WantNoneDriverWarning","Description":""},{"Name":"profile","Description":"The name of the minikube VM being used. (default \"minikube\")"},{"Name":"bootstrapper","Description":"The name of the cluster bootstrapper that will set up the Kubernetes cluster. (default \"kubeadm\")"},{"Name":"insecure-registry","Description":"Insecure Docker registries to pass to the Docker daemon.  The default service CIDR range will automatically be added."},{"Name":"hyperv-virtual-switch","Description":"The hyperv virtual switch name. Defaults to first found. (hyperv driver only)"},{"Name":"disable-driver-mounts","Description":"Disables the filesystem mounts provided by the hypervisors"},{"Name":"cache","Description":""},{"Name":"EmbedCerts","Description":"If true, will embed the certs in kubeconfig."},{"Name":"native-ssh","Description":"Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh' command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for SSH'."}]%                                          
```

2021-06-21 23:42 UTC, daehyeok commented
Description mostly copied from other command. but i couldn't find proper text for below fields. anyone help to fill missing text?
```
WantUpdateNotification 
WantBetaUpdateNotification 
ReminderWaitPeriodInHours 
WantNoneDriverWarning 
cache
```

Also i tired to print list with  "github.com/olekukonko/tablewriter" package which already used for profile list command. but it looks not well handling long text... Do we have other formatter used in minikube or other suggestion?
```
|----------------------------|------------------------------------------------------------------------------------------------------|
|            NAME            |                                             DESCRIPTION                                              |
|----------------------------|------------------------------------------------------------------------------------------------------|
| driver                     | Used to specify the driver to                                                                        |
|                            | run Kubernetes in. The list of                                                                       |
|                            | available drivers depends on                                                                         |
|                            | operating system.                                                                                    |
| vm-driver                  | DEPRECATED, use driver                                                                               |
|                            | instead.                                                                                             |
| container-runtime          | The container runtime to                                                                             |
|                            | be used (docker, cri-o,                                                                              |
|                            | containerd). (default                                                                                |
|                            | "docker")                                                                                            |
| feature-gates              | A set of key=value pairs that                                                                        |
|                            | describe feature gates for                                                                           |
|                            | alpha/experimental features.                                                                         |
| v                          | number for the log level                                                                             |
|                            | verbosity                                                                                            |
| cpus                       | Number of CPUs allocated to                                                                          |
|                            | Kubernetes.                                                                                          |
| disk-size                  | Disk size allocated to                                                                               |
|                            | the minikube VM (format:                                                                             |
|                            | <number>[<unit>], where unit                                                                         |
|                            | = b, k, m or g). (default                                                                            |
|                            | "20000mb")                                                                                           |
| host-only-cidr             | The CIDR to be used for                                                                              |
|                            | the minikube VM (virtualbox                                                                          |
|                            | driver only) (default                                                                                |
|                            | "192.168.99.1/24")                                                                                   |
| memory                     | Amount of RAM to allocate                                                                            |
|                            | to Kubernetes (format:                                                                               |
|                            | <number>[<unit>], where unit =                                                                       |
|                            | b, k, m or g).                                                                                       |
| log_dir                    | If non-empty, write log files                                                                        |
|                            | in this directory                                                                                    |
| kubernetes-version         | The Kubernetes version that                                                                          |
|                            | the minikube VM will use (ex:                                                                        |
|                            | v1.2.3, 'stable' for v1.20.7,                                                                        |
|                            | 'latest' for v1.22.0-alpha.2).                                                                       |
|                            | Defaults to 'stable'.                                                                                |
| iso-url                    | Locations to fetch the minikube ISO from. (default                                                   |
|                            | [https://storage.googleapis.com/minikube/iso/minikube-v1.21.0.iso,                                   |
|                            | https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-v1.21.0.iso,               |
|                            | https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.21.0.iso])                  |
| WantUpdateNotification     |                                                                                                      |
| WantBetaUpdateNotification |                                                                                                      |
| ReminderWaitPeriodInHours  |                                                                                                      |
| WantNoneDriverWarning      |                                                                                                      |
| profile                    |                                                                                                      |
| bootstrapper               | The name of the cluster                                                                              |
|                            | bootstrapper that will set                                                                           |
|                            | up the Kubernetes cluster.                                                                           |
|                            | (default "kubeadm")                                                                                  |
| insecure-registry          | Insecure Docker registries to                                                                        |
|                            | pass to the Docker daemon.                                                                           |
|                            | The default service CIDR range                                                                       |
|              [...]

2021-06-22 00:04 UTC, spowelljr commented
@daehyeok 
WantUpdateNotification  - If true, will notify on start if there's a newer stable version of minikube available.
WantBetaUpdateNotification  - If true, will notify on start if there's a newer beta version of minikube available.
ReminderWaitPeriodInHours - The number of hours to wait before reminding there's a newer version of minikube again.
WantNoneDriverWarning - If false, will stop recommending to use Docker driver instead of none driver.

2021-06-22 02:29 UTC, medyagh requested changes

2021-06-22 02:29 UTC, medyagh commented on cmd/minikube/cmd/config/config.go
> +		description: "The name of the minikube VM being used. (default \"minikube\")",
the name of the minikube cluster (profile) default "minikube"

2021-06-22 02:29 UTC, medyagh commented on cmd/minikube/cmd/config/list.go
> +Copyright 2016 The Kubernetes Authors All rights reserved.
2021

2021-06-22 02:29 UTC, medyagh commented on cmd/minikube/cmd/config/config.go
> +		description: "Number of CPUs allocated to Kubernetes.",
Number of CPUs allocated to each minikube node

2021-06-22 15:47 UTC, medyagh commented on cmd/minikube/cmd/config/config.go
> +		description: "Locations to fetch the minikube ISO from. (default [https://storage.googleapis.com/minikube/iso/minikube-v1.21.0.iso,https://github.com/kubernetes/minikube/releases/download/v1.21.0/m
this needs to be auto-generated we should not need to update this help every release

2021-06-22 15:48 UTC, medyagh requested changes

2021-06-22 15:48 UTC, medyagh commented on cmd/minikube/cmd/config/config.go
> +		description: "Insecure Docker registries to pass to the Docker daemon.  The default service CIDR range will automatically be added.",
Insecure image registries to pass to the container runtime engine (docker, containered, cri-o). The default service CIDR range will automatically be added.
...

2021-06-22 21:45 UTC, daehyeok commented
Fixed all description mentioned by @medyagh and @spowelljr 
```
❯ minikube config list
driver - Used to specify the driver to run Kubernetes in. The list of available drivers depends on operating system.
vm-driver - DEPRECATED, use driver instead.
container-runtime - The container runtime to be used (docker, cri-o, containerd). (default "docker")
feature-gates - A set of key=value pairs that describe feature gates for alpha/experimental features.
v - number for the log level verbosity
cpus - Number of CPUs allocated to each minikube node
disk-size - Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g). (default "20000mb")
host-only-cidr - The CIDR to be used for the minikube VM (virtualbox driver only) (default "192.168.99.1/24")
memory - Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g).
log_dir - If non-empty, write log files in this directory
kubernetes-version - The Kubernetes version that the minikube VM will use (ex: v1.2.3, 'stable' for v1.20.7, 'latest' for v1.22.0-alpha.2). Defaults to 'stable'.
iso-url - Locations to fetch the minikube ISO from. (default [https://storage.googleapis.com/minikube/iso/minikube-v1.21.0.iso https://github.com/kubernetes/minikube/releases/download/v1.21.0/minikube-v1.21.0.iso https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.21.0.iso])
WantUpdateNotification - If true, will notify on start if there's a newer stable version of minikube available.
WantBetaUpdateNotification - If true, will notify on start if there's a newer beta version of minikube available.
ReminderWaitPeriodInHours - The number of hours to wait before reminding there's a newer version of minikube again.
WantNoneDriverWarning - If false, will stop recommending to use Docker driver instead of none driver.
profile - The name of the minikube cluster (profile) default "minikube"
bootstrapper - The name of the cluster bootstrapper that will set up the Kubernetes cluster. (default "kubeadm")
insecure-registry - Insecure image registries to pass to the container runtime engine (docker, containerd, cri-o). The default service CIDR range will automatically be added.
hyperv-virtual-switch - The hyperv virtual switch name. Defaults to first found. (hyperv driver only)
disable-driver-mounts - Disables the filesystem mounts provided by the hypervisors
cache - 
EmbedCerts - If true, will embed the certs in kubeconfig.
native-ssh - Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh' command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for SSH'.
```

2021-10-05 19:02 UTC, spowelljr commented on cmd/minikube/cmd/config/list.go
> +	jsonString, _ := json.Marshal(body)
We're just ignoring the error here, but if there is an error we should exit with a non-zero exit code so any automation knows it failed.

2021-11-03 18:54 UTC, spowelljr requested changes

2021-11-03 18:54 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +		description: "The CIDR to be used for the minikube VM (virtualbox driver only) (default \"192.168.99.1/24\")",
This is now `192.168.59.1/24`

2021-11-03 18:54 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +		description: "The Kubernetes version that the minikube VM will use (ex: v1.2.3, 'stable' for v1.20.7, 'latest' for v1.22.0-alpha.2). Defaults to 'stable'.",
The stable and latest version are constantly changing, we should remove these versions as they're going to get outdated quickly.

2021-11-03 18:54 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +		description: "The name of the minikube cluster (profile) default \"minikube\"",
Would be nice to keep the consistency of having: `<description>. (default <default>)`

2021-11-03 18:54 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +		description: "The hyperv virtual switch name. Defaults to first found. (hyperv driver only)",
`Hyper-V`

2021-11-03 18:54 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +		description: "number for the log level verbosity",
Should start with a capital to keep consistency.

2021-11-03 18:55 UTC, spowelljr commented on cmd/minikube/cmd/config/config.go
> +Copyright 2021 The Kubernetes Authors All rights reserved.
This one should stay as 2016, it's `cmd/minikube/cmd/config/list.go` that should updated to 2021 since that's a brand new file.

2021-11-22 21:45 UTC, medyagh commented
@daehyeok plz take a look at the requested changes

2021-11-22 22:46 UTC, daehyeok commented
update and rebased

2022-06-04 06:39 UTC, closed without merging