Clean up ssh tunnels during exit.
kubernetes/minikube pull request #11745
Opened 2021-06-22 22:34 UTC by vishjain

fixes #10752

2021-06-22 23:55 UTC, medyagh requested changes
could u plz post before/after this PR in the PR Description ?

2021-06-23 00:14 UTC, vishjain commented
> could u plz post before/after this PR in the PR Description ?

Done.

2021-07-05 23:36 UTC, vishjain commented
@medyagh Can you take a glance at this, Thanks!

2021-07-14 18:25 UTC, ilya-zuyev commented on pkg/minikube/tunnel/kic/ssh_conn.go
> +	if c.activeConn {
can we set `c.activeConn` to `false` here? If somehow we call `c.stop()` twice, we'll try to kill already stopped process.

2021-07-21 18:30 UTC, sharifelgamal commented
@vishjain This looks good, could you just address the one comment above, then we can go ahead and run the full test suite.

2021-07-25 21:46 UTC, vishjain commented
> @vishjain This looks good, could you just address the one comment above, then we can go ahead and run the full test suite.

I've made the necessary changes here.

2021-08-04 18:13 UTC, spowelljr commented
/ok-to-test

2021-08-13 20:15 UTC, merged