Print profile driver, container runtime, and Kubernetes version on load
kubernetes/minikube pull request #12228
Opened 2021-08-10 20:44 UTC by andriyDev

fixes #11977.

Whenever a profile is loaded, some of its settings are printed out. Whenever profiles are listed, this also logs.

Example: `minikube -p mk2 addons enable dashboard --alsologtostderr`
```
... Stuff ...
I0810 13:39:50.012993  195672 config.go:177] Profile "mk2": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.21.3
... Stuff ...
```

2021-08-10 20:44 UTC, andriyDev commented
/ok-to-test

2021-08-10 21:51 UTC, medyagh requested changes

2021-08-10 21:51 UTC, medyagh commented on pkg/minikube/config/config.go
> +		klog.Infof("Profile \"%s\": Driver=%s, ContainerRuntime=%s, KubernetesVersion=%s",
lets add more context here,

Loaded Profile config

2021-08-10 21:53 UTC, andriyDev commented on pkg/minikube/config/config.go
> +		klog.Infof("Profile \"%s\": Driver=%s, ContainerRuntime=%s, KubernetesVersion=%s",
Done.

2021-08-12 23:42 UTC, medyagh approved these changes

2021-08-12 23:42 UTC, merged