Use newer dashboard, to support ingress extensions
kubernetes/minikube pull request #12475
Opened 2021-09-14 21:45 UTC by leifcr

This should solve #12402 and issues where ingresses will not show properly in the dashboard.
This error shows on kubernetes 1.22

It bumps the dashboard and metrics to newest versions

2021-09-15 19:23 UTC, medyagh requested changes
@leifcr please fix the unit test and also the Preload Version needs to be bumped after this PR

2021-09-16 18:07 UTC, sharifelgamal commented
/ok-to-test

2021-09-16 20:24 UTC, medyagh approved these changes

2021-09-16 20:31 UTC, merged

2021-09-16 21:24 UTC, leifcr commented
@sharifelgamal and @medyagh Thanks for fixing unit tests and getting this merged. I'll dig further into the code, so I can do that the next time.