Improved the output in minikube github action
kubernetes/minikube pull request #13264
Opened 2021-12-30 05:18 UTC by NikhilSharmaWe

Fixes #13233

2021-12-30 18:40 UTC, NikhilSharmaWe commented on pkg/minikube/download/download.go
> +	if out.IsTerminal(os.Stdout) && !(detect.GithubActionRunner()) {
@spowelljr added the condition for using progress bar when terminal is not in Github Actions.

2021-12-30 19:27 UTC, spowelljr requested changes

2021-12-30 19:27 UTC, spowelljr commented on pkg/minikube/detect/detect.go
> +func GithubActionRunner() bool {
This func should be removed from the test file you copied it from and the tests that reference it should be updated to use this one.

2022-01-06 13:50 UTC, NikhilSharmaWe commented
@spowelljr Could you please review the changes.

2022-01-06 17:52 UTC, spowelljr requested changes

2022-01-06 17:52 UTC, spowelljr commented on pkg/minikube/download/download.go
> +	if out.IsTerminal(os.Stdout) && !(detect.GithubActionRunner()) {
```suggestion
	if out.IsTerminal(os.Stdout) && !detect.GithubActionRunner() {
```
The logic is fine, but you don't have to have `()` around the func, so lets remove those to stay consistent with the rest of the code base and after that looks good to merge to me!

2022-01-06 18:08 UTC, spowelljr approved these changes
Looks good to me, thanks the PR!

2022-01-06 18:12 UTC, merged