German Translations
kubernetes/minikube pull request #13270
Opened 2021-12-31 16:09 UTC by jklippel

Added german translations to translations file.

2022-01-04 21:44 UTC, spowelljr commented
@jklippel 
```
--- FAIL: TestTranslationFilesValid (0.05s)
    --- FAIL: TestTranslationFilesValid/de.json (0.01s)
        translate_test.go:151: line "containers paused status: {{.paused}}": "Container in pausiert status: {{.pause}}" has mismatching variables
            original string variables: [{{.paused}}] do not match translated variables: [{{.pause}}]
        translate_test.go:151: line "{{.driver_name}} has only {{.container_limit}}MB memory but you specified {{.specified_memory}}MB": "{{.driver}} hat nur {{.container_limit}}MB Speicher aber spezifiziert wurden {{.specified_memory}}MB" has mismatching variables
            original string variables: [{{.container_limit}} {{.driver_name}} {{.specified_memory}}] do not match translated variables: [{{.container_limit}} {{.driver}} {{.specified_memory}}]
        translate_test.go:143: line "You have chosen to disable the CNI but the \\\"{{.name}}\\\" container runtime requires CNI": "Sie haben den CNI Treiber deaktiviert, aber die \\\"{{.name}\\\" Container Laufzeitumgebung benötigt ein CNI" has mismatching number of variables
            original string variables: [{{.name}}]; translated variables: []
        translate_test.go:143: line "Verifying {{.addon_name}} addon...": "Verifiziere {.addon_name}} Addon..." has mismatching number of variables
            original string variables: [{{.addon_name}}]; translated variables: []
        translate_test.go:151: line "Requested memory allocation {{.requested}}MiB is less than the usable minimum of {{.minimum_memory}}MB": "Die angeforderte Speicherzuweisung {{.request}}MB ist weniger als das verwendbare Minimum {{.minimum_memory}}MB" has mismatching variables
            original string variables: [{{.minimum_memory}} {{.requested}}] do not match translated variables: [{{.minimum_memory}} {{.request}}]
        translate_test.go:143: line "dashboard service is not running: {{.error}}": "Dashboard Service läuft nicht" has mismatching number of variables
            original string variables: [{{.error}}]; translated variables: []
        translate_test.go:151: line "Requested memory allocation ({{.requested}}MB) is less than the recommended minimum {{.recommend}}MB. Deployments may fail.": "Die angeforderte Speicherzuweisung {{.requested_size}} liegt unter dem zulässigen Mindestwert von {{.minimum_size}}MB. Deployments könnten fehlschlagen." has mismatching variables
            original string variables: [{{.recommend}} {{.requested}}] do not match translated variables: [{{.minimum_size}} {{.requested_size}}]
```

2022-01-04 22:28 UTC, jklippel commented
@spowelljr Fixed

2022-01-06 18:07 UTC, spowelljr requested changes

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"To set your Google Cloud project,  run:\n\n\t\tgcloud config set project \u003cproject name\u003e\n\nor set the GOOGLE_CLOUD_PROJECT environment variable.": "Um das Google Cloud project zu setzten,
```suggestion
	"To set your Google Cloud project,  run:\n\n\t\tgcloud config set project \u003cproject name\u003e\n\nor set the GOOGLE_CLOUD_PROJECT environment variable.": "Um das Google Cloud project zu setzten,  starte:\n\n\t\tgcloud config set project \u003cproject name\u003e\n\noder setze die Umgebungsvariabel GOOGLE_CLOUD_PROJECT.",
```
For conformity we should keep `<>` as unicode.

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"==\u003e Last Start \u003c==": "==> Letzter Start <==",
```suggestion
	"==\u003e Last Start \u003c==": "==\u003e Letzter Start \u003c==",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Configure an external network switch following the official documentation, then add `--hyperv-virtual-switch=\u003cswitch-name\u003e` to `minikube start`": "Konfigurieren Sie einen externen Netzwer
```suggestion
	"Configure an external network switch following the official documentation, then add `--hyperv-virtual-switch=\u003cswitch-name\u003e` to `minikube start`": "Konfigurieren Sie einen externen Netzwerk-Switch mit Hilfe der offiziellen Dokumentation, dann fügen Sie `--hyperv-virtual-switch=\u003cswitch-name\u003e` zum Start-Befehl `minikube start` hinzu",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Disk size allocated to the minikube VM (format: \u003cnumber\u003e[\u003cunit\u003e], where unit = b, k, m or g).": "Größe des der minikube-VM zugewiesenen Festplatte (Format: <Nummer> [<Einheit>],
```suggestion
	"Disk size allocated to the minikube VM (format: \u003cnumber\u003e[\u003cunit\u003e], where unit = b, k, m or g).": "Größe des der minikube-VM zugewiesenen Festplatte (Format: \u003cNummer\u003e [\u003cEinheit\u003e], wobei Einheit = b, k, m oder g).",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Basic Commands:": "Grundlegende Befehle",
```suggestion
	"Basic Commands:": "Grundlegende Befehle:",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Deleting container \"{{.name}}\" ...": "Lösche Container \"{{.name}}\"",
```suggestion
	"Deleting container \"{{.name}}\" ...": "Lösche Container \"{{.name}}\" ...",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Duration until minikube certificate expiration, defaults to three years (26280h).": "Dauer bis das Minikube-Zertifikat abläuft, Default ist drei Jahre (26280 Stunden)",
```suggestion
	"Duration until minikube certificate expiration, defaults to three years (26280h).": "Dauer bis das Minikube-Zertifikat abläuft, Default ist drei Jahre (26280 Stunden).",
```

2022-01-06 18:07 UTC, spowelljr commented on translations/de.json
> +	"Booting up control plane ...": "Starte Control-Plane",
```suggestion
	"Booting up control plane ...": "Starte Control-Plane ...",
```

2022-01-06 18:37 UTC, jklippel commented
@spowelljr Thank you for your review. I applied the requested changes (IDE autocorrecting unicode away :/). I had to do the changes manually, I hope I did not miss anything. For some strange reason github showed all your comments as outdated and I could not collect your suggestions into a batch to commit.

2022-01-06 18:52 UTC, spowelljr requested changes

2022-01-06 18:52 UTC, spowelljr commented on translations/de.json
> +	"Failed to set NO_PROXY Env. Please use `export NO_PROXY=$NO_PROXY,{{.ip}}": "NO_PROXY Env konnte nicht festgelegt werden. Benutzen Sie `export NO_PROXY=$NO_PROXY, {{.ip}}",
```suggestion
	"Failed to set NO_PROXY Env. Please use `export NO_PROXY=$NO_PROXY,{{.ip}}": "NO_PROXY Env konnte nicht festgelegt werden. Benutzen Sie `export NO_PROXY=$NO_PROXY,{{.ip}}",
```
Need no space after the comma as well

2022-01-06 18:52 UTC, spowelljr commented on translations/de.json
> +	"Failed to set NO_PROXY Env. Please use `export NO_PROXY=$NO_PROXY,{{.ip}}`.": "NO_PROXY Env konnte nicht festgelegt werden. Benutzen Sie `export NO_PROXY=$NO_PROXY, {{.ip}}`.",
```suggestion
	"Failed to set NO_PROXY Env. Please use `export NO_PROXY=$NO_PROXY,{{.ip}}`.": "NO_PROXY Env konnte nicht festgelegt werden. Benutzen Sie `export NO_PROXY=$NO_PROXY,{{.ip}}`.",
```

2022-01-06 18:52 UTC, spowelljr commented on translations/de.json
> +	"Pausing node {{.name}} ... ": "Pausiere Node {{.name}}",
```suggestion
	"Pausing node {{.name}} ... ": "Pausiere Node {{.name}} ...",
```

2022-01-06 18:54 UTC, spowelljr commented
@jklippel thanks for taking your time to do the translations, much appreciated! I see that, I'm not sure why that's happening. I just added three more comments and after that it'll be good to merge!

2022-01-06 19:02 UTC, jklippel commented
@spowelljr Thanks again. I added the additional proposed changes as well.

2022-01-06 20:06 UTC, spowelljr approved these changes
Looks good, thank you very much!

2022-01-06 20:06 UTC, merged