fix external cri-docker socket name
kubernetes/minikube pull request #13488
Opened 2022-01-25 22:34 UTC by sharifelgamal

2022-01-25 23:24 UTC, sharifelgamal commented
/ok-to-test

2022-01-26 06:55 UTC, afbjorklund requested changes
The location of the cri-dockerd socket was _changed_, in the cri-dockerd 0.2.0 release.

Now the systemd unit is called "cri-docker.socket", but the file is "cri-dockerd.sock".

2022-01-26 06:55 UTC, afbjorklund commented
/hold

2022-01-26 06:56 UTC, afbjorklund commented
Use this PR instead:

* https://github.com/kubernetes/minikube/pull/13302

2022-01-26 17:28 UTC, sharifelgamal commented
ok, I'll close this and we'll upgrade the version of cri-dockerd instead.

2022-01-26 17:28 UTC, closed without merging

2022-01-26 17:58 UTC, afbjorklund commented
Hopefully they don't change their mind again, so this should be it

2022-01-26 17:59 UTC, afbjorklund commented
* https://github.com/Mirantis/cri-dockerd/pull/31