Adding few new features
kubernetes/minikube pull request #13513
Opened 2022-01-29 17:41 UTC by MdSahil-oss

<h3>What type of PR is this ?</h3>
Add New Features.

<h3>What type of PR is this ?</h3>
fixes #13432 .

2022-01-29 17:44 UTC, MdSahil-oss commented
@afbjorklund , Is this good or i need to improve it more.

2022-01-30 16:08 UTC, afbjorklund commented
@MdSahil-oss : please rebase and squash (to remove the merge commits), and improve the commit message...

You cannot hardcode the container runtime, it has to come from the actual configuration (like _with_ Kubernetes)

2022-01-30 16:08 UTC, afbjorklund requested changes

2022-01-30 16:08 UTC, afbjorklund commented on pkg/minikube/node/start.go
> +		out.Step(style.Docker, "Preparing Docker 20.10.12 ...")
This needs to be dynamic, and use the same code as when running _with_ Kubernetes

2022-02-01 11:19 UTC, MdSahil-oss commented
@afbjorklund I made changes as per your suggestion

2022-02-08 00:21 UTC, medyagh reviewed
can you plz choose a more descriptive PR title and also paste the output of the minikube Before and After this PR in both normal cases and without kubernets ?

2022-02-23 19:38 UTC, spowelljr commented
@MdSahil-oss could you post the output in the PR description like @medyagh mentioned.

Just run minikube on master branch and copy and paste the output then do the same with this branch, something like:
**Before:**
```
😄  minikube v1.25.1 on Ubuntu 20.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, ssh
👍  Starting minikube without Kubernetes minikube in cluster minikube
...
```

**After:**
```
😄  minikube v1.25.1 on Ubuntu 20.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, ssh
👍  Starting minikube without Kubernetes minikube in cluster minikube
...
```
That way we can easily see the UI changes without having to run it, thanks!

2022-03-07 11:21 UTC, MdSahil-oss commented
@spowelljr sure, I would have done it but i'm getting an error on my ubuntu machine related to lint while running minikube.

2022-05-20 12:41 UTC, MdSahil-oss commented
@klaases I'm still getting error on my ubuntu machine related to lint while running minikube.

2022-09-30 11:27 UTC, closed without merging