Add sanity check to disk space check
kubernetes/minikube pull request #13630
Opened 2022-02-17 20:56 UTC by F1ko

Fixes https://github.com/kubernetes/minikube/issues/12761

2022-02-17 21:03 UTC, F1ko commented
This PR is identical to PR https://github.com/kubernetes/minikube/pull/12814 which acted out for some reason.

@spowelljr labeld the original PR with `/ok-to-test`.

Would be nice to pick up where we left off.

2022-02-17 21:16 UTC, F1ko commented
Looking through the git history I observed that workflow failures seem to be the case quite often, even for already merged commits. Does anyone mind explaining to me how to interpret that correctly? Are these certain "know-issues" and expected to fail? In that case, how would I know whether this is due to my changes or because it indeed is a known issue?

2022-02-17 21:21 UTC, sharifelgamal commented
We do unfortunately have some known test failures, and other tests that are simply flaky, that fail for reasons unrelated to your PR. Once all the tests have run, we have a bot that will comment the flake rate of all the failed tests. If there are tons of 0% tests, then it's a safe bet that your PR broke something. Otherwise, maintainers just use their best judgement when merging PRs.

2022-03-14 06:13 UTC, F1ko commented
hi @spowelljr 

are the flake rates high enough now or should I look into other issues as well?
any advice on debugging hyper-v windows without a native windows machine?

2022-03-14 17:50 UTC, spowelljr requested changes
Just a small thing and then it's good to merge

2022-03-14 17:50 UTC, spowelljr commented on pkg/minikube/machine/start_test.go
> +				t.Errorf("DiskUsed() error = %v, wantErr %v", err, tt.wantErr)
If you don't want execution to continue you can do `t.Fatalf` instead and then you don't have to add the return yourself.

2022-03-14 17:50 UTC, spowelljr commented on pkg/minikube/machine/start_test.go
> +				t.Errorf("DiskAvailable() error = %v, wantErr %v", err, tt.wantErr)
Same as above

2022-03-14 19:45 UTC, F1ko commented
@spowelljr thanks, fixed

2022-03-14 22:32 UTC, spowelljr approved these changes

2022-03-15 01:19 UTC, merged