Upgrade buildkit from 0.9.0 to 0.10.0
kubernetes/minikube pull request #13791
Opened 2022-03-15 19:22 UTC by afbjorklund

2022-03-16 21:27 UTC, klaases approved these changes
LGTM - thanks @afbjorklund!

2022-03-23 22:38 UTC, spowelljr commented
ok-to-build-image

2022-03-23 22:38 UTC, spowelljr commented
ok-to-build-iso

2022-03-24 16:12 UTC, spowelljr commented
ok-to-build-iso

2022-03-24 19:04 UTC, spowelljr commented
/ok-to-test

2022-03-24 19:05 UTC, spowelljr commented
ok-to-build-image

2022-03-30 20:29 UTC, spowelljr commented
ok-to-build-iso

2022-03-31 02:44 UTC, spowelljr commented
@afbjorklund This seems to break `image build` on Docker Linux containerd

2022-04-01 05:40 UTC, afbjorklund commented
> @afbjorklund This seems to break `image build` on Docker Linux containerd

Indeed, looks like it failed to start ?

`error: failed to get status: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory"`

2022-04-01 05:55 UTC, afbjorklund commented
```
● buildkit.socket
     Loaded: bad-setting (Reason: Unit buildkit.socket has a bad unit file setting.)
     Active: inactive (dead)
   Triggers: ● buildkit.service

```

2022-04-01 06:00 UTC, afbjorklund commented
ok-to-build-image

2022-04-01 16:05 UTC, afbjorklund commented
ok-to-build-image

2022-04-02 08:15 UTC, afbjorklund commented
ok-to-build-image

2022-04-09 15:33 UTC, afbjorklund commented
ok-to-build-image

Was failing due to cri-o package <sigh>

2022-04-09 15:34 UTC, afbjorklund commented
ok-to-build-iso

2022-04-10 07:34 UTC, afbjorklund commented
ok-to-build-image

was failing due to containerd checksum

2022-04-10 07:34 UTC, afbjorklund commented
ok-to-build-iso

2022-04-10 07:46 UTC, afbjorklund commented
There is a 0.10.1 out, but lets wait for the new build of this one.

2022-04-11 20:56 UTC, spowelljr commented
ok-to-build-image

2022-04-11 20:57 UTC, spowelljr commented
ok-to-build-iso

2022-04-12 17:41 UTC, spowelljr commented
ok-to-build-iso

2022-04-14 16:39 UTC, spowelljr commented
@afbjorklund This one seems to be good if you want to bump to `0.10.1`

2022-05-03 17:40 UTC, spowelljr commented
ok-to-build-iso

2022-05-04 21:03 UTC, spowelljr commented on deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
> +sha256 ed9d3942ca3f1cbc4906577a2422e5084416dd2739f3d85b800a129d61557630  buildkit-v0.10.0.linux-amd64.tar.gz
```suggestion
test123
```

2022-05-04 21:06 UTC, spowelljr requested changes

2022-05-04 21:06 UTC, spowelljr commented on deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
> +sha256 ed9d3942ca3f1cbc4906577a2422e5084416dd2739f3d85b800a129d61557630  buildkit-v0.10.0.linux-amd64.tar.gz
```suggestion
sha256 ce330ab4e1d6543fec0e62d724d361dddfcfb6dcd9ef992e0e6a498a1865f51f  buildkit-v0.10.2.linux-amd64.tar.gz
```

2022-05-04 21:06 UTC, spowelljr commented on deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
> +BUILDKIT_BIN_VERSION = v0.10.0
```suggestion
BUILDKIT_BIN_VERSION = v0.10.2
```

2022-05-04 21:06 UTC, spowelljr commented on deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
> +BUILDKIT_BIN_COMMIT = 068cf686a7e5c3254244d0acc54636f4f393611e
```suggestion
BUILDKIT_BIN_COMMIT = 9d2c9b25145ff021f91374408be710938297ba24
```

2022-05-04 21:06 UTC, spowelljr commented on deploy/kicbase/Dockerfile
> +ARG BUILDKIT_VERSION="v0.10.0"
```suggestion
ARG BUILDKIT_VERSION="v0.10.2"
```

2022-05-04 21:07 UTC, spowelljr commented
ok-to-build-iso

2022-05-04 21:07 UTC, spowelljr commented
ok-to-build-image

2022-05-04 23:02 UTC, spowelljr commented
kic failed due to crio `File has unexpected size (20111120 != 20114960)` error, will retry tomorrow

2022-05-05 16:54 UTC, spowelljr commented
ok-to-build-image

2022-05-05 17:37 UTC, spowelljr commented
Error is still occuring

2022-05-06 17:52 UTC, spowelljr commented
ok-to-build-image

2022-05-09 18:11 UTC, spowelljr commented
/retest-this-please

2022-05-10 20:35 UTC, spowelljr commented
ok-to-build-image

2022-05-11 22:50 UTC, spowelljr commented
/ok-to-build-image

2022-05-11 22:50 UTC, spowelljr commented
ok-to-build-image

2022-05-11 22:51 UTC, spowelljr commented
ok-to-build-iso

2022-05-12 16:44 UTC, spowelljr approved these changes

2022-05-12 16:44 UTC, merged