Make closing CLI-terminal more visible
kubernetes/minikube pull request #14289
Opened 2022-06-07 12:51 UTC by layakdev

2022-06-07 13:19 UTC, medyagh requested changes

2022-06-07 13:19 UTC, medyagh commented on site/content/en/docs/start/_index.md
> +    _If you used a CLI to perform the installation, you will need to close that CLI and open a new one before proceeding._</span>
Thank you for this PR, 
it seems like after changing this PR the "_" no longer makes the font "italic"

we could do replace "_" with "*" 

"If you used a CLI to perform the installation, you will need to close that CLI and open a new one before proceeding."

2022-06-07 13:20 UTC, medyagh commented on site/content/en/docs/start/_index.md
> +    _If you used a CLI to perform the installation, you will need to close that CLI and open a new one before proceeding._</span>
also how about we change the wording to
"If you used a terminal (like powershell) for the installation, you will need to close the terminal and reopen it before running minikube."

2022-06-21 15:04 UTC, layakdev commented
@medyagh 
Hi, ready to review =)
Thanks

2022-06-21 15:04 UTC, medyagh approved these changes
Looks good to me ! thank you for this PR, look forward to see more contributions from you !

2022-06-21 15:04 UTC, merged