Don't allow --control-plane=true for node add #14300
kubernetes/minikube pull request #14323
Opened 2022-06-11 10:02 UTC by lakshkeswani

output message for if the user tries to add a control panel to the node and avoid the crash
control panel feature for node add is not supported

2022-06-11 10:38 UTC, lakshkeswani commented
/assign @medyagh

2022-06-13 18:33 UTC, spowelljr requested changes

2022-06-13 18:33 UTC, spowelljr commented on cmd/minikube/cmd/node_add.go
> +			out.Step(style.Unsupported, "control-plane feature is not supported {{.name}} to {{.cluster}}!", out.V{"name": name, "cluster": cc.Name})
```suggestion
			out.Step(style.Unsupported, "Adding a control-plane node is not yet supported, setting control-plane flag to false")
```

Could you also move this `if` statement above the `out.Step(style.Happy, "Adding node` line.

2022-06-13 19:51 UTC, spowelljr commented
Can you also edit your PR description to include `Fixes https://github.com/kubernetes/minikube/issues/14300`, this will auto close the issue when this PR is merged, thanks

2022-06-14 00:06 UTC, spowelljr requested changes

2022-06-14 00:06 UTC, spowelljr commented on cmd/minikube/cmd/node_add.go
> +		if !cp {
This should be if `cp` is true, right?

2022-06-14 00:18 UTC, lakshkeswani commented on cmd/minikube/cmd/node_add.go
> +		if !cp {
yes

2022-06-14 04:15 UTC, knrt10 commented
@lakshkeswani Instead of creating a new commit [check for control panel](https://github.com/kubernetes/minikube/pull/14323/commits/b7c75c996735cd8375a4060fb91c23a224c0ed78). I would suggest you can edit your first commit with the change.

You can do the following steps.

- git rebase -i "commitID^" or git rebase -i HEAD~4
- On your editor change the commit you want to change i.e [Don't allow --control-plane=true for node add](https://github.com/kubernetes/minikube/pull/14323/commits/daf310b8fd5c2dbb346c40634491a4be8ef49308) from `pick` to `edit`. Save and exit editor
- Make your change to code.
- git add Filename
- git rebase --continue (this will generate the old commit)
- Save the commit
- git push origin lakshkeswani:master --force-with-lease

2022-06-14 17:33 UTC, spowelljr approved these changes
Thanks for the change, looks great!

2022-06-14 17:35 UTC, spowelljr commented
Actually one more thing, on line 97 could you add to the flag description that `This flag is currently unsupported.` And then run `make generate-docs` to update the site documentation, thanks!

2022-06-16 11:36 UTC, lakshkeswani commented
Generated the docs and squashed the commits, I hope this will get merged.
Thanks

2022-06-21 18:02 UTC, merged