automate publishing to winget
kubernetes/minikube pull request #14321
Opened 2022-06-11 04:47 UTC by vedantmgoyal2009

This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @kubernetes.

Fixes https://github.com/kubernetes/minikube/issues/14190

Edit:
Sorry for spaming the PR, but the bot is really good. It makes the review process interesting 😆

2022-06-22 06:31 UTC, vedantmgoyal2009 commented
> Can you fork it on your personal account?
>
> If yes, I can modify the workflow to use the fork from your personal account instead of organization account :)
>
> Note: The GitHub Personal Access Token (PAT) and the fork should be from the same account.

@spowelljr please reply so that we can move forward...

2022-06-27 10:56 UTC, vedantmgoyal2009 commented
> Can you fork it on your personal account?
>
> If yes, I can modify the workflow to use the fork from your personal account instead of organization account :)
>
> Note: The GitHub Personal Access Token (PAT) and the fork should be from the same account.

@spowelljr please reply so that we can move forward...

2022-07-25 06:42 UTC, vedantmgoyal2009 commented
> @vedantmgoyal2009
> 
> > Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @kubernetes
> 
> That's not something we can simply do, getting new repos created under kubernetes requires a review process and in which it would likely be rejected since it's not a repo core to Kubernetes. If that's a requirement we will likely have to abandon this implementation.

@k8s-ci-robot can also be used for this purpose...

2022-07-25 06:42 UTC, vedantmgoyal2009 commented
cc @spowelljr

2022-07-25 06:46 UTC, vedantmgoyal2009 commented
/unassign @spowelljr

2022-07-25 06:47 UTC, vedantmgoyal2009 commented
/assign @spowelljr

2022-07-25 06:55 UTC, vedantmgoyal2009 commented
/auto-cc

/cc @spowelljr 

/skip

2022-07-25 06:55 UTC, vedantmgoyal2009 commented
/auto-cc

2022-07-25 06:55 UTC, vedantmgoyal2009 commented
/skip

2022-07-25 06:56 UTC, vedantmgoyal2009 commented
/cc @spowelljr

2022-07-25 06:58 UTC, vedantmgoyal2009 commented
Can we fork winget-pkgs repo under @k8s-ci-robot or @minikube-bot account?

If yes, I can modify the workflow to use the fork from your personal account instead of organization account :)

Note: The GitHub Personal Access Token (PAT) and the fork should be from the same account.

2022-07-25 06:59 UTC, vedantmgoyal2009 commented
> @vedantmgoyal2009
> 
> > Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @kubernetes
> 
> That's not something we can simply do, getting new repos created under kubernetes requires a review process and in which it would likely be rejected since it's not a repo core to Kubernetes. If that's a requirement we will likely have to abandon this implementation.

Can we fork winget-pkgs repo under @k8s-ci-robot or @minikube-bot account?

If yes, I can modify the workflow to use the fork from your personal account instead of organization account :)

Note: The GitHub Personal Access Token (PAT) and the fork should be from the same account.

2022-10-05 18:48 UTC, medyagh requested changes
Thank you for this PR, do u mind clarifying how we can get the WINGET_TOKEN secret? I believe we need to add that to our github secrets

2022-10-08 14:03 UTC, vedantmgoyal2009 commented
> Thank you for this PR, do u mind clarifying how we can get the WINGET_TOKEN secret? I believe we need to add that to our github secrets

@medyagh thanks for getting back. you can create a new token by visiting https://github.com/settings/tokens/new.

2023-01-06 20:32 UTC, vedantmgoyal2009 commented
/remove-lifecycle stale

2023-04-07 09:43 UTC, vedantmgoyal2009 commented
/remove-lifecycle stale

2023-06-14 03:29 UTC, spowelljr commented
> Can we fork winget-pkgs repo under @k8s-ci-robot or @minikube-bot account?
> 
> If yes, I can modify the workflow to use the fork from your personal account instead of organization account :)
> 
> Note: The GitHub Personal Access Token (PAT) and the fork should be from the same account.

Hi @vedantmgoyal2009, sorry for the delay. Yes, I can fork winget-pkgs as @minikube-bot, I'll do it tomorrow.

2023-06-14 20:50 UTC, spowelljr commented
@vedantmgoyal2009 Repo is forked https://github.com/minikube-bot/winget-pkgs

2023-06-15 03:56 UTC, vedantmgoyal2009 commented
@spowelljr just one thing more... create a github personal access token (PAT) on @minikube-bot and add it as repository secret named `WINGET_TOKEN`.

2023-06-15 21:16 UTC, spowelljr commented
> @spowelljr just one thing more... create a github personal access token (PAT) on @minikube-bot and add it as repository secret named `WINGET_TOKEN`.

What permissions does the PAT need?

2023-06-15 21:24 UTC, vedantmgoyal2009 commented
@spowelljr only one permission is needed: `public_repo`

2023-06-15 21:34 UTC, spowelljr commented
> @spowelljr only one permission is needed: `public_repo`

Just created it

2023-06-15 21:37 UTC, spowelljr requested changes

2023-06-15 21:37 UTC, spowelljr commented on .github/workflows/winget.yml
> +      - uses: vedantmgoyal2009/winget-releaser@v2
```suggestion
      - uses: vedantmgoyal2009/winget-releaser@79853c0938cc9946c1ec3cdd1b2e761bb0372b8c
```
For security reasons, we use the commit instead

2023-06-15 22:39 UTC, vedantmgoyal2009 commented
> > @spowelljr only one permission is needed: `public_repo`
> 
> Just created it and added it as a repo secret to https://github.com/minikube-bot/winget-pkgs, right?

Seems like I couldn't make myself clear the first time. The secret should be added to this repository so that this workflow can access it.

2023-06-15 22:39 UTC, vedantmgoyal2009 commented
> > @spowelljr only one permission is needed: `public_repo`
> 
> Just created it and added it as a repo secret to https://github.com/minikube-bot/winget-pkgs, right?

Seems like I couldn't make myself clear the first time. The secret should be added to this repository so that this workflow can access it.

2023-06-15 23:08 UTC, spowelljr commented
Done

2023-06-18 11:22 UTC, vedantmgoyal2009 commented
We can merge now :)

2023-06-30 20:45 UTC, spowelljr approved these changes
Awesome, thanks for your patience!

2023-06-30 20:45 UTC, merged