update start help info, deprecated --network-plugin flag
kubernetes/minikube pull request #14485
Opened 2022-07-01 03:48 UTC by peizhouyu

Indicate --network-plugin flag is deprecated,The description should be updated to indicate that the flag is deprecated and --cni should be used instead.

Fixes https://github.com/kubernetes/minikube/issues/14480

2022-07-01 04:56 UTC, peizhouyu commented
/assign @spowelljr

2022-07-01 18:05 UTC, spowelljr requested changes

2022-07-01 18:05 UTC, spowelljr commented on cmd/minikube/cmd/start_flags.go
> +	startCmd.Flags().String(networkPlugin, "", "The --network-plugin is still supported by Docker (only!), but it is recommended to switch to using a CNI plugin instead.")
```suggestion
	startCmd.Flags().String(networkPlugin, "", ""DEPRECATED: Replaced by --cni")
```

2022-07-04 03:18 UTC, peizhouyu commented on cmd/minikube/cmd/start_flags.go
> +	startCmd.Flags().String(networkPlugin, "", "The --network-plugin is still supported by Docker (only!), but it is recommended to switch to using a CNI plugin instead.")
It has been modified, thanks

2022-07-04 03:19 UTC, peizhouyu commented on cmd/minikube/cmd/start_flags.go
> +	startCmd.Flags().String(networkPlugin, "", "The --network-plugin is still supported by Docker (only!), but it is recommended to switch to using a CNI plugin instead.")
> 
t has been modified, thanks

2022-07-06 20:18 UTC, merged

2022-07-07 03:12 UTC, peizhouyu commented
> Thanks for the PR!
😁