add VerifiedMaintainer field to Addons and display a warning if empty
kubernetes/minikube pull request #14499
Opened 2022-07-03 12:45 UTC by inifares23lab

The Addon type now has another string Field: VerifiedMaintainer
The new field is added to the NewAddon function and to the Addons map.

When enabling an addon if the VerifiedMaintainer field is empty a warning message is displayed:

! The <ADDON_NAME> addon doesn't have a verified maintainer.
Since for now I just added an empty string for every addon, it will always display the warning when enabling

fixes #14493

2022-07-06 21:24 UTC, inifares23lab commented
Hi @spowelljr
apologies
formatted and pushed now

2022-07-06 22:51 UTC, spowelljr commented
Hi @inifares23lab, thanks for formatting the code.

Could you wrap all `Maintainers` that aren't `Google` or `Kubernetes` with `3rd party(X)`.

For example `Portainer.io` to `3rd party (Portainer.io)`

Could you also add `3rd party (Gluster)` as the maintainer for `storage-provisioner-gluster`.

If the `Maintainer` is `Kubernetes` or `Google` could you make the message be the following:
```
<addon_name> is an addon maintained by <maintainer> for any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
```

For the rest of addons could you update your message to:
```
<addon_name> is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.
```

And for 3rd party addons, if there's a verified maintainer for the addon could you also add the following line:
```
<addonn_name> is maintained by <maintainer> for any concerns contact <verified_maintaer> on GitHub.
```

2022-07-07 14:20 UTC, inifares23lab commented
Hello

- updated messages and handled the 3 different cases
- updated 3rd party maintainers and fixed some typos

examples:
💡  auto-pause is an addon maintained by Google. For any concerns contact minikube on GitHub.
    You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS

❗  ambassador is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.

💡  metallb is maintained by 3rd party (MetalLB) for any concerns contact MOCK-VERIFI
ED-MAINTAINER on GitHub.

2022-07-08 19:07 UTC, spowelljr requested changes

2022-07-08 19:07 UTC, spowelljr commented on cmd/minikube/cmd/config/enable.go
> +    You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS`,
```suggestion
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS`,
```

2022-07-08 19:07 UTC, spowelljr commented on cmd/minikube/cmd/config/enable.go
> +				out.Styled(style.Warning, `{{.addon}} is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.`,
```suggestion
				out.Styled(style.Warning, `{{.addon}} is a 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.`,
```

2022-07-08 19:07 UTC, spowelljr commented on cmd/minikube/cmd/config/enable.go
> +					out.V{"addon": addon, "maintainer": maintainer, "verified_maintainer": verifiedMaintainer})
```suggestion
					out.V{"addon": addon, "maintainer": maintainer, "verifiedMaintainer": verifiedMaintainer})
					
```
Can we keep normal Go casing here

2022-07-09 13:30 UTC, inifares23lab commented on cmd/minikube/cmd/config/enable.go
> +					out.V{"addon": addon, "maintainer": maintainer, "verified_maintainer": verifiedMaintainer})
of course

2022-07-14 22:26 UTC, spowelljr requested changes
The Google/Kubernetes and no verified maintainer case is perfect.

But if it's a 3rd party and has a verified maintainer it should have both messages:
```
<addon_name> is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.
<addon_name> is maintained by <maintainer> for any concerns contact <verified_maintaer> on GitHub.
```

That ways they're notified it's a 3rd party addon and to enable at their own risk, but also pointed to someone if they have troubles.

2022-07-14 22:26 UTC, spowelljr commented on cmd/minikube/cmd/config/enable.go
> +					out.V{"addon": addon, "maintainer": maintainer, "verifiedMaintainer": verifiedMaintainer})
```suggestion
			} else if addonBundle.VerifiedMaintainer != "" {
				out.Styled(style.Tip, `{{.addon}} is maintained by {{.maintainer}} for any concerns contact {{.verifiedMaintainer}} on GitHub.`,
					out.V{"addon": addon, "maintainer": maintainer, "verifiedMaintainer": addonBundle.VerifiedMaintainer})
```

The assigning within the if statement is a bit long and makes it a bit unreadable, I feel doing a direct comparison without assigning a new variable would be better

2022-07-15 12:04 UTC, inifares23lab commented
Hi @spowelljr

I agree that displaying both messages is more clear for the user, however I have one concern:

- the first message also states that the addon is not verified by minikube maintainers even if in some cases it has a VerifiedMaintainer


It may be better to further customize the messages for the two cases:

1. 3rd party without verified maintainer(same as before):
> <addon_name> is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.

2. 3rd party with a verified maintainer(add the first message but omit "or verified"):
> <addon_name> is A 3rd party addon and not maintained by minikube maintainers, enable at your own risk.
> <addon_name> is maintained by <maintainer> for any concerns contact <verified_maintaer> on GitHub.


Let me know if it makes sense to you
thanks

2022-07-15 20:37 UTC, spowelljr commented
Hi @inifares23lab, I know in the issue I originally mentioned a verified maintainer but that was just something I quickly jotted down and should have named it something else.

The field can be called anything, `GitHubMaintainer` or something like that, there's really no verifying the user themselves. Verified is related to the addon itself though, and any addon that's not maintained by Kubernetes or Google isn't verified.

So the message:
`<addon_name> is A 3rd party addon and not maintained or verified by minikube maintainers, enable at your own risk.`
Seems fine to me for both cases because there is no verified maintainer.

2022-07-16 13:56 UTC, inifares23lab commented
understood, thank you for clarifying.
I applied the requested changes

2022-07-18 17:54 UTC, spowelljr requested changes
Looks good! Just a few last comments

2022-07-18 17:54 UTC, spowelljr commented on pkg/minikube/assets/addons.go
> +	}, false, "logviewer", "3rd party (ivans3)", "", "", map[string]string{
```suggestion
	}, false, "logviewer", "3rd party (unknown)", "", "", map[string]string{
```

2022-07-18 17:54 UTC, spowelljr commented on pkg/minikube/assets/addons.go
> +	}, false, "pod-security-policy", "3rd party (pod-security-policy)", "", "", nil, nil),
```suggestion
	}, false, "pod-security-policy", "3rd party (unknown)", "", "", nil, nil),
```

2022-07-18 17:54 UTC, spowelljr commented on pkg/minikube/assets/addons.go
> +	}, false, "registry-aliases", "3rd party (registry-aliases)", "", "", map[string]string{
```suggestion
	}, false, "registry-aliases", "3rd party (unknown)", "", "", map[string]string{
```

2022-07-25 17:31 UTC, spowelljr commented
/ok-to-test

2022-07-26 00:00 UTC, spowelljr approved these changes
Looks good, thanks for your work on this!

2022-07-26 00:00 UTC, merged