Fix Post installation tip for headlamp
kubernetes/minikube pull request #14522
Opened 2022-07-07 09:45 UTC by yolossn

For Kubernetes versions > 1.24 the tokens for service account are not created by default, this patch fixes the help command that gets printed after installation of the headlamp addon to generate a token.  

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2022-07-12 11:04 UTC, yolossn commented
@spowelljr Gentle Ping, Can you please take a look?

2022-07-14 22:04 UTC, spowelljr requested changes
Once you make the changes could you run `make generate-docs` to update the translations and such, thanks

2022-07-14 22:04 UTC, spowelljr commented on cmd/minikube/cmd/config/flags.go
> +	return ""
```suggestion
	_, cc := mustload.Partial(clusterProfile)
	return cc.KubernetesConfig.KubernetesVersion
```
This should do the same thing in an easier way.

2022-07-14 22:06 UTC, spowelljr commented on cmd/minikube/cmd/config/enable.go
> +				if parsedClusterVersion.Major >= 1 && parsedClusterVersion.Minor >= 24 {
I know this might be an extreme case, but this would fail on `2.0`

2022-07-15 17:06 UTC, spowelljr commented
/ok-to-test

2022-07-15 20:18 UTC, merged