Fix tunnel doesn't work for Windows installation with non-en_US language
kubernetes/minikube pull request #14586
Opened 2022-07-14 15:48 UTC by favadi

Fixes #11645

Disclaimer: I'm not very familiar with Windows, so there is a good chance that I don't know what I'm doing. 

In linked issue, there are reports that `minikube tunnel` is failing on Windows installation with non-en_US language. The reason is, we are relying on matching English text of `route` command to know if a command succeed or failed.

I did following experiment on a Windows Russian installation.

```shell
C:\Windows\system32>route add 192.168.1.2 MASK 255.255.255.255 192.168.1.1
 ОК

C:\Windows\system32>route add 192.168.1.2 MASK 255.255.255.255 192.168.1.1
Сбой добавления маршрута: Этот объект уже существует.

C:\Windows\system32>echo %ERRORLEVEL%
0
```

There are few things here:

1. In Russian version, when succeed, the `route add` command prints `OK` instead of `OK!`
2. The failure message is totally in Russian
3. The command still returns 0 when failed

I think (3) is the reason why the English output text matching is added in the first place. 

This PR tries to workaround the issue by setup the console code page to US English before executing any `route` command. 
Reference: https://docs.microsoft.com/id-id/windows-server/administration/windows-commands/chcp.

2022-07-14 20:02 UTC, medyagh requested changes
@favadi thank you for this PR, could you please the output of the minikube tunnel before and after this PR in the description ?

2022-07-14 21:48 UTC, spowelljr commented on pkg/minikube/tunnel/route_windows.go
> +	klog.Infof("%s", stdOutAndErr)
```suggestion
	klog.Info(message)
```
While we're at it do you mind simplifying this since we already converted `message` to a string

2022-07-15 08:48 UTC, favadi commented
@medyagh I updated the description with the testing instructions and the logs before/after this patch.

2022-08-08 21:42 UTC, spowelljr commented
/ok-to-test

2023-01-06 00:22 UTC, closed without merging