Fix french translation
kubernetes/minikube pull request #14739
Opened 2022-08-05 13:38 UTC by jeffmaury

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

2022-08-05 21:15 UTC, klaases approved these changes

2022-08-05 22:58 UTC, spowelljr requested changes

2022-08-05 22:58 UTC, spowelljr commented on translations/fr.json
> +	"The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.\n\t\t\n\t\tPlease install cri-dockerd using these instructions:\n\n\t\thttps://github.com/Mirantis/cri-
```suggestion
	"The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.\n\t\t\n\t\tPlease install cri-dockerd using these instructions:\n\n\t\thttps://github.com/Mirantis/cri-dockerd#build-and-install": "Le pilote none avec Kubernetes v1.24+ et l'environnement d'exécution du conteneur docker nécessitent cri-dockerd.\n\t\t\n\t\tVeuillez installer cri-dockerd en suivant ces instructions :\n\n\t\thttps://github.com/Mirantis/cri-dockerd#build-and-install",
```

2022-08-05 22:58 UTC, spowelljr commented on translations/fr.json
> +	"The none driver with Kubernetes v1.24+ and the docker container-runtime requires dockerd.\n\t\t\n\t\tPlease install dockerd using these instructions:\n\n\t\thttps://docs.docker.com/engine/install/"
```suggestion
	"The none driver with Kubernetes v1.24+ and the docker container-runtime requires dockerd.\n\t\t\n\t\tPlease install dockerd using these instructions:\n\n\t\thttps://docs.docker.com/engine/install/": "Le pilote none avec Kubernetes v1.24+ et l'environnement d'exécution du conteneur docker nécessitent dockerd.\n\t\t\n\t\tVeuillez installer dockerd en suivant ces instructions :\n\n\t\thttps://docs.docker.com/engine/install/",
```

2022-08-08 16:13 UTC, spowelljr approved these changes

2022-08-08 16:13 UTC, merged