fix: trim docker.io to prevent always writing to daemon
kubernetes/minikube pull request #14956
Opened 2022-09-15 02:03 UTC by g1eny0ung

Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

2022-09-20 03:57 UTC, g1eny0ung commented
@medyagh Have a look when you have time? 👀

2022-09-20 04:19 UTC, medyagh commented
> @medyagh Have a look when you have time? 👀

Thanks for the PR, I am curious, could we add docker.io to all docker hub images instead of trimming it ? 
in our preload images tarball we include images with FQDN

2022-09-20 08:23 UTC, g1eny0ung commented
> > @medyagh Have a look when you have time? 👀
> 
> Thanks for the PR, I am curious, could we add docker.io to all docker hub images instead of trimming it ? in our preload images tarball we include images with FQDN

Makes sense to me. This problem is due to using the `docker images` command. It will check whether an image is from the docker official registry internally, if it is, the default domain will be removed.

But for now, the `docker images` command can not set an option to output the repo name in FQDN format, so I think the easiest and most straightforward way is to keep trimming the docker.io prefix.

2022-09-26 05:51 UTC, g1eny0ung commented
@medyagh PTAL again? This problem currently affects me every time I run `minikube start`.

2022-10-15 01:53 UTC, g1eny0ung commented
@blueelvis Hi, mind taking a look at this please?

2022-10-24 23:36 UTC, spowelljr commented
/ok-to-test

2022-10-25 21:45 UTC, spowelljr requested changes
Hi @g1eny0ung, this looks good, but could you move the trim function to: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/image/image.go

The functions in that file seem to fit more in line with what you're doing here.

2022-10-26 02:56 UTC, g1eny0ung commented
> Hi @g1eny0ung, this looks good, but could you move the trim function to: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/image/image.go
> 
> The functions in that file seem to fit more in line with what you're doing here.

Sure. Thanks for pointing out, I'll update it now.

2022-10-26 23:24 UTC, spowelljr approved these changes

2022-10-26 23:24 UTC, merged