updates the docs for  network option of the start command
kubernetes/minikube pull request #15202
Opened 2022-10-24 14:53 UTC by paularah

Fixes #4663

To start minikube with a user-defined bridge network, You need both a subnet and a gateway. This applies to both the docker and podman drivers. See https://docs.podman.io/en/latest/markdown/podman-network-create.1.html. 

This PR includes that in the documentation and adds the missing gateway option from the start command documentation.

2022-10-24 15:14 UTC, paularah commented
Hey @klaases, pls have a look

2022-10-24 17:48 UTC, spowelljr requested changes
Hi @paularah, `site/content/en/docs/commands/start.md` is a generated file. If you want to update flag descriptions you'll need to update them in https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go and then run `make generate-docs`. Also, `gateway` is not a supported flag for the start command.

2022-10-24 19:35 UTC, paularah commented
@spowelljr  Thanks.  I've  made the neccesary changes. 

If you start minikube with a user-defined brigde network, then you need to explicitly create the network with both a subnet and gateway or minikube will throw  this error `docker: Error response from daemon: user specified IP address is supported only when connecting to networks with user configured subnets.`  for a missing subnet or default back to the minikube network for a missing gateway. 

This update makes that clear in the docs.

2022-10-24 20:16 UTC, spowelljr requested changes

2022-10-24 20:16 UTC, spowelljr commented on cmd/minikube/cmd/start_flags.go
> +	startCmd.Flags().StringP(network, "", "", "Network to run minikube with. Now it is used by docker/podman and KVM drivers. If left empty, minikube will create a new network. User-defined docker/podma
```suggestion
	startCmd.Flags().StringP(network, "", "", "Network to run minikube with. Now it is used by docker/podman and KVM drivers. If left empty, minikube will create a new network. User-defined docker/podman bridge networks need to be created with both a subnet and gateway.")
```

2022-10-26 23:08 UTC, spowelljr requested changes
Can you run `make generate-docs` to update the typo in the documentation

2022-10-28 10:21 UTC, paularah commented
@spowelljr I think this is alright now. Let me know if there are any changes I need to make.

2022-11-08 03:42 UTC, closed without merging