Fix subnet checking
kubernetes/minikube pull request #15394
Opened 2022-11-23 00:18 UTC by spowelljr

**Problem:**
While checking for a free subnet, if an IPv6 network is found `n.IP` is set to `0.0.0.0`, which is then set to `startSubnet`. This will cause an error on the next loop of the check as it add 9 to `0.0.0.0` instead of the starting IP, resulting in the second IP to check for being `0.9.0.0`.

**Expected:**
```
Checking 192.168.49.0
Checking 192.177.49.0
Checking 192.186.49.0
...
```

**Actual:**
```
Checking 192.168.49.0
Checking 0.9.0.0
Checking 0.18.0.0
...
```

**Solution:**
Assign the value returned from `n.IP` to its own variable to not interrupt the checking loop.

2022-11-23 03:05 UTC, medyagh requested changes

2022-11-23 03:05 UTC, medyagh commented on pkg/network/network.go
> +		if isSubnetPrivate(subnet) {
could we add unit test for this ?

2022-11-23 18:31 UTC, medyagh commented
adding @josedonizetti as reviwer

2022-11-29 00:22 UTC, medyagh commented
/ok-to-test

2022-11-30 22:47 UTC, spowelljr commented on pkg/network/network.go
> +		if isSubnetPrivate(subnet) {
Unit tests added

2022-11-30 23:48 UTC, medyagh approved these changes

2022-11-30 23:49 UTC, medyagh approved these changes
lgtm

2022-12-01 18:01 UTC, merged