Resubmit new last-start-only flag
kubernetes/minikube pull request #15770
Opened 2023-02-01 21:36 UTC by nickmancari

I closed my last PR. Here is a re-subbmission for a cleaner branch:

This PR adds the `minikube logs --last-start-only` flag feature as requested here: https://github.com/kubernetes/minikube/issues/15700

Before the PR:
```
$ minikube logs --last-start-only
Error: unknown flag: --last-start-only
See 'minikube logs --help' for usage.

```

After PR: 
```
$ minikube logs --last-start-only

==> Audit <==
|---------|------|----------|------|--------------|---------------------|---------------------|
| Command | Args | Profile  | User |   Version    |     Start Time      |      End Time       |
|---------|------|----------|------|--------------|---------------------|---------------------|
| start   |      | minikube | nick | v0.0.0-unset | 26 Jan 23 15:38 CST | 26 Jan 23 15:58 CST |
|---------|------|----------|------|--------------|---------------------|---------------------|

==> Last Start <==
Log file created at: 2023/01/26 15:38:56
Running on machine: Nicks-MBP
Binary: Built with gc go1.19.5 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0126 15:38:56.202574   76978 out.go:296] Setting OutFile to fd 1 ...
I0126 15:38:56.202791   76978 out.go:348] isatty.IsTerminal(1) = true
I0126 15:38:56.202796   76978 out.go:309] Setting ErrFile to fd 2...
I0126 15:38:56.202801   76978 out.go:348] isatty.IsTerminal(2) = true
I0126 15:38:56.202918   76978 root.go:334] Updating PATH: /Users/nick/.minikube/bin
W0126 15:38:56.203041   76978 root.go:311] Error reading config file at /Users/nick/.minikube/config/config.json: open /Users/nick/.minikube/config/config.json: no such file or directory
I0126 15:38:56.203610   76978 out.go:303] Setting JSON to false
I0126 15:38:56.246624   76978 start.go:125] hostinfo: {"hostname":"Nicks-MBP.home","uptime":5104184,"bootTime":1669664952,"procs":497,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"12.6.1","kernelVersion":"21.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"2e97756e-e296-517d-96d1-91d34cd120f0"}
W0126 15:38:56.246759   76978 start.go:133] gopshost.Virtualization returned error: not implemented yet
I0126 15:38:56.254778   76978 out.go:177] 😄  minikube v0.0.0-unset on Darwin 12.6.1
W0126 15:38:56.270215   76978 preload.go:295] Failed to list preload files: open /Users/nick/.minikube/cache/preloaded-tarball: no such file or directory
```

2023-02-02 01:32 UTC, medyagh requested changes
thanks for resubmitting this PR, the After output shows the minikube logs command is still showing audit logs too... but it only should show the last start logs

2023-02-02 03:12 UTC, nickmancari commented
> thanks for resubmitting this PR, the After output shows the minikube logs command is still showing audit logs too... but it only should show the last start logs

Oh I see. I corrected the output to only show the last start log:

```
$ minikube logs --last-start-only

==> Last Start <==
Log file created at: 2023/02/01 20:55:49
Running on machine: Nicks-MBP
Binary: Built with gc go1.19.5 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0201 20:55:49.529075   63168 out.go:296] Setting OutFile to fd 1 ...
I0201 20:55:49.529464   63168 out.go:348] isatty.IsTerminal(1) = true
I0201 20:55:49.529469   63168 out.go:309] Setting ErrFile to fd 2...
I0201 20:55:49.529477   63168 out.go:348] isatty.IsTerminal(2) = true
I0201 20:55:49.529607   63168 root.go:334] Updating PATH: /Users/nick/.minikube/bin
W0201 20:55:49.529733   63168 root.go:311] Error reading config file at /Users/nick/.minikube/config/config.json: open /Users/nick/.minikube/config/config.json: no such file or directory
I0201 20:55:49.530772   63168 out.go:303] Setting JSON to false
I0201 20:55:49.573892   63168 start.go:125] hostinfo: {"hostname":"Nicks-MBP.home","uptime":5641601,"bootTime":1669664948,"procs":409,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"12.6.1","kernelVersion":"21.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"2e97756e-e296-517d-96d1-91d34cd120f0"}
W0201 20:55:49.573997   63168 start.go:133] gopshost.Virtualization returned error: not implemented yet
I0201 20:55:49.579787   63168 out.go:177] 😄  minikube v0.0.0-unset on Darwin 12.6.1
I0201 20:55:49.588916   63168 notify.go:220] Checking for updates...
I0201 20:55:49.589715   63168 config.go:180] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.26.1
...
```

2023-02-02 17:29 UTC, medyagh commented
/ok-to-test

2023-02-03 17:58 UTC, spowelljr requested changes
Can you also run `make generate-docs` to update website docs for the new flag.

2023-02-03 17:58 UTC, spowelljr commented on cmd/minikube/cmd/logs.go
> +	logsCmd.Flags().BoolVar(&lastStartOnly, "last-start-only", false, "Show logs from last start.")
```suggestion
	logsCmd.Flags().BoolVar(&lastStartOnly, "last-start-only", false, "Show only the last start logs.")
```

2023-02-03 17:58 UTC, spowelljr commented on cmd/minikube/cmd/logs.go
> +				klog.Errorf("failed to output last start logs: %V", err)
```suggestion
				klog.Errorf("failed to output last start logs: %v", err)
```

2023-02-08 21:35 UTC, spowelljr approved these changes

2023-02-08 21:36 UTC, merged