added detail json for addons
kubernetes/minikube pull request #15866
Opened 2023-02-16 07:44 UTC by swastik959

**added detail json for addons**

- fixes #15862

2023-02-16 07:50 UTC, medyagh commented
Thank u for this contribution can u please put the output of minikube before/after this pr

2023-02-16 10:56 UTC, swastik959 commented
> Thank u for this contribution can u please put the output of minikube before/after this pr

@medyagh attached the screenshots . are these the changes you wanted

2023-02-16 15:38 UTC, spowelljr requested changes
This implementation of the PR doesn't respect the `-d` flag. The extra fields should only be shown if `-d` is passed, but currently it's always outputting the extra fields.

2023-02-16 15:38 UTC, spowelljr commented on cmd/minikube/cmd/config/addons_list.go
> +			"docs":       docs,
```suggestion
			"Maintainer": maintainer,
			"Docs":       docs,
```
For consistency sake we should keep the keys starting with a capital.

2023-02-16 15:38 UTC, spowelljr commented on cmd/minikube/cmd/config/addons_list.go
> +	fmt.Println(string(jsonOut))
```suggestion
	out.String(string(jsonOut))
```
This should be left as `out.String`

2023-02-16 16:28 UTC, swastik959 commented
@spowelljr although I have fixed it now but somehow first docs are printing

2023-02-16 16:44 UTC, spowelljr commented
> @spowelljr although I have fixed it now but somehow first docs are printing

I'm not sure what you mean by this, could you explain

2023-02-16 16:50 UTC, swastik959 commented
@spowelljr see the attached image in the release notes in the after section

2023-02-16 16:53 UTC, spowelljr requested changes

2023-02-16 16:53 UTC, spowelljr commented on cmd/minikube/cmd/config/addons_list.go
> +		        }
```suggestion
		addonsMap[addonName] = map[string]interface{}{
                        "Status":  stringFromStatus(enabled),
                        "Profile": cc.Name,
                }
                if addonPrintDocs {
                        addonsMap[addonName]["Maintainer"] = addonBundle.Maintainer
                        addonsMap[addonName]["Docs"] = addonBundle.Docs
```
This code can be refactored to greatly reduce duplication and lines of code

2023-02-16 16:57 UTC, spowelljr commented
> @spowelljr see the attached image in the release notes in the after section

Maps in go are unordered so you can't guarantee the order. But it doesn't matter as this is JSON and only computers are going to use it and they also don't care about the order.

2023-02-16 16:58 UTC, spowelljr commented
Also, please run `make test` before pushing changes up to ensure they pass linting and unit tests.

2023-02-17 06:09 UTC, swastik959 commented
@spowelljr how do I fix linting and unit-tests

2023-02-17 16:33 UTC, spowelljr commented
To fix the linting run `gofmt -s -w .` the unit test is failing because you're using custom indenting with `json.MarshalIndent` so you either have to remove it or update the test.

2023-02-20 06:30 UTC, swastik959 commented
@spowelljr please review this pr now

2023-02-21 18:19 UTC, medyagh commented
/ok-to-test

2023-02-22 21:12 UTC, medyagh approved these changes

2023-02-22 21:12 UTC, merged