translate some fields
kubernetes/minikube pull request #15892
Opened 2023-02-20 09:54 UTC by syxunion

update zh-CN.json

I want too supplement the translation of some fields

2023-02-21 16:48 UTC, spowelljr requested changes

2023-02-21 16:48 UTC, spowelljr commented on translations/zh-CN.json
> +	"{{.name}} doesn't have images.": "{{.name} 没有镜像}",
```suggestion
	"{{.name}} doesn't have images.": "{{.name}} 没有镜像",
```

2023-02-22 05:35 UTC, syxunion commented
Completed modification

2023-02-22 16:52 UTC, spowelljr approved these changes
Thanks for the PR

2023-02-22 16:52 UTC, merged