fix: storage provision identity got changed after every restart
kubernetes/minikube pull request #16141
Opened 2023-03-23 10:01 UTC by vanhtuan0409

fix https://github.com/kubernetes/minikube/issues/16140

Before:

Storage privisioner's identity got random generated at the start. Which will be changed after every restart

After:

Pass in provisioner's identity by environment variable. This will work in single node setup but will not work well for multi node

2023-03-23 17:40 UTC, medyagh reviewed
hi @vanhtuan0409 would you please post before/after this PR in the PR description ?

2023-03-24 02:35 UTC, vanhtuan0409 commented
Hi @medyagh , I added before and after in the description

This is only partial fix as it still not work well in multi node setup

2023-03-24 20:17 UTC, medyagh commented
> Hi @medyagh , I added before and after in the description
> 
> This is only partial fix as it still not work well in multi node setup

did it work in multinode before this PR ? how about instead of random we use the minikube profile name ? 


do they have to be unique name for each node ? if yes then you could use the machine name
currently minikube nodes are named proilfe-m0 m1... m2...

2023-03-25 01:01 UTC, vanhtuan0409 commented
As you can see from this line. The provisioner checks for identity before perform deleting the data folder. If the identity got changed compared to when to PVC was created, the provisioner would skip deleting and return an error
https://github.com/kubernetes/minikube/blob/master/pkg/storage/storage_provisioner.go#L103

The current master branch does not work on single-node and multi-node setups. We don't need different uniq name for each node. But for multi-node setup to work, you need to locate which node the PVC was created in and delete the data folder in exactly that node. It will be a complete redesign I think

Using the machine name is also good, but I don't know how to pass the machine name to the provisioner yet

2023-03-25 20:33 UTC, medyagh commented
> As you can see from this line. The provisioner checks for identity before perform deleting the data folder. If the identity got changed compared to when to PVC was created, the provisioner would skip deleting and return an error https://github.com/kubernetes/minikube/blob/master/pkg/storage/storage_provisioner.go#L103
> 
> The current master branch does not work on single-node and multi-node setups. We don't need different uniq name for each node. But for multi-node setup to work, you need to locate which node the PVC was created in and delete the data folder in exactly that node. It will be a complete redesign I think
> 
> Using the machine name is also good, but I don't know how to pass the machine name to the provisioner yet

If you look at multi node code u can find out

maybe check the code that implements 
minikube node list

2023-03-27 02:26 UTC, vanhtuan0409 commented
storage provisioner is deployed into minikube as a deployment. It is not a part of minikube cli. So I don't think it will be able to access to profile name

My current approach is to passed in environment. AFAIK, minikube node name is also based on profile name
https://github.com/kubernetes/minikube/pull/16141/files#diff-89dd13ca41e2948be16d9c0f163009b685a3536b234be0c9d482253eff5036a3R106

2023-09-06 19:00 UTC, medyagh requested changes

2023-09-06 19:00 UTC, medyagh commented on pkg/storage/storage_provisioner.go
> +	nodeName := os.Getenv("NODE_NAME")
who sets this environment variable ? and I dont see it being set anywhere ? 

also the name should be unique to minikube to not collide withe other tools, such as
MINIKUBE_STORAGE_PROVISIONER_NAME...or something like that

2023-11-29 19:59 UTC, medyagh requested changes
do you mind pasting the Before After this PR output with a full example describing the problem and example showing solving the probem?
[vanhtuan0409](https://github.com/vanhtuan0409)

2024-02-20 17:52 UTC, medyagh commented
@vanhtuan0409 thank you for your patience on this PR review time, do you mind adding an Example of Before and After?
by before after I mean, provide an example with minikube ouptput Before and After your PR

2024-03-21 18:20 UTC, closed without merging