WIP: Adds solution for runtime_enable kind of errors
kubernetes/minikube pull request #16218
Opened 2023-04-03 14:24 UTC by x7upLime

We're trying to reproduce an error for a RUNTIME_ENABLE reason,
so that we can provide specific solutions for that class of errors.

## how to reproduce:
`Tested inside an ubuntu kinetic w/ 3cpu 3Gmemory`
Executing the following on a freshly provisioned box, I was able to reproduce a RUNTIME_ENABLE kind of error.
```bash
#!/bin/bash

ARCH="amd64"
DEST="/opt/cni/bin"
CRI_DOCKERD_VERSION="v0.3.1"
CRICTL_VERSION="v1.26.1"
CNI_PLUGINS_VERSION="v1.2.0"
DOWNLOAD_DIR="/usr/local/bin"

if [ $EUID -ne 0 ]
then
        echo "Must run as root!"
        exit
fi

echo "Installing dependencies"
apt-get install conntrack apt-transport-https ca-certificates curl -y

if ! hash docker
then
        echo "Getting docker sh'ing get.docker.com"
        curl -Ssl https://get.docker.com | sh -
        usermod -aG docker $(id -un)
else
        echo "docker already installed.. not doing anything"
fi

echo "Getting cri-dockerd"
curl -LO https://github.com/Mirantis/cri-dockerd/releases/download/$CRI_DOCKERD_VERSION/cri-dockerd_0.3.1.3-0.ubuntu-jammy_amd64.deb
dpkg -i cri-dockerd_0.3.1.3-0.ubuntu-jammy_amd64.deb

#### These are provided by `minikube start`
# echo "Getting kübernetes components"
# sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
# echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
# sudo apt-get update
# sudo apt-get install -y kubelet kubeadm kubectl
# sudo apt-mark hold kubelet kubeadm kubectl

curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.1/crictl-v1.26.1-linux-amd64.tar.gz | tar -C $DOWNLOAD_DIR -xz
# cp crictl /usr/bin
cat <<EOF | tee /usr/local/bin/crictl
echo "🤯"
exit -1
EOF
```

The command is
`sudo -E minikube start --driver=none --container-runtime=docker`

### BEFORE:
```
😄  minikube v1.29.0 on Ubuntu 22.10 (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 22.10
E0403 16:16:11.241087    6745 start.go:413] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%p, " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

❌  Exiting due to RUNTIME_ENABLE: Failed to start container runtime: Temporary Error: sudo /usr/local/bin/crictl version: exit status 2
stdout:
🤯

stderr:
/usr/local/bin/crictl: 2: exit: Illegal number: -1

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

```
### AFTER:
```
😄  minikube v1.29.0 on Ubuntu 22.10 (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=3919MB, Disk=4781MB) ...
ℹ️  OS release is Ubuntu 22.10
E0403 15:52:09.070157    4510 start.go:413] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%p, " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

❌  Exiting due to RUNTIME_DOCKER_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 2
stdout:
🤯

stderr:
/usr/local/bin/crictl: 2: exit: Illegal number: -1

💡  Suggestion: It seems like docker/cri-docker could be misconfigured. Please make sure that you followed the recommended installation procedure
📘  Documentation: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
```

works towards #15897 solution

2023-04-03 14:28 UTC, x7upLime commented
I opened this early for discussion..
For details, see pkg/minikube/node/start.go and pkg/minikube/reason/reason.go:
Should we include a different error reason for each container runtime, in order to provide a tailored solution for each?

2023-05-17 19:04 UTC, x7upLime commented on pkg/minikube/reason/reason.go
> +	RuntimeDockerEnable = Kind{ID: "RUNTIME_DOCKER_ENABLE", ExitCode: ExRuntimeError}
rename this to runtime_docker_crictl
and same w/ the others...

2023-05-17 19:06 UTC, x7upLime commented on pkg/minikube/node/start.go
> +		case "docker":
use minikube/pkg/minikube/constants/constants.go for those

2023-05-22 19:03 UTC, medyagh requested changes

2023-05-22 19:03 UTC, medyagh commented on pkg/minikube/reason/known_issues.go
> +		Regexp: re(`(.*bin/crictl.*exit status.*)|(.*rpc error.*)|(.*cri-docker.*)`),
lets match only one thing here ! crictl

2024-01-16 12:00 UTC, closed without merging