Removes storage_driver option from /etc/docker/daemon.json
kubernetes/minikube pull request #16235
Opened 2023-04-04 18:15 UTC by x7upLime

This setting is applied by minikube in both /etc/docker/daemon.json and as an override to the service file in
/etc/systemd/system/docker.service.d/10-machine.conf, during provision phase.

If two such directives are set, docker.service will not start

fixes #16231

2023-04-04 18:17 UTC, x7upLime commented
This was the workaround.. 
It should be safe to remove it from here, because we're already setting it inside the service file override in the cmdline.

I'm wondering about linux distros that are not using systemd..

2023-04-09 13:40 UTC, x7upLime commented
The situation is as follows:
##### 1st storage-driver
is set by minikube indiscriminately when configuring the docker cruntime()
```
     // minikube/pkg/minikube/cruntime/docker.go
     func (r *Docker) setCGroup(driver string) error {
     	fmt.Printf("configuring docker to use %q as cgroup driver...\n", driver)
	daemonConfig := fmt.Sprintf(`{
            "exec-opts": ["native.cgroupdriver=%s"],
            "log-driver": "json-file",
            "log-opts": {
            	"max-size": "100m"
            },
            "storage-driver": "overlay2"
            }
            `, driver)
```
##### 2nd storage-driver
is set as an override for the systemd service file, by libmachine code, that minikube relias upon... 
It happens only with ssh driver and none driver, because of this check:
```
// minikube/pkg/minikube/machine/machine.go
// fastDetectProvisioner provides a shortcut for provisioner detection
func fastDetectProvisioner(h *host.Host) (libprovision.Provisioner, error) {
	d := h.Driver.DriverName()
	switch {
	case driver.IsKIC(d):
		return provision.NewUbuntuProvisioner(h.Driver), nil
	case driver.BareMetal(d), driver.IsSSH(d):
		return libprovision.DetectProvisioner(h.Driver)
	default:
		return provision.NewBuildrootProvisioner(h.Driver), nil
	}
}
``` 
with every other driver we call minikube code for provisioning of the machine, with ssh/none driver, we default to the provisioner of libmachine.

2023-04-09 14:01 UTC, x7upLime commented
minikube implements 2 libmachine-compatible provisioners:
UbuntuProvisioner -- for kic driver
BuildrootProvisioner -- for everything else
while libmachine implements a ton of provisioners (machine/libmachine/provision/*.go)

Our storage-driver gets set by the provisioner's method `GenerateDockerOptions`.
In minikube's codebase, **UbuntuProvisioner** and **BuildRootProvivisioner** don't set *storage-driver*
while inside libmachine's codebase, provisioners may set *storage-driver* (say ***SystemdProvisioner**)

2023-04-09 15:32 UTC, x7upLime commented
solutions I can think of..
1. export the driver we're using at runtime as a getter function, and use that value to conditionally change the config for /etc/docker/daemon.json: if driver.IsNone() || driver.IsSSH() {don't insert storage-driver option}. **But**: "adding a global variable and ensuring it gets valued at runtime?"

2. Add a `MachineDriver` field in the docker cruntime struct, in order to change the config as described above.. This could mean modifying the signature for the function that generates cruntime config, and modifying its call parameters in a lot of places
  ```
// New returns an appropriately configured runtime
func New(c Config) (Manager, error) {
	sm := sysinit.New(c.Runner)

	switch c.Type {
	case "", "docker":
		sp := c.Socket
		cs := ""
		// There is no more dockershim socket, in Kubernetes version 1.24 and beyond
		if sp == "" && c.KubernetesVersion.GTE(semver.MustParse("1.24.0-alpha.0")) {
			sp = ExternalDockerCRISocket
			cs = "cri-docker"
		}
		return &Docker{
			Socket:            sp,
			Runner:            c.Runner,
			NetworkPlugin:     c.NetworkPlugin,
			ImageRepository:   c.ImageRepository,
			KubernetesVersion: c.KubernetesVersion,
			Init:              sm,
			UseCRI:            (sp != ""), // !dockershim
			CRIService:        cs,
			MachineDriver: "???",
		}, nil
 ...
  ```
  **But**: "changing a struct (*Config*) and related initializer, that gets called across all the codebase?"

3. Somehow "override" the `GenerateDockerOptions` method of whatever provisioner gets initialized by libmachine... **But**: "a method override just to change an option in a config file?"

2023-04-09 17:36 UTC, x7upLime commented
or...
we could play along the libmachine's intended behavior of taking care of the storage-driver option, inside the *provisioner* logic, and not outside
Meaning we don't add unnecessary complexity, we rather adjust the other two provisioners inside the minikube codebase.

2023-04-11 09:39 UTC, afbjorklund requested changes
I think the provisioner should be changed instead, and leave cruntime for now...

The /etc/docker/daemon.json comes from the old kubernetes installation docs

https://github.com/kubernetes/website/commit/e7e5f0c912a7cc504703e087178a39a2a645c8ea

   ```shell
   sudo mkdir /etc/docker
   cat <<EOF | sudo tee /etc/docker/daemon.json
   {
     "exec-opts": ["native.cgroupdriver=systemd"],
     "log-driver": "json-file",
     "log-opts": {
       "max-size": "100m"
     },
     "storage-driver": "overlay2",
     "storage-opts": [
       "overlay2.override_kernel_check=true"
     ]
   }
   EOF
   ```

2023-04-11 09:40 UTC, afbjorklund commented
* https://github.com/kubernetes/minikube/issues/16279

2023-04-11 11:17 UTC, x7upLime commented
> I'm not sure where this 10-machine.conf comes from, and we should probably not set it up in the first place ?

If i remember correctly, that comes from the systemd provisioner of the docker-machine lib. That is the default behavior of docker-machine's provisioners: it is the provisioner that sets the storage-driver as a .service ExecStart= override.

> It would make more sense to have the none and ssh drivers use the minikube provisioner, instead of mixing/matching.
>
> The minikube provisioner is currently broken (it doesn't provision docker), but it should be improved instead.
>
> I think it only needs to support the ubuntu and the rhel systems, and not all the other system provisioners.

If I understand correctly, you're suggesting that in order to address this issue and the kind, we should first refactor the provisioner code for the none/generic driver (minikube side). 
We should remove the dependency of docker-machine lib for generic/none, and support only the usecases where minikube none/ssh is used against an ubuntu/rhel system?

2023-04-11 11:29 UTC, x7upLime commented
I can see that inside the minikube codebase, we're using the miniProvisioner interface:
```
// generic interface for minikube provisioner
type miniProvisioner interface {
	String() string
	CompatibleWithHost() bool
	GenerateDockerOptions(int) (*provision.DockerOptions, error)
	Provision(swarmOptions swarm.Options, authOptions auth.Options, engineOptions engine.Options) error
	GetDriver() drivers.Driver
	GetAuthOptions() auth.Options
	SSHCommand(string) (string, error)
}
```

instead of the Provisioner interface of docker-machine:

```
type Provisioner interface {
	fmt.Stringer
	SSHCommander
	GenerateDockerOptions(dockerPort int) (*DockerOptions, error)
	GetDockerOptionsDir() string
	GetAuthOptions() auth.Options
	GetSwarmOptions() swarm.Options
	Package(name string, action pkgaction.PackageAction) error
	Hostname() (string, error)
	SetHostname(hostname string) error
	CompatibleWithHost() bool
	// Do the actual provisioning piece:
	//     1. Set the hostname on the instance.
	//     2. Install Docker if it is not present.
	//     3. Configure the daemon to accept connections over TLS.
	//     4. Copy the needed certificates to the server and local config dir.
	//     5. Configure / activate swarm if applicable.
	Provision(swarmOptions swarm.Options, authOptions auth.Options, engineOptions engine.Options) error
	Service(name string, action serviceaction.ServiceAction) error
	GetDriver() drivers.Driver
	SetOsReleaseInfo(info *OsRelease)
	GetOsReleaseInfo() (*OsRelease, error)
}
```

the former being compatible with the latter.. that's why we're able to use docker-machine provisioners.

2023-04-11 17:28 UTC, afbjorklund commented
Fixing the minikube Provisioner would be a major effort, agreed.

2023-04-12 13:23 UTC, x7upLime commented
taking into considerations all the opinions collected between zoom/slack/github.
All the traces of storage-driver have been wiped in the first commit, since as @afbjorklund pointed, its the default behavior to use overlay2.
If we wanted to enforce the overlay2, the best place is arguably the provisioner; second commit places storage-driver directive into the ExecStart= of the docker service, for the minikube-codebase provisioners.

2023-04-12 13:29 UTC, x7upLime commented
as @spowelljr pointed out, there may be calls to the provisioner between `minikube stop/start`.. and this change may break existing clusters.
checking backwards compatibility...

2023-04-12 13:50 UTC, x7upLime commented
Cluster seems to continue running between `minikube start` from master and `minikube start` from fix-cr_docker_config

```
😄  minikube v1.30.1 on Ubuntu 22.10
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🤦  StartHost failed, but will try again: provision: ssh command error:
command : sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
err     : Process exited with status 1
output  : --- /lib/systemd/system/docker.service	2023-04-12 13:39:58.584369590 +0000
+++ /lib/systemd/system/docker.service.new	2023-04-12 13:40:23.016636132 +0000
@@ -25,7 +25,7 @@
 # NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
 # container runtimes. If left unlimited, it may result in OOM issues with MySQL.
 ExecStart=
-ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 
+ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay2 --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 
 ExecReload=/bin/kill -s HUP $MAINPID
 
 # Having non-zero Limit*s causes performance problems due to accounting overhead
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.3 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

And the journalctl logs:
```
-- Logs begin at Wed 2023-04-12 13:39:57 UTC, end at Wed 2023-04-12 13:41:27 UTC. --
Apr 12 13:39:57 minikube systemd[1]: Starting Docker Application Container Engine...
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.526771737Z" level=info msg="Starting up"
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527588104Z" level=info msg="[core] [Channel #1] Channel created" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527608260Z" level=info msg="[core] [Channel #1] original dial target is: \"unix:///run/containerd/containerd.sock\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527636216Z" level=info msg="[core] [Channel #1] parsed dial target is: {Scheme:unix Authority: Endpoint:run/containerd/containerd.sock URL:{Scheme:unix Opaque: User: Host: Path:/run/containerd/containerd.sock RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527646599Z" level=info msg="[core] [Channel #1] Channel authority set to \"localhost\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527730407Z" level=info msg="[core] [Channel #1] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"/run/containerd/containerd.sock\",\n      \"ServerName\": \"\",\n      \"Attributes\": {},\n      \"BalancerAttributes\": null,\n      \"Type\": 0,\n      \"Metadata\": null\n    }\n  ],\n  \"ServiceConfig\": null,\n  \"Attributes\": null\n} (resolver returned new addresses)" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527772219Z" level=info msg="[core] [Channel #1] Channel switches to new LB policy \"pick_first\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527820647Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel created" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527863574Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527898021Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel picks a new address \"/run/containerd/containerd.sock\" to connect" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.527908037Z" level=info msg="[core] [Channel #1] Channel Connectivity change to CONNECTING" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.528240705Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to READY" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.528348427Z" level=info msg="[core] [Channel #1] Channel Connectivity change to READY" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529577426Z" level=info msg="[core] [Channel #4] Channel created" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529588249Z" level=info msg="[core] [Channel #4] original dial target is: \"unix:///run/containerd/containerd.sock\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529601516Z" level=info msg="[core] [Channel #4] parsed dial target is: {Scheme:unix Authority: Endpoint:run/containerd/containerd.sock URL:{Scheme:unix Opaque: User: Host: Path:/run/containerd/containerd.sock RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529606885Z" level=info msg="[core] [Channel #4] Channel authority set to \"localhost\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529634065Z" level=info msg="[core] [Channel #4] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"/run/containerd/containerd.sock\",\n      \"ServerName\": \"\",\n      \"Attributes\": {},\n      \"BalancerAttributes\": null,\n      \"Type\": 0,\n      \"Metadata\": null\n    }\n  ],\n  \"ServiceConfig\": null,\n  \"Attributes\": null\n} (resolver returned new addresses)" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529647550Z" level=info msg="[core] [Channel #4] Channel switches to new LB policy \"pick_first\"" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529660451Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel created" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529670836Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to CONNECTING" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529680903Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel picks a new address \"/run/containerd/containerd.sock\" to connect" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529728667Z" level=info msg="[core] [Channel #4] Channel Connectivity change to CONNECTING" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.529764700Z" level=info msg="[core] [Channel #4 SubChannel #5] Subchannel Connectivity change to READY" module=grpc
Apr 12 13:39:57 minikube dockerd[142]: time="2023-04-12T13:39:57.52977968 [...]

2023-04-19 18:37 UTC, spowelljr commented
ok-to-build-iso

2023-04-20 14:53 UTC, spowelljr commented
/ok-to-test

2023-04-24 20:57 UTC, x7upLime commented
/retest

2023-04-24 21:03 UTC, spowelljr commented
/retest-this-please

2023-06-29 16:53 UTC, f0rkz commented
Seeing the same issue in debian... Any progress on this fix?

2024-01-16 12:00 UTC, closed without merging