Kicbase: Resolve docker build deprecation
kubernetes/minikube pull request #16252
Opened 2023-04-06 20:36 UTC by spowelljr

On kicbase, running `docker build` on minikube's Docker returns:
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

2023-04-06 20:37 UTC, spowelljr commented
ok-to-build-image

2023-04-06 21:20 UTC, spowelljr commented
/ok-to-test

2023-04-06 21:53 UTC, medyagh approved these changes

2023-04-08 00:09 UTC, medyagh approved these changes

2023-04-08 00:14 UTC, medyagh commented
@spowelljr 
this test could be related

https://storage.googleapis.com/minikube-builds/logs/16252/28694/Hyperkit_macOS.html#fail_TestImageBuild%2fserial%2fBuildWithBuildArg

2023-04-11 17:37 UTC, medyagh requested changes

2023-04-11 17:37 UTC, medyagh commented on test/integration/image_test.go
> +	if KicDriver() {
rr.Output()

2023-04-11 18:48 UTC, medyagh approved these changes

2023-04-11 20:10 UTC, merged