add github action for running minikube-image-benchmark
kubernetes/minikube pull request #17058
Opened 2023-08-14 11:34 UTC by ComradeProgrammer

This PR add github action for running minikube-image-benchmark

2 pictures will be generated and uploaded to s3. Here are the example of these photos (generated with fake data)

![interative](https://github.com/kubernetes/minikube/assets/46831212/cc46a52a-9642-4ad3-91d4-d4a8c78fdc8b)
![non-interative](https://github.com/kubernetes/minikube/assets/46831212/ab1d0ede-e351-4510-99a8-c4a731d4faf8)

2023-08-27 09:01 UTC, ComradeProgrammer commented
@medyagh @spowelljr  could you please have a look at the revised PR?

Now it shows the performance changes over time, as we have discussed in the previous office hour.

2023-09-11 18:08 UTC, medyagh requested changes
lets have one chart per container runtime

2023-09-11 18:16 UTC, medyagh requested changes

2023-09-11 18:16 UTC, medyagh commented on hack/benchmark/build_and_run/publish-chart.sh
> +copy ./Iterative_buildpacksFewLargeFiles_chart.png "$BUCKET/Iterative_buildpacksFewLargeFiles_chart.png"
lets choose only 1 method for now, itterative few Large would be good enoug

2023-09-11 18:16 UTC, medyagh commented on hack/benchmark/build_and_run/generate-chart.go
> +/*
the folder name could be hack/benchmark/image-build

2023-09-20 18:47 UTC, medyagh requested changes

2023-09-20 18:47 UTC, medyagh commented on .github/workflows/minikube-image-benchmark.yml
> +name: "build-and-run Publish Chart"
change name to "publish image benchmark "

2023-09-20 18:47 UTC, medyagh requested changes

2023-09-20 18:47 UTC, medyagh commented on .github/workflows/minikube-image-benchmark.yml
> +  build-and-run-benchmark:
also change this to image-benchmark, since we have other benchmarks we dont wanna confuse this with other jobs

2023-09-21 16:26 UTC, ComradeProgrammer commented
@medyagh the comments have been solved

but it seems that the automation test cannot pull submodule correctly

2023-09-21 19:21 UTC, medyagh commented
> @medyagh the comments have been solved
> 
> but it seems that the automation test cannot pull submodule correctly

yeah plz check how we can fix this https://app.netlify.com/sites/kubernetes-sigs-minikube/deploys/650c6df8085de50008eb8ece

2023-09-21 19:22 UTC, medyagh commented
we should not break deploy/netlify

2023-09-25 20:48 UTC, medyagh commented
@ComradeProgrammer plz fix the lint

2023-09-27 20:04 UTC, medyagh approved these changes

2023-09-28 20:59 UTC, merged