Add Hyper-V memory validation
kubernetes/minikube pull request #17325
Opened 2023-09-29 23:37 UTC by spowelljr

Closes https://github.com/kubernetes/minikube/issues/17242

Added logic to ensure that if `--memory max` is passed we don't generate an invalid memory value for Hyper-V and added validation to ensure odd MB memory value isn't passed to Hyper-V.

```
$ minikube start --driver hyperv --memory 6001
...

⛔  Exiting due to RSRC_INVALID_HYPERV_MEMORY: Hyper-V requires that memory MB be an even number, 6001MB was specified
```

2023-10-02 18:49 UTC, medyagh requested changes

2023-10-02 18:49 UTC, medyagh commented on cmd/minikube/cmd/start.go
> +		exitIfNotForced(reason.RsrcInvalidHyperVMemory, "Hyper-V requires that memory MB be an even number, {{.memory}}MB was specified", out.V{"memory": req})
we could suggest, "--memory=req-1"

2023-10-02 21:22 UTC, spowelljr commented on cmd/minikube/cmd/start.go
> +		exitIfNotForced(reason.RsrcInvalidHyperVMemory, "Hyper-V requires that memory MB be an even number, {{.memory}}MB was specified", out.V{"memory": req})
Done

2023-10-03 19:48 UTC, medyagh commented
/ok-to-test

2023-10-04 18:43 UTC, merged