CI: Auto update node version
kubernetes/minikube pull request #17903
Opened 2024-01-05 18:59 UTC by spowelljr

2024-01-08 19:51 UTC, medyagh requested changes

2024-01-08 19:51 UTC, medyagh commented on .github/workflows/update-node-version.yml
> +name: "update-node-version"
consider a more explicit name such as update-site-node-version

2024-01-10 21:56 UTC, spowelljr commented on .github/workflows/update-node-version.yml
> +name: "update-node-version"
Renamed

2024-01-10 23:02 UTC, medyagh approved these changes

2024-01-10 23:02 UTC, merged