WIP ci: bump macos version to 13
kubernetes/minikube pull request #18609
Opened 2024-04-09 10:23 UTC by ComradeProgrammer

WIP ci: bump macos version to 13

2024-04-09 10:25 UTC, ComradeProgrammer commented
@spowelljr  @medyagh could you please type an ok-to-test?
Now I changed the value of `runs-on` to `[macos-13,x64]` according to https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job 

I think it may works

2024-04-09 16:13 UTC, spowelljr commented
The additional tags are for self-hosted runners where you specify the tags on the runner itself, I don't think this is going to work.

2024-04-09 16:34 UTC, ComradeProgrammer commented
> The additional tags are for self-hosted runners where you specify the tags on the runner itself, I don't think this is going to work.

I see. I shall try something else later

2024-04-15 22:49 UTC, ComradeProgrammer commented
I think this time it might work.
Basically, what I did is that adding a new workflow into the github action. This workflow use PR workflow as its dependency, so that it will be triggered once this workflow is finished.

This workflow will try to use gh commandline to check the log of its depedent PR workflow to see if there are warnings about incorrect architecture(`gh run view ${{ github.event.workflow_run.id }} --log | grep ':type=>:arm'`) .

 If such error is found in the log, then it will try to fetch the jobid of `PR / functional_virtualbox_macos ` (` JOBID=`gh run view ${{ github.event.workflow_run.id }} --json jobs | jq '.jobs[] | select ( .name == "functional_virtualbox_macos") | .databaseId'``)and rerun it(`gh run rerun --job $JOBID`)

I created a test repo and used a simplified version of it, and I think it works. However, it seems that this change cannot take effect before it is merged.

2024-04-15 23:44 UTC, medyagh commented on .github/workflows/virtual_box_rerun.yml
> +# This is a basic workflow to help you get started with Actions
add better comments and explain what is this and why we need it

2024-04-15 23:45 UTC, medyagh commented
> mmandline to check the log of its depedent PR workflow to see if there are warnings about incorrect architecture(`gh run view ${{ github.event.workflow_run.id }} --log | grep ':type=>:arm'`) .
> 
> If such error is found in the log, then it will try to fetch the jobid of `PR / functional_vir`

cool, lets see if you can make the Test Pass too ?

2024-04-15 23:46 UTC, medyagh commented on .github/workflows/virtual_box_rerun.yml
> +          gh run view ${{ github.event.workflow_run.id }} --log | grep ':type=>:arm'
in the Original Job, we should have a Check that checks "step" for Architecture
and in the step it should fail Nice-er

2024-04-22 18:31 UTC, medyagh requested changes

2024-04-22 18:31 UTC, medyagh commented on .github/workflows/pr.yml
> +          exit 0
if this "Exit 0" will it still be triggered by the Re-Run job

2024-04-22 18:31 UTC, medyagh commented on .github/workflows/pr.yml
> +          exit 0
I also suggest that you create an issue in in minikube and also in Github Action itself, so they can fix this for everyone, they should not give users Arm Machines

2024-06-13 16:55 UTC, medyagh commented
@ComradeProgrammer can we make sure we have create an issue in Github Action to make sure they know this issue exists?

2024-07-04 03:39 UTC, spowelljr commented
How often was this occurring? I just tried to replicate this, I ran 50 jobs using a `macos-13` runner and all of them gave me an x86 machine. Was this possibly resolved?

2024-07-09 16:15 UTC, medyagh commented
I think I would like to do this PR without the Re-Run logic that way at least we will have a nice message that it failed

2024-07-15 18:37 UTC, spowelljr commented
VirtualBox doesn't support macOS 13+ so I think we can close this PR.

2024-07-15 18:37 UTC, closed without merging