Add instructions for Linux OS systemd-resolved to ingress-dns documentation
kubernetes/minikube pull request #18728
Opened 2024-04-23 09:49 UTC by gpelouze

Fixes #18727

This PR adds instructions to setup the ingress DNS on Linux systems using `systemd-resolved`. This is relevant because Ubuntu>=22.04 uses this resolver.

2024-05-07 20:28 UTC, medyagh requested changes
thanks for this PR do u mind pasting an example of this Before this instructions and does it apply to all Linux users ? or only ubuntu?

2024-05-07 20:28 UTC, medyagh commented on site/content/en/docs/handbook/addons/ingress-dns.md
> +Run the following commands to add the Minikube DNS for `.test` domains:
minikube should be lowercase

2024-05-07 20:28 UTC, medyagh commented on site/content/en/docs/handbook/addons/ingress-dns.md
> +sudo mkdir /etc/systemd/resolved.conf.d
let do -p incase it exsits

```sudo mkdir -p /etc/systemd/resolved.conf.d
```

2024-05-12 19:21 UTC, Dmarcotrigiano commented
When following these docs, I can now correctly connect to my services from my host machine at their <service>.test domain, but API calls to other services such as below are now failing.
```
https://api.stripe.com/v1/products\": dial tcp: lookup api.stripe.com on 10.96.0.10:53: no such host
```

2024-05-24 20:37 UTC, merged