18724
kubernetes/minikube pull request #18814
Opened 2024-05-06 14:52 UTC by xcarolan

Ref: Issue 18724
Exit gracefully  from mount of 9p file type when the host does not support 9p.
/sig cluster-lifecycle
/kind improvement
/area minikube
/assign

2024-05-06 15:39 UTC, xcarolan commented
/approve prezha

2024-05-07 16:36 UTC, medyagh commented on cmd/minikube/cmd/mount.go
> +			exit.Message(reason.GuestMount, "mount failed, does host support filesystem type 9p?")
@xcarolan I dont think this PR is actually doing any detection, or any improvement over the current situation,
if I am wrong, do you mind pasting the output Before and After this PR to prove?

there should be a mechanisim to Detect if this the host supports 9P or not, and if it doesn't it should detect it let the user know befrehand

2024-05-07 16:37 UTC, medyagh requested changes
please see the comment

2024-05-07 21:48 UTC, xcarolan commented
yes, all I did was change the error type so instead of this:
![image](https://github.com/kubernetes/minikube/assets/15894686/1d6ee5b7-8ffc-4b20-9cf2-76a9fcbae71c)

you get this:

![image](https://github.com/kubernetes/minikube/assets/15894686/5cb76324-68b3-499d-b5c3-f0533b263ff4)

I was trying to find some way of checking the host system to see if it supported 9p, but could find anything. If you are aware of a way of checking, or can point me in the right direction, I'll go back and change it. As it stands now, i'm really not sure how useful (if at all) this change is.
Thanks for the feedback,

2024-05-08 22:00 UTC, xcarolan commented
Actually let me pull this back and rework it,,

2024-05-08 22:01 UTC, closed without merging

2024-05-08 22:02 UTC, xcarolan commented
reworking...