Fix for linkable tabs ui breaking
kubernetes/minikube pull request #18982
Opened 2024-05-28 19:56 UTC by hritesh04

#18977 

fix for breaking changes 

### problem 

The issue was on macOS where the ui breaks when there is no parameters

### solution

in quiz file in line 59 the comparison should be with mac not Mac

This will fix the ui breaking if the issue was generated in macos

2024-05-28 20:11 UTC, spowelljr requested changes
Just those two spaces and looks good to me

2024-05-28 20:11 UTC, spowelljr commented on site/static/js/quiz.js
> +  //auto-select the first option for the user, to reduce the number of clicks
```suggestion
  // auto-select the first option for the user, to reduce the number of clicks
```

2024-05-28 20:11 UTC, spowelljr commented on site/static/js/quiz.js
> +    //checks for query params and process each option one by one
```suggestion
    // checks for query params and process each option one by one
```

2024-05-28 20:19 UTC, hritesh04 commented
done

2024-05-28 20:27 UTC, spowelljr requested changes

2024-05-28 20:27 UTC, spowelljr commented on site/static/js/quiz.js
> +    if (autoselect) {
Once last thing, this is unnecessarily double nested, could these two be `&&` together

2024-05-28 21:11 UTC, hritesh04 commented
done

2024-05-29 00:02 UTC, spowelljr approved these changes

2024-05-29 00:02 UTC, merged