fix: fix empty tarball when generating image save
kubernetes/minikube pull request #19312
Opened 2024-07-21 22:34 UTC by ComradeProgrammer

FIX #19233
### What happened: T.B.D.

### Before&After: T.B.D.

2024-07-21 23:00 UTC, ComradeProgrammer commented
/ok-to-test

2024-07-23 16:30 UTC, medyagh commented
@ComradeProgrammer excellent ! thank you for such a detailed PR description, please check the docker Linux CRIO tests
for imageLoad 
https://storage.googleapis.com/minikube-builds/logs/19312/35447/Docker_Linux_crio.html#fail_TestFunctional%2fparallel%2fImageCommands%2fImageLoadDaemon

2024-07-29 18:30 UTC, medyagh requested changes
plz take a look at this PR https://github.com/kubernetes/minikube/pull/19344

and let me know if we merge that PR or this, are they gonna affect each other

2024-07-29 19:04 UTC, ComradeProgrammer commented
```
docker@minikube:~$ sudo crictl image ls
IMAGE                                     TAG                  IMAGE ID            SIZE
docker.io/kicbase/echo-server             latest               ce2d2cda2d858       2.17MB
docker.io/kindest/kindnetd                v20240202-8f1494ea   4740c1948d3fc       25.3MB
gcr.io/k8s-minikube/storage-provisioner   v5                   ba04bb24b9575       8.03MB
registry.k8s.io/coredns/coredns           v1.11.1              2437cf7621777       16.5MB
registry.k8s.io/etcd                      3.5.12-0             014faa467e297       66.2MB
registry.k8s.io/kube-apiserver            v1.30.0              181f57fd3cdb7       29.9MB
registry.k8s.io/kube-controller-manager   v1.30.0              68feac521c0f1       28.3MB
registry.k8s.io/kube-proxy                v1.30.0              cb7eac0b42cc1       25.6MB
registry.k8s.io/kube-scheduler            v1.30.0              547adae34140b       17.6MB
registry.k8s.io/pause                     3.9                  829e9de338bd5       268kB
docker@minikube:~$ sudo ctr -n=k8s.io images check
REF                                                                                                             TYPE                                                      DIGEST                                                                  STATUS            SIZE              UNPACKED 
docker.io/kicbase/echo-server:latest                                                                            application/vnd.docker.distribution.manifest.v2+json      sha256:0fabc732ad18ac2e4eea22a8449cb04c9b96651282c688d76158012ce9bf53e9 complete (2/2)    2.1 MiB/2.1 MiB   true
docker.io/kindest/kindnetd:v20240202-8f1494ea                                                                   application/vnd.docker.distribution.manifest.list.v2+json sha256:61f9956af8019caf6dcc4d39b31857b868aaab80521432ddcc216b805c4f7988 incomplete (1/5)  1.2 KiB/24.2 MiB  true
docker.io/kindest/kindnetd@sha256:61f9956af8019caf6dcc4d39b31857b868aaab80521432ddcc216b805c4f7988              application/vnd.docker.distribution.manifest.list.v2+json sha256:61f9956af8019caf6dcc4d39b31857b868aaab80521432ddcc216b805c4f7988 incomplete (1/5)  1.2 KiB/24.2 MiB  true
gcr.io/k8s-minikube/storage-provisioner:v5                                                                      application/vnd.docker.distribution.manifest.list.v2+json sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944 incomplete (1/2)  797.0 B/7.7 MiB   true
gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944 application/vnd.docker.distribution.manifest.list.v2+json sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944 incomplete (1/2)  797.0 B/7.7 MiB   true
registry.k8s.io/coredns/coredns:v1.11.1                                                                         application/vnd.docker.distribution.manifest.list.v2+json sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1 incomplete (1/12) 2.7 KiB/15.7 MiB  true
registry.k8s.io/coredns/coredns@sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1         application/vnd.docker.distribution.manifest.list.v2+json sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1 incomplete (1/12) 2.7 KiB/15.7 MiB  true
registry.k8s.io/etcd:3.5.12-0                                                                                   application/vnd.docker.distribution.manifest.list.v2+json sha256:44a8e24dcbba3470ee1fee21d5e88d128c936e9b55d4bc51fbef8086f8ed123b incomplete (1/13) 2.3 KiB/63.1 MiB  true
registry.k8s.io/etcd@sha256:44a8e24dcbba3470ee1fee21d5e88d128c936e9b55d4bc51fbef8086f8ed123b                    application/vnd.docker.distribution.manifest.list.v2+json sha256:44a8e24dcbba3470ee1fee21d5e88d128c936e9b55d4bc51fbef8086f8ed123b incomplete (1/13) 2.3 KiB/63.1 MiB  true
registry.k8s.io/kube-apiserver:v1.30.0                                                                          application/vnd.docker.distribution.manifest.list.v2+json sha256:6b8e197b2d39c321189a475ac755a77896e34b56729425590fbc99f3a96468a3 incomplete (1/14) 2.7 KiB/28.5 MiB  true
registry.k8s.io/kube-apiserver@sha256:6b8e197b2d39c321189a475ac755a77896e34b56729425590fbc99f3a96468a3          application/vnd.docker.distribution.manifest.list.v2+json sha256:6b8e197b2d39c321189a475ac755a77896e34b56729425590fbc99f3a96468a3 incomplete (1/14) 2.7 KiB/28.5 MiB  true
registry.k8s.io/kube-controller-manager:v1.30.0                                                                 application/vnd.docker.distribution.manifest.list.v2+json sha256:5f52f00f17d5784b5ca004dffca59710fa1a9eec8d54cebdf9433a1d134150fe incomplete (1/14) 2.6 KiB/27.0 MiB  true
registry.k8s.io/kube-controller-manager@sha256:5f52f00f17d5784b5ca004dffca59710fa1a9eec8d54cebdf9433a1d134150fe application/vnd.docker.distribution.manifest.list.v2+json sha256:5f52f00f17d5784b5ca004dffca59710fa1a9eec8d54cebdf9433a1d134150fe incomplete (1/14) 2.6 KiB/27.0 MiB  true
registry.k8s.io/kube-proxy:v1.30.0                                                                              application/vnd.docker.distribution.manifest.list.v2+json sha256:ec532ff47eaf39822387e51ec73f1f2502eb74658c6303319db88d2c380d0210 incomplete (1/3)  642.0 B/24.4 MiB  true
registry.k8s.io/kube-proxy@sha256:ec532ff47eaf39822387e51ec73f1f2502eb74658c6303319db88d2c380d0210              application/vnd.docker.distribution.manifest.list.v2+json sha256:ec532ff47eaf39822387e51ec73f1f2502eb74658c6303319db88d2c380d0210 incomplete (1/3)  642.0 B/24.4 MiB  true
registry.k8s.io/kube-scheduler:v1.30.0                                                                          application/vnd.docker.distribution.manifest.list.v2+json sha256:2353c3a1803229970fcb571cffc9b2f120372350e01c7381b4b650c4a02b9d67 incomplete (1/14) 2.6 KiB/16.7 MiB  true
registry.k8s.io/kube-scheduler@sha256:2353c3a1803229970fcb571cffc9b2f120372350e01c7381b4b650c4a02b9d67          application/vnd.docker.distribution.manifest.list.v2+json sha256:2353c3a1803229970fcb571cffc9b2f120372350e01c7381b4b650c4a02b9d67 incomplete (1/14) 2.6 KiB/16.7 MiB  true
registry.k8s.io/pause:3.9                                                                                       application/vnd.docker.distribution.manifest.list.v2+json sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097 incomplete (1/2)  973.0 B/258.9 KiB true
registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097                   application/vnd.docker.distribution.manifest.list.v2+json sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097 incomplete (1/2)  973.0 B/258.9 KiB true
sha256:014faa467e29798aeef733fe6d1a3b5e382688217b053ad23410e6cccd5d22fd                                         application/vnd.docker.distribution.manifest.list.v2+json sha256:44a8e24dcbba3470ee1fee21d5e88d128c936e9b55d4bc51fbef8086f8ed123b incomplete (1/13) 2.3 KiB/63.1 MiB  true
sha256:181f57fd3cdb796d3b94d5a1c86bf48ec261d75965d1b7c328f1d7c11f79f0bb                                         application/vnd.docker.distribution.manifest.list.v2+json sha256:6b8e197b2d39c321189a475ac755a77896e34b56729425590fbc99f3a96468a3 incomplete (1/14) 2.7 KiB/28.5 MiB  true
sha256:2437cf762177702dec2dfe99a09c37427a15af6d9a57c456b65352667c223d93                                         application/vnd.docker.distribution.manifest.list.v2+json sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1 incomplete (1/12) 2.7 KiB/15.7 MiB  true
sha256:4740c1948d3fceb8d7dacc63033aa6299d80794ee4f4811539ec1081d9211f3d                                         application/vnd.docker.distribution.manifest.list.v2+json sha256:61f9956af8019caf6dcc4d39b31857b868aaab80521432ddcc216b805c4f7988 incomplete (1/5)  1.2 KiB/24.2 MiB  true
sha256:547adae34140be47cdc0d9f3282b6184ef76154c44cf43fc7edd0685e61ab73a                                         applicati [...]

2024-07-29 19:05 UTC, medyagh commented on pkg/minikube/cruntime/containerd.go
>  		!strings.Contains(rr.Output(), name) ||
since we use ls can we use exit code instead of Containts?

2024-08-07 21:38 UTC, medyagh approved these changes

2024-08-07 21:38 UTC, merged