Add "-o json" option for "minikube addon images"
kubernetes/minikube pull request #19364
Opened 2024-08-02 08:41 UTC by thomasjm

I wanted to be able to programmatically consume the output of `minikube addon images ADDON_NAME`.

The normal behavior is unchanged:

```shell
$ minikube addons images gvisor
    ▪ gvisor has the following images:
|-------------|----------------------------------------------------------------------------------------------------------|------------------|
| IMAGE NAME  |                                              DEFAULT IMAGE                                               | DEFAULT REGISTRY |
|-------------|----------------------------------------------------------------------------------------------------------|------------------|
| GvisorAddon | k8s-minikube/gvisor-addon:v0.0.1@sha256:d29adbddc7a44dab4c675c0eaea398907fe1f33f5f723274b0d40195b3076cae | gcr.io           |
|-------------|----------------------------------------------------------------------------------------------------------|------------------|
```

But now you can do `-o json`:

```shell
$ minikube addons images gvisor -o json
["gcr.io/k8s-minikube/gvisor-addon:v0.0.1@sha256:d29adbddc7a44dab4c675c0eaea398907fe1f33f5f723274b0d40195b3076cae"]
```

Also fixed the grammar of the existing message from "has following images" to "has the following images."

2024-08-02 17:01 UTC, medyagh requested changes
this seems like a great feature and thanks for adding it, just a couple comments

2024-08-03 08:51 UTC, thomasjm commented on cmd/minikube/cmd/config/images.go
> +			out.Infof("{{.name}} doesn't have images.", out.V{"name": addon})
The diff is being a little confusing here by splitting the old function in half -- there's no logic change here. The "previous" line can still be found below.

2024-08-03 08:51 UTC, thomasjm commented on cmd/minikube/cmd/config/images.go
> +func printAddonImagesJson(addon string) {
Done

2024-08-03 22:28 UTC, medyagh commented
/ok-to-test

2024-08-05 16:50 UTC, medyagh commented
/lgtm

2024-08-05 16:50 UTC, medyagh commented
thanks for this contribution, look forward to see more contributions

2024-08-05 16:50 UTC, merged