Feature/19788
kubernetes/minikube pull request #19790
Opened 2024-10-11 22:21 UTC by fbyrne

fixes #19788

Adds support for kubeadm.k8s.io/v1beta4 available since k8s v1.31

https://kubernetes.io/blog/2024/08/23/kubernetes-1-31-kubeadm-v1beta4/

2024-10-11 22:22 UTC, fbyrne commented
I branched off the AMD support, just ignore that commit it will be removed when the PR gets merged.

2024-10-12 01:30 UTC, spowelljr requested changes
This seems to be branched off of your AMD plugin changes, since that's merged now would you mind rebasing.

I just read your message above now

2024-10-12 01:33 UTC, spowelljr requested changes

2024-10-12 01:33 UTC, spowelljr commented on pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta4.go
> +Copyright 2022 The Kubernetes Authors All rights reserved.
```suggestion
Copyright 2024 The Kubernetes Authors All rights reserved.
```

2024-10-12 01:33 UTC, spowelljr commented on pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta4.go
> +// V1Beta4 is kubeadm config template for Kubernetes v1.23.0+
```suggestion
// V1Beta4 is kubeadm config template for Kubernetes v1.31.0+
```

2024-10-12 16:42 UTC, fbyrne commented
suggestions applied and rebased.

2024-10-14 13:18 UTC, spowelljr commented
/ok-to-test

2024-10-14 19:20 UTC, merged