WIP: Add new external-dns addon for exposing ingress & LoadBalancer external IPs to the host
kubernetes/minikube pull request #9000
Opened 2020-08-14 14:42 UTC by segevfiner

An initial version of an addon for
[external-dns](https://github.com/kubernetes-sigs/external-dns). Based on [ExternalDNS for CoreDNS with minikube](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md). Cobbled together from that tutorial, upstream helm charts, and the way minikube/kubeadm deploy etcd & CoreDNS. Those manifests probably
need some reviewing and tweaking. See TODO below

Add an addon for installing external DNS. See https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md which uses CoreDNS as the DNS server.

Unlike ingress-dns, which is minikube specific:
1. This is sometimes used in production, so will give similar behavior in development to production.
2. Will support LoadBalancer services.

Some notes about configuring the host that also apply for ingress-dns:
1. For Linux distros using `systemd-resolved`, you can use [`systemd.network` units](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for configuring DNS domain specific DNS servers. Using the `Domains` & `DNS` keys in a new network unit matching the required interface. I used it before, but don't remember the details.
2. For Windows, there is NRPT which should allow setting this.

### TODO
- [ ] Which images to use for etcd and CoreDNS? The k8s.io ones minikube uses? or upstream ones (From docs or helm charts)? Using minikube's images means it can use the preloaded ones as long as it is kept up to date, at least for the latest Kubernetes version, though updating those is likely to be forgotten...
- [ ] `readinessProbe`/`livenessProbe`, what times, thresholds should be used, are the scripts, endpoints correct, etc. (I kinda copied them from somewhere and they are not necessarily optimal)
  - [ ] The `readinessProbe` for etcd breaks it because the headless service doesn't register it until it is ready but it queries for it to become ready, At first I tried just disabling it, but that also didn't always work, not sure why, so I added `publishNotReadyAddresses` to the service, which might be correct anyhow, though not sure if I should then add a separate service that does not publish unready addresses, though it is a single node deployment so might not matter much either way.
- [ ] Do any pods here need a `priorityClass`?
- [ ] Do any pods here need `tolerations`?
- [ ] Use `hostPath` instead of PVC for etcd? or maybe make it ephemeral and not use a volume at all?
- [ ] labels for the objects, etc. Are there any labels add-ons normally use? Any label schema this should use instead of just `app`?
- [ ] I used the headless service to access etcd, not sure that's the best/correct way, some etcd deployments seem to also add `ClusterIP` service and use that instead, might not matter much for a single node.
- [ ] The CoreDNS server currently forwards DNS to the in cluster DNS which will also answer for `cluster.local`, which is not desired on the host, had to explicitly `except` it. Not sure if that's the best config. I can't just `dnsPolicy: Default` like the in-cluster CoreDNS because the CoreDNS server needs to resolve the etcd server address.
- [ ] The CoreDNS server is not currently exposed to the host. I think we should use `hostPort` to expose it. This also requires `hostIP` due to having another DNS server listening on localhost on the `minikube` VM, this needs to be set automatically but I'm not sure how to add such a template parameter, as in: where to extract it from inside minikube. Just using `hostNetwork` will be problematic with accessing etcd.
- [ ] Add `README.md` explaining how to configure host, etc. Like `ingress-dns` has. Maybe also an example, though upstream examples using the appropriate domain should work too.
- [ ] The domain is currently hard-coded to `test`, we might want to make that configurable.

fixes #8980

2020-08-15 12:03 UTC, segevfiner commented
/assign @josedonizetti

2020-10-14 19:22 UTC, medyagh commented
hi @segevfiner  this seems to be an interesting addon, do you mind pulling upstream and putting an example output in the description how to use this addon?

2020-10-14 19:23 UTC, medyagh requested changes
if you please put steps in the description how to use this addon with example output this would be a good addon, if you can also document if it works with all drivers or only VM drivers?

2020-10-18 16:53 UTC, segevfiner commented
To make this operational, we still need to somehow set the `hostIP` for exposing the DNS server to the host.

> The CoreDNS server is not currently exposed to the host. I think we should use hostPort to expose it. This also requires hostIP due to having another DNS server listening on localhost on the minikube VM, this needs to be set automatically but I'm not sure how to add such a template parameter, as in: where to extract it from inside minikube. Just using hostNetwork will be problematic with accessing etcd.

But I wasn't sure how to get the addon infrastructure of minikube render that into a templated deployment spec.

The rest of the stuff in the TODO list I left in the PR description are about polishing this as far as I remember.

For trying it out:
```
kubectl create deployment nginx --image nginx
kubectl expose deployment nginx --port 80 --type LoadBalancer
kubectl annotate service nginx "external-dns.alpha.kubernetes.io/hostname=nginx.test"
```

And you should be able to query the created DNS server for it, but we need to fix the expose to host thing so you can do so from the host.

See for my initial POC of this https://github.com/kubernetes/minikube/issues/8980#issuecomment-673708670 for more information.

I only tested this with VM drivers, it likely suffers from whatever issue that prevent the ingress addon from working, that I don't fully understand, on the docker driver, as this too tries to expose a port via the host machine. Though it tries to do so differently using `hostPort`/`hostIP` so it can still communicate with the deployed etcdz rather than `hostNetwork` , once we get the `hostPort`/`hostIP` thing sorted, we can try to see if that works or not.

2020-11-11 19:16 UTC, medyagh commented
hi @segevfiner thanks for this PR, do you mind adding a tutorial of using this new addon with examples
the documentation for addons can be added to https://minikube.sigs.k8s.io/docs/handbook/addons/

2020-11-25 21:50 UTC, segevfiner commented
I will once we can get it fully working, I need help with the last issue I described here: https://github.com/kubernetes/minikube/pull/9000#issuecomment-711287826

The rest of the things mentioned in the PR description are about polishing it, stuff that I wasn't sure about and only someone more familiar with this project might be able to help with.

2020-12-18 00:39 UTC, bl-ue commented
@segevfiner Keep up the great work! 👍 This is a fantastic idea. It's also PR 9,000 :)

2021-01-06 19:34 UTC, tstromberg commented
is this ready to merge?

2021-01-29 13:08 UTC, segevfiner commented
See the PR description for the list of remaining tasks. The major ones being figuring out how to handle `hostIP` so the dns server is exposed, minikube needs to set the `hostIP` in the dns server pod template, and I couldn't figure out where to get it from, and documentation (Which I'm not sure where to write, it is similar to the existing ingress-dns in terms of host setup but I can add some more details on to of what's already there)

2021-03-31 18:23 UTC, spowelljr commented
@segevfiner Is this still something you're working on?

2021-04-07 18:26 UTC, spowelljr commented
@segevfiner I'm going to close this PR due to long duration without activity, but feel free to reopen if you have time to work on  this again.

2021-04-07 18:26 UTC, closed without merging

2021-04-07 18:29 UTC, bl-ue commented
(off-topic: @spowelljr you must have had a reminder or something, didn't you?  Because you close this PR almost exactly 1 week after you last commented, off by only +3 minutes!)

2021-04-07 18:42 UTC, spowelljr commented
@bl-ue That's a really good observation! But actually there's no reminder, every Wednesday 11-12 PST minikube maintainers do through PRs and issues to comment/label/close. The 3 minute difference is somewhat of a coincidence, but would have been within an hour if that makes sense.

2021-04-07 18:47 UTC, bl-ue commented
Yeah that does make sense.  Thank you!