Add install minikube with homebrew on Linux
kubernetes/minikube pull request #9066
Opened 2020-08-23 09:36 UTC by inductor

Homebrew has supported Linux since a while ago and I've been using it on my Linux environment too :)

2020-08-24 17:55 UTC, inductor commented
@medyagh

>if you think adding brew would add a lot of value, I recommend at least adding it in the end and with same format as others

Sure, but I do not think the format is h2(with ##) and `Homebrew install`. I followed other formats as follows

```markdown
### Debian package
### RPM package
```

2020-08-25 21:10 UTC, medyagh commented on site/content/en/docs/start/_index.md
> +If `which minikube` fails after installation via brew, you may have to remove the minikube cask and link the binary:
I rather we keep this first page short, about creating a full page for all the possible installation for linux, and then from here

that says
for hombrew and full notes see ...(link)

2020-08-29 08:15 UTC, afbjorklund commented
Worked fine here, defintely better than the other mess... (the binary, and deb and rpm "hacks")
With their `sudo` and multiple commands and whatever. I'll throw in [0install](https://0install.net/) option too.

Binary download

```
 curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
 sudo install minikube-linux-amd64 /usr/local/bin/minikube
```

Debian package

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb
```

RPM package

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
sudo rpm -ivh minikube-latest.x86_64.rpm
```

Linux Homebrew

```
brew install minikube
```

Zero Install

```
alias minikube='0install run https://apps.0install.net/kubernetes/minikube.xml'
```

2020-08-29 09:48 UTC, inductor commented
>Worked fine here, defintely better than the other mess... (the binary, and deb and rpm "hacks")

Yeah, that's actually the biggest motivation for this Pull Request!

2020-08-29 10:21 UTC, afbjorklund commented
However, the sheer amount of text / different environments is also a problem with the install page.
The first three all deliver the very same "official" binary, which is why they are prominently featured.

It is nowhere as bad as the podman/cri-o pages, with dozens and dozens of distributions, but still...
Another approach would be to use the tabs for the package managers, like is being done here:

https://kubernetes.io/docs/tasks/tools/install-kubectl/

You know, the alternative to `brew install kubectl`. 😃

2020-08-29 10:37 UTC, afbjorklund commented
@inductor : actually we **do** recommend using `brew`:

https://kubernetes.io/docs/tasks/tools/install-minikube/

2020-09-03 05:18 UTC, inductor commented
@afbjorklund @medyagh 

I am actually from SIG-Docs 😅 
So regarding all these, what should the doc be?

2020-09-03 06:40 UTC, afbjorklund commented
>  So regarding all these, what should the doc describe?

I think the original idea (add brew) was OK, just formatting...

* Documentation
  * Get Started!
    * What you’ll need
        1) Installation
           * Linux
              * Binary download
              * RPM package
              * DEB package
              * **Brew Package Manager**
           * macOS
              * Brew Package Manager
              * Binary download
           * Windows
              * Chocolatey Package Manager
              * Binary download
         2) Start your cluster

So it is mostly about fiddling the order around, and improving wording.

It is also somewhat complicated, compared to a big Download button...

2020-09-03 06:52 UTC, afbjorklund commented
The comment from @medyagh was that adding brew would make the Linux list too long.

Maybe nested tabs would fix, but I'm not sure about that approach either - if it even works.

2020-09-03 07:10 UTC, inductor commented
>Maybe nested tabs would fix,

I think it's already nested

2020-09-03 15:57 UTC, afbjorklund commented
> I think it's already nested

I can only see one layer, but nested tabs is probably evil (and I'm not sure if Hugo allows it)

![minikube-installation](https://user-images.githubusercontent.com/10364051/92137779-df814d00-ee0d-11ea-8421-a45dea938758.png)

Theoretically one _could_ put DEB and RPM tabs, like is being done for kubeadm now.

![kubeadm-installation](https://user-images.githubusercontent.com/10364051/92138043-2ff8aa80-ee0e-11ea-8ab4-e4c3418121c6.png)

But then there would be a distro tab inside an operating system tab, and it would be ugly.

And of course trying to get apt and yum working is like a whole **class** of fail on its own...
It is working for kubectl and kubeadm, but minikube is not allowed in the same repository.

We could of course "untab" the OS, but then the page would be longer rather than shorter ?

2020-09-12 11:56 UTC, afbjorklund commented
@priyawadhwa : we don't usually have priorities on PRs, so if we don't want to merge it as-is we need a backlog issue (for brew)

@medyagh : maybe we can discuss it on the next meeting, if you think that the Linux install page is indeed becoming too long ?

![minikube-linux-install-brew](https://user-images.githubusercontent.com/10364051/92994982-809f9000-f4ff-11ea-8774-bf92b2b5b1c2.png)

At the very least, we should probably work with @inductor and others to make the two install pages a bit more similar than now:

* https://kubernetes.io/docs/tasks/tools/install-minikube/

* https://minikube.sigs.k8s.io/docs/start/

2020-10-13 00:54 UTC, medyagh requested changes
I am okay with adding home brew as an option but i would like to know first, who Maintains this minikube homebrew for linux ?

is it an automatic process to ensure we have brew for linux ? does that mean whenever we update the mac homebrew they automatically add linux version too ? till I dont know the details I am not comfortable merging this
and also we dont need the extra lines that says if it didnt work do this or that. first page should be as short as possible. u can have a Link to another page that says for more info see... (homebrew links)

2020-10-23 06:05 UTC, afbjorklund commented
> I am okay with adding home brew as an option but i would like to know first, who Maintains this minikube homebrew for linux ?

It is the same package:

https://github.com/Homebrew/homebrew-core/commits/master/Formula/minikube.rb

https://github.com/Homebrew/linuxbrew-core/commits/master/Formula/minikube.rb

Basically only header changes:

```ruby
class Minikube < Formula
  desc "Run a Kubernetes cluster locally"
  homepage "https://minikube.sigs.k8s.io/"
  url "https://github.com/kubernetes/minikube.git",
      tag:      "v1.14.0",
      revision: "b09ee50ec047410326a85435f4d99026f9c4f5c4"
  license "Apache-2.0"
  head "https://github.com/kubernetes/minikube.git"

...
```

And then the build system builds the binaries ("bottles") from the source ("formulas")

So homebrew is not using the same binaries as available on the github download page.

They call that "[cask](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#casks)", when speaking in :beer:

2020-12-05 12:05 UTC, afbjorklund commented
We close this for now, Brew and Arch are still available - even if undocumented "upstream".

https://formulae.brew.sh/formula/minikube

https://www.archlinux.org/packages/community/x86_64/minikube/

Thanks for your contribution! Maybe a future version of Getting Started will feature them...

2020-12-05 12:05 UTC, closed without merging