add mep for Dedidcated docekr driver
kubernetes/minikube pull request #9296
Opened 2020-09-22 01:08 UTC by medyagh

2020-09-25 18:27 UTC, tstromberg requested changes

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +
Can you clarify why this approach isn't ideal?

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +
Can you include the rest of the standard MEP template text?

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +Each minikube cluster will get it is own network, instead of using docker’s owned default network which is unmodifiable by the user.
s/owned/own/g

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +on “minikube start”, minikube will try to create a docker network at a default subnet
Can you describe how the default subnet was chosen, and what occurs if that default subnet happens to be the one the host is using?

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +if can’t create network, should fall back to docker’s default bridge IP
Move this to the standard Goals section of the MEP template.

2020-09-25 18:27 UTC, tstromberg commented on enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
> +since we own the created network we can assign and calculate the IP.
Could you clarify thiss statement?

2020-11-06 20:06 UTC, priyawadhwa approved these changes

2020-11-16 17:51 UTC, merged