Mention Docker for Linux in registries documentation
kubernetes/minikube pull request #9314
Opened 2020-09-24 08:55 UTC by dominikbraun

Fixes #8925. Anything else we could improve in this documentation section?

2020-09-24 18:27 UTC, medyagh commented
technically there is no difference between docker on winows and docker on macos.

but I think what this doc was meant to do was making sure to make users aware of the Random Port on Docker on MacOS and docker on Windows


on linux the port is same 5000
but on mac os/windows it will give you random port.

2020-09-28 05:21 UTC, afbjorklund requested changes
It doesn't make sense to talk about the "docker virtual machine" on Linux, since there is no Docker Desktop product available (only Docker Engine which doesn't have a VM and doesn't need the `socat`)

2020-09-28 05:26 UTC, afbjorklund commented
It probably needs a **separate** entry on Linux. Normally you would talk to $(minikube ip):5000, as a "insecure registry".

Tunneling localhost:5000 to the Minikube VM is _one_ way of getting around the SSL requirement (localhost is "insecure").

2020-09-29 16:20 UTC, medyagh requested changes

2020-09-29 16:20 UTC, medyagh commented on site/content/en/docs/handbook/registry.md
> +### docker on Linux/macOS
this doesn't seem right, 

docker on Linux is one way
docker on mac os and windows is the other way.

this is due to docker limitaitons on non-linux

and the limitation is, on non-linux we can not use the port 5000. but use a different random port.

2020-09-29 16:20 UTC, medyagh commented on site/content/en/docs/handbook/registry.md
> +### docker on Linux/macOS
this doc needs to be reviewed from scratch to make sure the language is correct all the way.

2020-10-02 14:00 UTC, dominikbraun commented
I get the point, just adding "Linux" to the heading doesn't seem to make sense here. Since correctly documenting this for all operating systems isn't quite easy, I'm going to close this PR for the time being.

2020-10-02 14:00 UTC, closed without merging