WIP: expose extra ports (docker driver)
kubernetes/minikube pull request #9404
Opened 2020-10-06 11:43 UTC by ToonvanStrijp

expose extra ports when using docker driver. This fixes issue: #8008 #8398

Usage:
```
minikube start --driver=docker \
--docker-ports=8080:30000 \
--docker-ports=8443:30001 \
--docker-ports=15021:30002 
```

Please let me know if changes are necessary 😃

2020-10-06 11:49 UTC, TravisBuddy commented
## Travis tests have failed

Hey @ToonvanStrijp,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;kubernetes&#x2F;minikube&#x2F;jobs&#x2F;733297210">View build log</a>


<details>
  <summary>
    <strong>
     make test
    </strong>
  </summary>

```
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.14.6.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.14.6.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.13.1 -X k8s.io/minikube/pkg/version.isoVersion=v1.13.1 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="82e244b6a111df7520b5e2a4e2af3156843277ab" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v3" ./test.sh
= schema_check ==========================================================
go: downloading github.com/xeipuuv/gojsonschema v0.0.0-20180618132009-1d523034197f
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
ok
= go test ===============================================================
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/machine-drivers/machine v0.7.1-0.20200810185219-7d42fed1b770
go: downloading k8s.io/api v0.17.3
go: downloading k8s.io/apimachinery v0.17.3
go: downloading k8s.io/kubernetes v1.18.5
go: downloading github.com/phayes/freeport v0.0.0-20180830031419-95f893ade6f2
go: downloading k8s.io/client-go v0.17.3
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading k8s.io/kubectl v0.17.3
go: downloading github.com/otiai10/copy v1.0.2
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/mattn/go-runewidth v0.0.7
go: downloading golang.org/x/crypto v0.0.0-20200510223506-06a226fb4e37
go: downloading github.com/blang/semver v3.5.0+incompatible
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/afbjorklund/go-containerregistry v0.0.0-20200902152226-fbad78ec2813
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/cloudevents/sdk-go/v2 v2.1.0
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading cloud.google.com/go v0.57.0
go: downloading github.com/pkg/browser v0.0.0-20160118053552-9302be274faa
go: downloading github.com/afbjorklund/go-getter v1.4.1-0.20190910175809-eb9f6c26742c
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/juju/mutex v0.0.0-20180619145857-d21b13acf4bf
go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: downloading github.com/intel-go/cpuid v0.0.0-20181003105527-1a4a6f06a1c6
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/cheggaaa/pb v1.0.27
go: downloading github.com/hashicorp/go-safetemp v1.0.0
go: downloading github.com/mitchellh/go-ps v0.0.0-20190716172923-621e5597135b
go: downloading github.com/docker/docker v1.4.2-0.20190924003213-a8608b5b67c7
go: downloading github.com/cheggaaa/pb/v3 v3.0.1
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/hooklift/iso9660 v0.0.0-20170318115843-1cf07e5970d8
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
go: downloading cloud.google.com/go/storage v1.8.0
go: downloading google.golang.org/api v0.25.0
go: downloading github.com/hashicorp/go-version v1.2.0
go: downloading github.com/google/go-querystring v1.0.0
go: downloading go.opencensus.io v0.22.3
go: downloading k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
go: downloading github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/mitchellh/go-testing-interface v1.0.0
go: downloading github.com/pkg/profile v0.0.0-20161223203901-3a8809bd8a80
go: downloading github.com/juju/errors v0.0.0-20190806202954-0232dcc7464d
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/aws/aws-sdk-go v1.31.6
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/google/slowjam v0.0.0-20200530021616-df27e642fe7b
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner v4.0.0+incompatible
go: downloading google.golang.org/grpc v1.29.1
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner/v5 v5.0.0
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/c4milo/gotoolkit v0.0.0-20170318115440-bcc06269efa9
go: downloading github.com/fatih/color v1.9.0
go: downloading google.golang.org/protobuf v1.24.0
go: downloading golang.org/x/sys v0.0.0-20200523222454-059865788121
go: downloading golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading google.golang.org/genproto v0.0.0-20200527145253-8367513e4ece
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/machine-drivers/docker-machine-driver-vmware v0.1.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
go: downloading github.com/spf13/viper v1.7.0
go: downloading k8s.io/component-base v0.17.3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/prometheus/client_golang v1.4.1
go: downloading github.com/docker/cli v0.0.0-20200303162255-7d407207c304
go: downloading github.com/ulikunitz/xz v0.5.7
go: downloading github.com/libvirt/libvirt-go v3.4.0 [...]

2020-10-06 12:16 UTC, ToonvanStrijp commented
/assign @sharifelgamal

2020-10-06 23:33 UTC, medyagh requested changes

2020-10-07 02:04 UTC, arielmoraes commented
Not an admin here, but I was analyzing the changes, and I have a question: as the start command already binds some ports to the 127.0.0.1 IP address, if the user choose to expose those ports will them be bound to the correct IP for exposure (0.0.0.0 or any other supplied)? That is, if the user provides custom ports (including the default ones), those have to have priority over the default ones.

2020-10-07 16:11 UTC, ToonvanStrijp commented on cmd/minikube/cmd/start_flags.go
> +	dockerPorts             = "docker-ports"
@medyagh totally agree! Changes are made ;)

2020-10-07 20:56 UTC, medyagh approved these changes
thank you very much for this PR

2020-10-07 20:56 UTC, merged

2021-09-14 15:35 UTC, mans0954 commented
It's important to note that the `--ports` option only applies when first creating the `minikube` docker container. If `minikube start --ports=...` is called when the `minikube` container already exists, then the option is ignored.

e.g.
```
# Delete any exisitng `minikube` container
minikube delete
# Create a new `minikube` container listening on ports `80` and `443` on localhost
minikube start --ports=127.0.0.1:443:443 --ports=127.0.0.1:80:80
# Check it worked
docker port minikube
2376/tcp -> 127.0.0.1:49271
32443/tcp -> 127.0.0.1:49268
443/tcp -> 127.0.0.1:443
5000/tcp -> 127.0.0.1:49270
80/tcp -> 127.0.0.1:80
8443/tcp -> 127.0.0.1:49269
22/tcp -> 127.0.0.1:49272
```
Probably I'm a bit dim, but it took me a couple of hours to work this out, so posting it here in the hope that it helps someone else.

2022-02-16 20:59 UTC, kliarist commented
What would be the syntax if I need to have 2 minikube nodes (docker). I tried the below with no luck:

$ minikube start --nodes 2 --driver=docker --ports=":30778" --ports=":9001"
😄  minikube v1.25.1 on Fedora 35 (arm64)
✨  Using the docker driver based on user configuration

❌  Exiting due to MK_USAGE: Sorry, one of the ports provided with --ports flag is not valid [:30778 :9001]

2022-07-22 16:18 UTC, marhav20 commented
Seems that for multi-node minikube the --ports parameter is also sent to the workers causing a "port is already allocated" error. (minikube version 1.26.0)

minikube start -driver=docker --nodes=2 --ports=9000:9000