updating the controller name in ingress-nginx-controller-patch.yaml
kubernetes/minikube pull request #9413
Opened 2020-10-07 20:01 UTC by nprajilesh

2020-10-07 21:07 UTC, medyagh requested changes
@nprajilesh thank you for this PR,

do you mind sharing the before/after this PR output ? to see if this PR fixed the bug ?

2020-10-08 06:13 UTC, nprajilesh commented
@medyagh I've updated the PR description with before/after details.

2020-10-08 20:23 UTC, medyagh approved these changes

2020-10-08 20:24 UTC, merged

2020-10-11 10:02 UTC, nprajilesh commented
Hey @medyagh I'm participating in Hacktoberfest, would you mind adding the **hacktoberfest-accepted** label to this PR.