start gluster with no auth
kubernetes/minikube pull request #9471
Opened 2020-10-15 08:10 UTC by tbox1911

fixes #8846

2020-10-15 08:14 UTC, tbox1911 commented
/assign @medyagh

2020-10-15 17:23 UTC, medyagh requested changes
do u mind adding documentation for gluster addon and documenting this issue?

there could be a page about this addon simmilar to this
https://minikube.sigs.k8s.io/docs/handbook/addons/gcp-auth/

2020-10-16 00:27 UTC, medyagh commented
@tbox1911  please make sure to sign the CLA https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

2020-10-16 15:33 UTC, tbox1911 commented
I sign the CLA

2020-11-05 07:48 UTC, RA489 commented
> I sign the CLA

/check-cla

2020-11-24 19:26 UTC, medyagh commented
@tbox1911 seems like it didnt go through the CLA, please check if u are using the same email in git as in CLA sign

2020-12-09 19:19 UTC, medyagh commented
@tbox1911 I would like to accept this PR but the CLA is required. 
also needs to rebase the PR. do u mind checking if your email is the same as the one you logged in in "git" for the CLA ?

2020-12-10 08:06 UTC, tbox1911 commented
Hi,

Maybe I use the wrong email, anyway I'll rebase this PR  and double check
my login for the CLA
best regards,

On Wed, Dec 9, 2020 at 8:20 PM Medya Ghazizadeh <notifications@github.com>
wrote:

> @tbox1911 <https://github.com/tbox1911> I would like to accept this PR
> but the CLA is required.
> also needs to rebase the PR. do u mind checking if your email is the same
> as the one you logged in in "git" for the CLA ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/minikube/pull/9471#issuecomment-741992146>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA6NNEVTBQMEWIC54DO5TQDST7EW5ANCNFSM4SRUPFZA>
> .
>

2021-01-06 19:31 UTC, spowelljr commented
@tbox1911 Any update on signing the CLA?

2021-01-27 19:29 UTC, priyawadhwa commented
Hey @tbox1911 this PR needs the following before we can merge:

1. A rebase to resolve merge conflicts
2. A signed CLA as described [here](https://github.com/kubernetes/minikube/pull/9471#issuecomment-708979883)

Since this PR has been quiet for a few weeks now, I'm going to temporarily close it. Whenever you have a chance to address the above, please reopen and we can get it merged!

2021-01-27 19:29 UTC, closed without merging