hack/update: base library
kubernetes/minikube pull request #9526
Opened 2020-10-22 19:27 UTC by prezha

fixes: #9464 

pr #9464 ("automate update processes") split: part 1/4 - this one should be the first one to merge

includes:
 - update.go: package init, base struct w/ method, and functions
 - filesystem.go: update local filesystem repo
 - github.go: get greatest stable and latest releases, find/create PR,
   and update remote GitHub repo
 - registry.go: manage images (eg, pull, tag, etc.) and update container
   registries

2020-10-22 20:52 UTC, medyagh requested changes
thank you for splitting the work into smaller parts
do you mind choosing a more declaring name, for both the PR and also the folder, so it is obvious what is the "update" for

2020-10-22 21:05 UTC, prezha commented
@medyagh no worries
also, please note that this part is still wip - i'll update when it's ready (in the next few hours) so that it's not reviewed multiple times...

not sure how to rename the update folder (and the pr), as it will contain more declaring subfolders and files like:
- part 2 pr would be named `hack-update--kubernetes-version` and will contain script: `hack/update/kubernetes_version/update_kubernetes_version.go`,
- part 3 pr would be named `hack-update--golang-version` and will contain script: `hack/update/golang_version/update_golang_version.go`, and
- part 4 pr would be named `hack-update--kicbase-version` and will contain script: `hack/update/kicbase_version/update_kicbase_version.go`

does that makes sense or we need to have something more specific names? (if latter - please help with proposals ! :))

2020-10-28 23:25 UTC, prezha commented
this one should be ok to merge now

2020-10-29 02:29 UTC, TravisBuddy commented
## Travis tests have failed

Hey @prezha,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;kubernetes&#x2F;minikube&#x2F;jobs&#x2F;739718219">View build log</a>


<details>
  <summary>
    <strong>
     make test
    </strong>
  </summary>

```
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.14.2 -X k8s.io/minikube/pkg/version.isoVersion=v1.14.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="85b916981a29ee40585eab0a4a91de5b8e3d245a" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v3" ./test.sh
= make lint =============================================================
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/linux/amd64
golangci/golangci-lint info installed out/linters/golangci-lint
WARN [runner] Can't run linter goanalysis_metalinter: S1016: failed prerequisites: [(inspect@k8s.io/minikube/hack/update/kubernetes_version, isgenerated@k8s.io/minikube/hack/update/kubernetes_version): analysis skipped: errors in package: [/home/travis/gopath/src/github.com/kubernetes/minikube/hack/update/kubernetes_version/update_kubernetes_version.go:76:32: GHVersions not declared by package update]] 
WARN [runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/home/travis/gopath/src/github.com/kubernetes/minikube/hack/update/kubernetes_version/update_kubernetes_version.go:76:32: GHVersions not declared by package update] 
ERRO Running error: buildir: analysis skipped: errors in package: [/home/travis/gopath/src/github.com/kubernetes/minikube/hack/update/kubernetes_version/update_kubernetes_version.go:76:32: GHVersions not declared by package update] 
Makefile:434: recipe for target 'lint-ci' failed
make[1]: *** [lint-ci] Error 3
= go mod ================================================================
ok
= boilerplate ===========================================================
ok
Makefile:315: recipe for target 'test' failed
make: *** [test] Error 4
travis_time:end:108b7ff0:start=1603935856795869053,finish=1603936072378825257,duration=215582956204,event=script
```

</details>


###### TravisBuddy Request Identifier: 8dd81090-198e-11eb-a6ec-b9eb403ed3be

2020-10-30 23:45 UTC, medyagh commented
PR needs lint

2020-10-30 23:45 UTC, medyagh requested changes
plz check lint

2020-10-31 01:27 UTC, prezha commented
> plz check lint

@medyagh, yes, the lint error here was expected - please see:

https://github.com/kubernetes/minikube/pull/9526#issuecomment-718265171 above:
> this one should be ok to merge now (lint error `hack/update/kubernetes_version/update_kubernetes_version.go:76:32: GHVersions not declared by package update` is covered in pr #9529)

and

https://github.com/kubernetes/minikube/pull/9529#issuecomment-718264649:
> @tstromberg similar as with pr #9532:
> 
> the conflicts were due to the pr #9464 (the original one - before i've split it into several prs) got merged first, and i had a couple of changes made in those individual prs; essentially my fault, i should have had closed the original pr right after the split (but left it just in case anyone wanted to compare)...
> 
> i've fixed this one now but had to also add here the `base library` from pr #9526 to resolve dependencies, should be ok to merge this as well as pr #9526 (i'll resolve the conflicts there if any)

we can:
- merge this one and then also with merging #9529 everything should be fine,
or
- merge #9529 first and then this one (i'll resolve any conflicts)

or if you have a better proposal - please share your thoughts

2020-11-11 00:44 UTC, closed without merging

2020-11-11 00:59 UTC, prezha commented
this one got automatically closed after merging #9529 and rebasing, as explained in https://github.com/kubernetes/minikube/pull/9529#issuecomment-718264649