hack/update: kubernetes version
kubernetes/minikube pull request #9529
Opened 2020-10-22 22:35 UTC by prezha

fixes: #9464
fixes: #4392
fixes: #9384 

pr #9464 ("automate update processes") split: part 2/4:
- includes: `hack/update/kubernetes_version/update_kubernetes_version.go`
- removes: `hack/kubernetes_version/update_kubernetes_version.go`

2020-10-23 00:56 UTC, TravisBuddy commented
## Travis tests have failed

Hey @prezha,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;kubernetes&#x2F;minikube&#x2F;jobs&#x2F;738167127">View build log</a>


<details>
  <summary>
    <strong>
     make test
    </strong>
  </summary>

```
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.14.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.14.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="3b670001c532a86f3da0a6221b200f76f741da4e" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v3" ./test.sh
= make lint =============================================================
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/linux/amd64
golangci/golangci-lint info installed out/linters/golangci-lint
WARN [runner] Can't run linter goanalysis_metalinter: S1021: failed prerequisites: [(inspect@k8s.io/minikube/hack/update/kubernetes_version, isgenerated@k8s.io/minikube/hack/update/kubernetes_version): analysis skipped: errors in package: [/home/travis/gopath/src/github.com/kubernetes/minikube/hack/update/kubernetes_version/update_kubernetes_version.go:35:2: could not import k8s.io/minikube/hack/update (hack/update/kubernetes_version/update_kubernetes_version.go:35:2: cannot find module providing package k8s.io/minikube/hack/update: module k8s.io/minikube/hack/update: reading https://proxy.golang.org/k8s.io/minikube/hack/update/@v/list: 410 Gone
	server response: not found: module k8s.io/minikube/hack/update: no matching versions for query "latest")]] 
WARN [runner] Can't run linter unused: buildir: failed to load package : could not load export data: no export data for "k8s.io/minikube/hack/update" 
ERRO Running error: buildir: failed to load package : could not load export data: no export data for "k8s.io/minikube/hack/update" 
Makefile:434: recipe for target 'lint-ci' failed
make[1]: *** [lint-ci] Error 3
= go mod ================================================================
go: finding module for package k8s.io/minikube/hack/update
k8s.io/minikube/hack/update/kubernetes_version imports
	k8s.io/minikube/hack/update: cannot find module providing package k8s.io/minikube/hack/update: module k8s.io/minikube/hack/update: reading https://proxy.golang.org/k8s.io/minikube/hack/update/@v/list: 410 Gone
	server response: not found: module k8s.io/minikube/hack/update: no matching versions for query "latest"
= boilerplate ===========================================================
ok
Makefile:315: recipe for target 'test' failed
make: *** [test] Error 6
travis_time:end:04f859c0:start=1603414152432289556,finish=1603414366384601606,duration=213952312050,event=script
```

</details>


###### TravisBuddy Request Identifier: 9ddb8210-14ca-11eb-aff7-dd8cbeb067cc

2020-10-28 18:12 UTC, tstromberg requested changes
Looks good, but references `hack/update` directory which doesn't yet exist. We'll need to defer merging until that directory is filled in. 

Please resolve this comment once that code is merged.

2020-10-28 18:18 UTC, tstromberg commented
Dependency updated - can you resolve the conflicts?

2020-10-28 23:23 UTC, prezha commented
@tstromberg similar as with pr #9532:

the conflicts were due to the pr #9464 (the original one - before i've split it into several prs) got merged first, and i had a couple of changes made in those individual prs; essentially my fault, i should have had closed the original pr right after the split (but left it just in case anyone wanted to compare)...

i've fixed this one now but had to add `base library` from pr #9526 to resolve dependencies, should be ok to merge this as well as pr #9526 (i'll resolve the conflicts there if any)

2020-11-07 20:19 UTC, TravisBuddy commented
## Travis tests have failed

Hey @prezha,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;kubernetes&#x2F;minikube&#x2F;jobs&#x2F;742131330">View build log</a>


<details>
  <summary>
    <strong>
     make test
    </strong>
  </summary>

```
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.14.2 -X k8s.io/minikube/pkg/version.isoVersion=v1.14.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="510b1efde10a8973127ba93718ba40564566eb57" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v3" ./test.sh
= schema_check ==========================================================
go: downloading github.com/xeipuuv/gojsonschema v0.0.0-20180618132009-1d523034197f
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
ok
= go test ===============================================================
go: downloading github.com/blang/semver v3.5.0+incompatible
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/otiai10/copy v1.0.2
go: downloading k8s.io/client-go v0.17.3
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading k8s.io/api v0.17.3
go: downloading github.com/machine-drivers/machine v0.7.1-0.20200810185219-7d42fed1b770
go: downloading k8s.io/kubectl v0.17.3
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/juju/mutex v0.0.0-20180619145857-d21b13acf4bf
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading k8s.io/apimachinery v0.17.3
go: downloading github.com/afbjorklund/go-containerregistry v0.0.0-20200902152226-fbad78ec2813
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading github.com/mitchellh/mapstructure v1.3.1
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/juju/errors v0.0.0-20190806202954-0232dcc7464d
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/intel-go/cpuid v0.0.0-20181003105527-1a4a6f06a1c6
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/docker/docker v1.4.2-0.20190924003213-a8608b5b67c7
go: downloading github.com/libvirt/libvirt-go v3.4.0+incompatible
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/go-logr/logr v0.3.0
go: downloading github.com/spf13/cobra v1.0.0
go: downloading cloud.google.com/go v0.57.0
go: downloading golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/docker/cli v0.0.0-20200303162255-7d407207c304
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/imdario/mergo v0.3.9
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
go: downloading github.com/juju/clock v0.0.0-20190205081909-9c5c9712527c
go: downloading golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
go: downloading github.com/sayboras/dockerclient v1.0.0
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner v4.0.0+incompatible
go: downloading github.com/cloudevents/sdk-go/v2 v2.1.0
go: downloading cloud.google.com/go/storage v1.8.0
go: downloading gopkg.in/ini.v1 v1.56.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner/v5 v5.0.0
go: downloading github.com/google/gofuzz v1.1.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading github.com/google/slowjam v0.0.0-20200530021616-df27e642fe7b
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/cloudfoundry-attic/jibber_jabber v0.0.0-20151120183258-bcc4c8345a21
go: downloading google.golang.org/api v0.25.0
go: downloading github.com/phayes/freeport v0.0.0-20180830031419-95f893ade6f2
go: downloading go.opencensus.io v0.22.3
go: downloading github.com/mattn/go-runewidth v0.0.7
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/prometheus/client_golang v1.4.1
go: downloading github.com/mitchellh/go-ps v0.0.0-20190716172923-621e5597135b
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/hooklift/iso9660 v0.0.0-20170318115843-1cf07e5970d8
go: downloading google.golang.org/grpc v1.29.1
go: downloading google.golang.org/protobuf v1.24.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/pkg/browser v0.0.0-20160118053552-9302be274faa
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
go: downloading github.com/googleapis/gnostic v0.3.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/lightstep/tracecontext.go v0.0.0-20181129014701-1757c391b1ac
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/cheggaaa/pb v1.0.27
go: downloading k8s.io/kubernet [...]

2020-11-10 22:28 UTC, tstromberg approved these changes

2020-11-10 22:28 UTC, merged