replace set-env with Env Files in GitHub Actions
kubernetes/minikube pull request #9542
Opened 2020-10-23 21:37 UTC by prezha

fixes: #9541

due to the security vulnerability, GitHub Actions deprecating set-env command and replace it with Environment Files

more details are in the issue description

2020-10-26 21:19 UTC, medyagh commented
@prezha seems like the windows tests didn't like it
```
 $numFail=(echo $Env:STAT | jq '.NumberOfFail')
  $failedTests=( echo $Env:STAT | jq '.FailedTests')
  $numPass=$(echo $Env:STAT | jq '.NumberOfPass')
  $passedTests=( echo $Env:STAT | jq '.PassedTests')
  echo "*******************${numPass} Passes :) *******************"
  echo $passedTests
  echo "*******************************************************"
  echo "---------------- ${numFail} Failures :( ----------------------------"
  echo $failedTests
  echo "-------------------------------------------------------"
  If ($numFail -gt 0){ exit 2 }
  If ($numPass -eq 0){ exit 2 }
  If ($numPass -lt 33){ exit 2 }
  If ($numFail -eq 0){ exit 0 }
  shell: C:\windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    GOPROXY: https://proxy.golang.org
    TIME_ELAPSED: time
    JOB_NAME: functional_docker_windows
    GOPOGH_RESULT: 
    STAT: 
    GOROOT: C:\Users\jenkins\actions-runner\_work\_tool\go\1.15.2\x64
******************* Passes :) *******************
*******************************************************
----------------  Failures :( ----------------------------
-------------------------------------------------------
Error: Process completed with exit code 1.
```

we used the set:env to pass arround the result of the test from previous step

2020-10-26 21:19 UTC, medyagh requested changes
lets ensure the windows test results are passed to the End Result Step

2020-10-27 22:33 UTC, prezha commented
@medyagh thank you for the review
i've made changes to the pr and windows test results now seem to be passed correctly to the End Result Step?

2020-10-28 19:30 UTC, medyagh reviewed
looks good, do you mind pulling upstream master, to ensure get latest gh yaml

2020-10-28 19:52 UTC, medyagh commented
on my mac it asked for me to enter a password, it is not clear what i am supposed to enter?
<img width="469" alt="Screen Shot 2020-10-28 at 12 52 26 PM" src="https://user-images.githubusercontent.com/4564227/97489182-71906800-191c-11eb-9adb-6deb4f437e6c.png">

2020-10-30 23:38 UTC, medyagh approved these changes
Thank you very much @prezha

2020-10-30 23:38 UTC, merged

2020-10-31 01:28 UTC, prezha commented
> Thank you very much @prezha

you are most welcome @medyagh!