add ImageRepository to addons templates
kubernetes/minikube pull request #9551
Opened 2020-10-25 14:28 UTC by yehiyam

fixes #8298

2020-10-28 20:10 UTC, medyagh requested changes
do you mind putting in the PR description an example usage of this ? the Before and After this PR

otherwise the code looks good

2020-10-29 08:51 UTC, yehiyam commented
@medyagh I've updated the PR description

2020-11-03 15:27 UTC, yehiyam commented
@medyagh, @tstromberg  did you have a chance to look over this PR?

2020-11-10 18:25 UTC, tstromberg approved these changes
Looks great. Thank you!

2020-11-10 18:25 UTC, tstromberg approved these changes

2020-11-10 18:25 UTC, merged