Bump kicbase
kubernetes/minikube pull request #9604
Opened 2020-11-05 20:46 UTC by medyagh

building changes on HEAD

2020-11-05 21:10 UTC, medyagh commented
/ok-to-test

2020-11-05 21:27 UTC, tstromberg requested changes
Please split the Makefile & code change, In the unlikely case that this PR needs to reverted. Thanks!

2020-11-05 21:27 UTC, tstromberg commented on Makefile
> +push-docker: # Push docker image base on to IMAGE variable (used internaly by other targets)
"internally"

2020-11-05 22:55 UTC, sharifelgamal approved these changes

2020-11-06 06:13 UTC, medyagh commented
/retest-this-please

2020-11-06 22:31 UTC, merged