Add ssh-host command for getting the ssh host keys
kubernetes/minikube pull request #9630
Opened 2020-11-07 17:43 UTC by afbjorklund

This is similar to the existing minikube "ssh-key" command, but gets
the content of the host key instead of the path to the identity key.

The output of this command can be added to the ~/.ssh/known_hosts,
for strict host key authentication. For instance when using Docker.

For #9229
And #9548

2020-11-07 17:49 UTC, TravisBuddy commented
## Travis tests have failed

Hey @afbjorklund,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;kubernetes&#x2F;minikube&#x2F;jobs&#x2F;742111171">View build log</a>


<details>
  <summary>
    <strong>
     make test
    </strong>
  </summary>

```
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.2.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/gopath/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.14.2 -X k8s.io/minikube/pkg/version.isoVersion=v1.14.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="eead694850c808377bf7bfd3feee7630df4baa04" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v3" ./test.sh
= schema_check ==========================================================
go: downloading github.com/xeipuuv/gojsonschema v0.0.0-20180618132009-1d523034197f
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
ok
= go test ===============================================================
go: downloading k8s.io/client-go v0.17.3
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/machine-drivers/machine v0.7.1-0.20200810185219-7d42fed1b770
go: downloading github.com/google/slowjam v0.0.0-20200530021616-df27e642fe7b
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading github.com/spf13/cobra v1.0.0
go: downloading k8s.io/apimachinery v0.17.3
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading github.com/docker/docker v1.4.2-0.20190924003213-a8608b5b67c7
go: downloading k8s.io/api v0.17.3
go: downloading k8s.io/kubernetes v1.18.5
go: downloading github.com/afbjorklund/go-containerregistry v0.0.0-20200902152226-fbad78ec2813
go: downloading golang.org/x/exp v0.0.0-20200224162631-6cc2880d07d6
go: downloading github.com/pkg/profile v0.0.0-20161223203901-3a8809bd8a80
go: downloading github.com/phayes/freeport v0.0.0-20180830031419-95f893ade6f2
go: downloading github.com/blang/semver v3.5.0+incompatible
go: downloading github.com/afbjorklund/go-getter v1.4.1-0.20201020145846-c0da14b4bffe
go: downloading github.com/hooklift/iso9660 v0.0.0-20170318115843-1cf07e5970d8
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner v4.0.0+incompatible
go: downloading github.com/otiai10/copy v1.0.2
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/pkg/browser v0.0.0-20160118053552-9302be274faa
go: downloading sigs.k8s.io/sig-storage-lib-external-provisioner/v5 v5.0.0
go: downloading google.golang.org/api v0.25.0
go: downloading github.com/cheggaaa/pb v1.0.27
go: downloading github.com/cheggaaa/pb/v3 v3.0.1
go: downloading github.com/aws/aws-sdk-go v1.31.6
go: downloading github.com/mitchellh/go-testing-interface v1.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/ulikunitz/xz v0.5.7
go: downloading github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
go: downloading github.com/mitchellh/go-ps v0.0.0-20190716172923-621e5597135b
go: downloading github.com/juju/clock v0.0.0-20190205081909-9c5c9712527c
go: downloading github.com/prometheus/client_golang v1.4.1
go: downloading github.com/docker/cli v0.0.0-20200303162255-7d407207c304
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/c4milo/gotoolkit v0.0.0-20170318115440-bcc06269efa9
go: downloading github.com/hashicorp/go-safetemp v1.0.0
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading cloud.google.com/go v0.57.0
go: downloading github.com/juju/mutex v0.0.0-20180619145857-d21b13acf4bf
go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: downloading google.golang.org/grpc v1.29.1
go: downloading cloud.google.com/go/storage v1.8.0
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading k8s.io/klog v1.0.0
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/sayboras/dockerclient v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/cloudevents/sdk-go/v2 v2.1.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/juju/errors v0.0.0-20190806202954-0232dcc7464d
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading go.opencensus.io v0.22.3
go: downloading k8s.io/kube-openapi v0.0.0-20200410145947-61e04a5be9a6
go: downloading k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
go: downloading github.com/googleapis/gnostic v0.3.0
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/cloudfoundry-attic/jibber_jabber v0.0.0-20151120183258-bcc4c8345a21
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading google.golang.org/genproto v0.0.0-20200527145253-8367513e4ece
go: downloading golang.org/x/text v0.3.2
go: downloading golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading google.golang.org/protobuf v1.24.0
go: downloading github.com/hashicorp/go-version v1.2.1
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading k8s.io/component-base v0.17.3
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/opencontainers/go-digest v1. [...]

2020-11-10 18:49 UTC, tstromberg commented
Can you explain in your PR what the problem is that you are trying to solve, and why the approach this PR takes is the best way to go about solving this problem? It would help to provide context.

2020-11-10 19:14 UTC, afbjorklund commented
> Can you explain in your PR what the problem is that you are trying to solve, and why the approach this PR takes is the best way to go about solving this problem? It would help to provide context.

Will do, we broke this PR out from the other work - so it lost the context

https://github.com/kubernetes/minikube/pull/9548#issuecomment-720075600

2020-11-10 19:29 UTC, afbjorklund commented
Added context to PR description.

2020-11-27 01:59 UTC, medyagh approved these changes

2020-11-27 01:59 UTC, medyagh commented
@afbjorklund please check unit test

2020-11-27 11:11 UTC, afbjorklund commented
> @afbjorklund please check unit test

Unrelated to PR, I think ? The help was broken, but fixed by PR #9632

2020-12-08 18:49 UTC, medyagh approved these changes

2020-12-08 18:49 UTC, medyagh requested changes
please run generate docs on this PR

2020-12-09 21:43 UTC, medyagh approved these changes

2020-12-09 21:43 UTC, medyagh commented
/ok-to-test

2020-12-12 17:53 UTC, afbjorklund commented
Somebody broke the documentation on master, failing the unit tests (fix in #9941)

2020-12-17 16:09 UTC, merged