Bug #9607 - Document no support for userns and rootless in Docker driver
kubernetes/minikube pull request #9648
Opened 2020-11-09 19:33 UTC by bleggett

As per #9607 we don't support `userns-remap` or `rootless` Docker engine security options in the Docker driver - so mention that up front.

2020-11-09 21:03 UTC, afbjorklund approved these changes

2020-11-10 22:23 UTC, tstromberg requested changes
Can you provide a link to #9607 or some other relevant GitHub issue in this text? See the other examples in this doc for guidance.

2020-11-12 15:59 UTC, bleggett commented
> Can you provide a link to #9607 or some other relevant GitHub issue in this text? See the other examples in this doc for guidance.

Done.

2020-11-16 18:37 UTC, sharifelgamal commented
Thanks!

2020-11-16 18:37 UTC, merged