fixes #9722, reverting ImageRepository templating for registry-creds-rc.yaml.tmpl
kubernetes/minikube pull request #9725
Opened 2020-11-17 14:39 UTC by fredrik-smedberg

This fixes #9722 by reverting part of yehiyam's add ImageRepository to addons templayes change for the registry-creds addon.

2020-11-17 14:52 UTC, fredrik-smedberg commented
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I've signed the CLA for my Corporation using the same username and e-mail address as used with Github.

2020-11-17 19:00 UTC, medyagh reviewed
I wonder if there is a reson that ImageRepository didn't do the right thing ?

2020-11-17 19:53 UTC, medyagh requested changes
could we fix this in a way that image repositry sitll be respected ?

maybe if we specify the more explicit tag it would help ? like this PR 

https://github.com/kubernetes/minikube/pull/9728/files

2020-11-18 08:27 UTC, yehiyam commented
Hi @fredrik-smedberg and @medyagh 
I believe that the problem is that I missed setting this addon as a template in [addons.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go#L269)

2020-11-18 08:39 UTC, fredrik-smedberg commented
@yehiyam I believe you're correct. I'll try to make the change locally in my environment and verify this, and then change this PR to that solution instead.

2020-11-18 14:39 UTC, alonyb commented
@yehiyam you're right, it's done in #9733 don't worry.

2020-11-18 14:49 UTC, fredrik-smedberg commented
Agreed, let's use #9733 and I'll close this one.

2020-11-18 14:50 UTC, closed without merging