Ability to use a custom TLS certificate with the Ingress
kubernetes/minikube pull request #9797
Opened 2020-11-28 23:05 UTC by msedzins

Description of functionality can be found here: #9335

This is my first contribution to this repository. I'm sorry for any mistakes.

The change is pretty straightforward, however I have a doubts regarding the tests. I can see that there are no tests for similar pieces of functionality when it comes to addons "registry-creds" and "metallb".

However I found integration tests for ingress addon (test/integration/addons_test.go). Maybe I should extend them to test the new functionality?

2020-11-28 23:52 UTC, msedzins commented
/retest

2020-11-29 08:38 UTC, msedzins commented
/retest

2020-11-29 08:41 UTC, msedzins commented
/meow

2020-11-29 08:41 UTC, msedzins commented
/retest

2020-11-29 08:46 UTC, msedzins commented
/test ?

2020-11-29 08:46 UTC, msedzins commented
/test pull-minikube-platform-tests

2020-11-29 08:48 UTC, msedzins commented
/retest

2020-11-29 08:49 UTC, msedzins commented
/test all

2020-11-29 08:50 UTC, msedzins commented
/retest

2020-11-29 08:57 UTC, msedzins commented
Hi, there are 4 tests failing, completely not related to the functionality introduced in this PR, 

Could someone tell me if I should do anything about this?

2020-11-30 18:15 UTC, medyagh requested changes
thanks for this PR @msedzins 
do you mind adding in the PR description the output after this PR using this new feature?

add a short tutotiral in our website 
"how to use custom TLS cert with ingress addon on minikube"
with an example usage of this feature

https://minikube.sigs.k8s.io/docs/tutorials/

2020-11-30 22:58 UTC, msedzins commented
@medyagh Hi, I've added tutorial and extended PR description.

2020-12-04 20:45 UTC, medyagh approved these changes
thank you for this PR

2020-12-04 20:45 UTC, merged